<?php 
if(!$this->ajax){
	echo '<!DOCTYPE html>
<html>
	<head>
		<title>ISTE - Auteurs</title>
		<link rel="stylesheet" type="text/css" href="../css/w2ui.css" />
		<link rel="stylesheet" type="text/css" href="../font/font-awesome/font-awesome.css" />
		<script type="text/javascript">
			var urlP = "../";
		</script>		
		<script type="text/javascript" src="../js/jquery.min.js"></script>
		<script type="text/javascript" src="../js/w2ui.js"></script>
		<script type="text/javascript" src="../js/global.js"></script>
		<script type="text/javascript" src="../js/data.js"></script>
		<script type="text/javascript">
			$(function () {initAll(); });                       		
		</script>		
		</head>
<body>';
}
$idGrid = "gridAut";
?>
<style>
.w2ui-field input {
    width: 400px;
}
.w2ui-field > div > span {
    margin-left: 20px;
}
</style>
<div id="<?php echo $idGrid;?>" style="width: 1200px; height: 600px;"></div>

<script type="text/javascript">
var rs = <?php echo $this->json; ?>;
var itemSelect;
var arrDetail = [{ recid: 0, name: 'URL :', value: 'url' },                
	{name: 'Adresse :', value: 'adresse' },
	{name: 'Code Postal :', value: 'code_postal' },
	{name: 'Ville :', value: 'ville' },
	{name: 'Pays :', value: 'pays' },
	{name: 'Téléphone :', value: 'telephone' },
	{name: 'E-mail :', value: 'mail' }
];
var arrChange=[];

//widget configuration
var pstyle = 'border: 1px solid #dfdfdf; padding: 5px;';
var pstyleDetail = 'background-color: #F0F0C1; border: 1px solid #dfdfdf; padding: 5px;';
var config;

function initAuteur() {

	config = {
		    layout: {
		        name: 'layout_<?php echo $idGrid;?>',
		        padding: 4,
		        panels: [
					{ type: 'main', size: 600, style: pstyle},
		            { type: 'left', size: 754, resizable: true, hidden: true, style: pstyle},
		            { type: 'right', size: 600, resizable: true, hidden: false, style: pstyle}
		        ]
		    },
		    grid: { 
		        name: 'grid_<?php echo $idGrid;?>', 
				header: 'Auteurs',		
		        show: { 
					header			: true,		
		            toolbar			: true,
					toolbarReload   : true,
					toolbarColumns  : true,
		            	toolbarSearch   : true,
		            	toolbarAdd      : true,
		            	toolbarDelete   : true,
		            	toolbarSave		: true,
		        },
		        columnGroups: [
		                       { caption: '', span: 1 },
		                       { caption: 'Informations générales', span: 4 }
		                      ],        
		        columns: [                
		            { field: 'recid', caption: 'ID', size: '50px', sortable: true, resizable: true },
		            { field: 'civilite', caption: 'Civilité', size: '120px', sortable: true, resizable: true, 
		                editable: { type: 'list', items: arrListes['civilites'], showAll: true },
		                render: function (record, index, col_index) {
		                    var html = this.getCellValue(index, col_index);
		                    return html.text ? html.text : html;
		                }
		            },
		            { field: 'prenom', caption: 'Prénom', size: '120px', sortable: true, resizable: true, 
		                editable: { type: 'text' }
		            },
		            { field: 'nom', caption: 'Nom', size: '120px', sortable: true, resizable: true, 
		                editable: { type: 'text' }
		            },
		            { field: 'instNom', caption: 'Institution', size: '100%', sortable: true, resizable: true, 
		                editable: { type: 'combo', items: arrListes['institution'], showAll: true },
		                /*
		                render: function (record, index, col_index) {
		                    var html = rs.filter(function(d){
			                    return d.id == record.id_institution;
			                	});
		                    if(html[0])
			                 	return '<div>'+html[0]+'<button class="w2ui-btn" onclick="getPopup('+record.recid+')"> Details </button></div>';
		                }
		                */
		            },		            
		        ],
		        toolbar: {
		            items: [
		                { id: 'export', type: 'button', caption: 'Exporter', icon: 'fa-file' }
		            ],
		            onClick: function (event) {
		                if (event.target == 'export') {
		                    w2ui.<?php echo $idGrid;?>.add({ recid: w2ui.<?php echo $idGrid;?>.records.length + 1 });
		                }
		            }
		        },
		        records: rs,
		        onSave: function(event) {
		            var changes = w2ui['grid_<?php echo $idGrid;?>'].getChanges();
		            changes.forEach(function(c, i){
			            c.obj = 'auteur';
			            if(c.civilite)c.civilite=c.civilite.text;			            
				        	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
				        			c,
				        			function(html){
				        				if(changes.length==i+1)w2alert(html);
				        			});                        
		            });
		        },
		        onDelete: function(event) {            
					console.log(event);
					var p = {id:itemSelect.recid, obj:'auteur'};
					if(event.force){
			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/delete',
								p,
				            		function(js){
				            			w2alert(js.message);
				           		},"json");
					}
			    },
		        onAdd: function(event) {            
		            w2ui['layout_<?php echo $idGrid;?>'].toggle('left', true);
		            w2ui['layout_<?php echo $idGrid;?>'].hide('main', true);
		            w2ui['layout_<?php echo $idGrid;?>'].hide('right', true);
			    },
		        onClick: function (event) {
		            var g = w2ui['grid_<?php echo $idGrid;?>_detail1'];
		            g.clear();
		            itemSelect = this.get(event.recid);
		            arrDetail.forEach(function(d, i){
		                g.add({ recid: i, name: d.name, value: itemSelect[d.value] });               
		            });
		        }	    
		    },
		    coor : {
		            header: 'Coordonnées',
		            show: {toolbar		: true,
		    				toolbarReload   : false,
		    				toolbarColumns  : false,
		                	toolbarSearch   : false,
		                	toolbarAdd      : false,
		                	toolbarDelete   : false,
		                	toolbarSave		: true,
		                	header: true, 
		                	columnHeaders: false},
		            name: 'grid_<?php echo $idGrid;?>_detail1', 
		            columns: [                
		                { field: 'name', caption: 'Name', size: '100px', style: 'background-color: #efefef; border-bottom: 1px solid white; padding-right: 5px;', attr: "align=right" },
		                { field: 'value', caption: 'Value', size: '100%', editable: { type: 'text' } }
		            ],
					onSave: function(event) {
						var data = {'recid':itemSelect.recid,'obj':'auteur'};
					    var changes = w2ui['grid_<?php echo $idGrid;?>_detail1'].getChanges();
					    changes.forEach(function(d){
					    		data[arrDetail[d.recid].value] = d.value;
					    		itemSelect[arrDetail[d.recid].value] = d.value;
					    });				
						updateBdd('<?php if(!$this->ajax) echo '../'; ?>crud/update', data);
		            }
		    },		    
		    form: { 
		        header: 'Ajouter un auteur',
		        name: 'form_<?php echo $idGrid;?>',
		        fields: [
		            { name: 'civilite', type: 'list'
		            		, options: { items: arrListes['civilites'] }
		        			, html: { caption: 'Civilité', attr: 'size="10"' }
		           	},
		            { name: 'prenom', type: 'text', required: true, html: { caption: 'Prénom', attr: 'size="40" maxlength="40"' } },
		            { name: 'nom', type: 'text', required: true, html: { caption: 'Nom', attr: 'size="40"' } },
		            { name: 'adresse', type: 'text', html: { caption: 'Adresse', attr: 'size="40"' } },
		            { name: 'code_postal', type: 'text', html: { caption: 'Code Postal', attr: 'size="10"' } },
		            { name: 'ville', type: 'text', html: { caption: 'Ville', attr: 'size="40"' } },
		            { name: 'pays', type: 'text', html: { caption: 'Pays', attr: 'size="30"' } },
		            { name: 'telephone', type: 'text', html: { caption: 'Téléphone', attr: 'size="10"' } },
		            { name: 'mail', type: 'email', html: { caption: 'E-mail', attr: 'size="30"' } },
		            { name: 'url', type: 'url', html: { caption: 'URL', attr: 'size="30"' } },
		            { name: 'institution', type: 'combo', options: { items: arrListes['institution'] }
		            		, html: { caption: 'Institution', attr: 'size="30"' } 
		            		}
		        ],
		        actions: {
		            Reset: function () {
		                w2ui['layout_<?php echo $idGrid;?>'].toggle('left', true);
		                w2ui['layout_<?php echo $idGrid;?>'].toggle('main', true);
		                w2ui['layout_<?php echo $idGrid;?>'].toggle('right', true);
		                this.clear();
		            },
		            Save: function () {
		                var errors = this.validate();
		                if (errors.length > 0) return;
		                var g = w2ui['grid_<?php echo $idGrid;?>'];
		                var data = this.record;
		                data.civilite = data.civilite.text; 
		                data.obj = "auteur";
		                this.clear();		                
			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/insert',
							data,
			            		function(js){
								g.add(js.rs);
								g.selectNone();
		                        	w2ui['layout_<?php echo $idGrid;?>'].toggle('left', true);
		                        	w2ui['layout_<?php echo $idGrid;?>'].toggle('main', true);
		    		                w2ui['layout_<?php echo $idGrid;?>'].toggle('right', true);
			            			w2alert(js.message);
			           		},"json");
		            }
		        }
		    },
		    layoutDetail : {
		        name: 'layoutDetail_<?php echo $idGrid;?>',
		        panels: [
		            { type: 'top', size: 248, style: pstyleDetail},
		            { type: 'main', style: pstyleDetail },
		        ]
		    },
		    enumCoordi : { 
	            name     : 'formTheme',
	            show: {toolbar		: true,
	    				toolbarReload   : false,
	    				toolbarColumns  : false,
	                	toolbarSearch   : false,
	                	toolbarAdd      : false,
	                	toolbarDelete   : false,
	                	toolbarSave		: true,
	                	header: true, 
	                	columnHeaders: false},	            
	            header   : 'Coordination - Comité',
	            fields: [
	                { field: 'Coordination - fr', type: 'enum', required: false, 
	                    options: { items: arrListes['collection']['fr'] } },
	                { field: 'Coordination - en', type: 'enum', required: false, 
	                    options: { items: arrListes['collection']['en'] } },
	                { field: 'Comité - fr', type: 'enum', required: false, 
	                    options: { items: arrListes['comite']['fr'] } },
	                { field: 'Comité - en', type: 'enum', required: false, 
	                    options: { items: arrListes['comite']['en'] } },
	            ],
	            onChange: function (event) {
		            if(event.value_new.length && itemSelect){
			            //récupère l'item modifiée
			            if(event.target=="Coordination - fr")
		            			arrChange.push({obj:"coordination",id_collection:event.value_new[0].id,id_auteur:itemSelect["id_auteur"]});
			            if(event.target=="Coordination - en")
	            				arrChange.push({obj:"coordination",id_collection:event.value_new[0].id,id_auteur:itemSelect["id_auteur"]});
			            if(event.target=="Comité - fr")
		            			arrChange.push({obj:"comitexauteur",id_comite:event.value_new[0].id,id_auteur:itemSelect["id_auteur"]});
			            if(event.target=="Comité - en")
	            				arrChange.push({obj:"comitexauteur",id_comite:event.value_new[0].id,id_auteur:itemSelect["id_auteur"]});
		            }
	            },
	            actions: {
		            Save: function () {
		                var errors = this.validate();
		                if (errors.length > 0) return;
		                var data = this.record;
		                arrChange.forEach(function(d, i){
				            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/insert',
										d,
						            		function(js){
				            					if(arrChange.length==i+1){
					            					w2alert(js.message);
					            					arrChange = [];
				            					}
						           		},"json");
				           	//attend pour que les index MYSQL se mettent à jour
				            	setTimeout(function () {var i=1}, 1000);   	
		                });
		            }
		        }
		    }		    
		};
	//
	
    // initialisation
    $('#<?php echo $idGrid;?>').w2layout(config.layout);
    w2ui.layout_<?php echo $idGrid;?>.content('main', $().w2grid(config.grid));
    w2ui.layout_<?php echo $idGrid;?>.content('left', $().w2form(config.form));
    w2ui.layout_<?php echo $idGrid;?>.content('right', $().w2layout(config.layoutDetail));
    w2ui.layoutDetail_<?php echo $idGrid;?>.content('top', $().w2grid(config.coor));    
    w2ui.layoutDetail_<?php echo $idGrid;?>.content('main', $().w2form(config.enumCoordi));    

}
</script>

<?php 
if(!$this->ajax){
	echo '</body>
</html>';
}
?>