<?php 
if(!$this->ajax){
	echo '<!DOCTYPE html>
<html>
	<head>
		<title>ISTE - Droits</title>
		<link rel="stylesheet" type="text/css" href="../css/gestedit.css" />
		<link rel="stylesheet" type="text/css" href="../css/w2ui.css" />
		<link rel="stylesheet" type="text/css" href="../fonts/font-awesome/font-awesome.css" />
		<script type="text/javascript">
			var urlP = "../";
			var uti = '.$this->uti.';
			var fctInit;			
		</script>		
		<script type="text/javascript" src="../js/jquery.min.js"></script>
		<script type="text/javascript" src="../js/w2ui.js"></script>
		<script type="text/javascript" src="../js/global.js"></script>
		<script type="text/javascript" src="../js/data.js"></script>
		<script type="text/javascript" src="../js/log.js"></script>
		<script type="text/javascript" src="../js/d3.js"></script>
		<script type="text/javascript">
			$(function () {
				initAll(initDroit); 
	  			if(uti)
					utiIsConnect();
	  			else
		    	  	diagLogin.showModal();				
			});                       		
		</script>		
		</head>
<body>
';
}
$idPage = "Droit";
?>

<div id="<?php echo $idPage;?>" style="width: 100%; height: 1000px;"></div>

<script type="text/javascript">



var rsVenteISBN = <?php echo $this->jsonISBN; ?>;
var rsVenteAuteur = <?php echo $this->jsonAuteur; ?>;
var rsFichierImport;
var rsDev = <?php echo $this->rsDev; ?>;
var rsDroitParam = <?php echo $this->rsDroitParam; ?>;
var rsParamMail = <?php echo $this->rsParamMail; ?>;

//widget configuration
var pstyle = 'border: 1px solid #dfdfdf; padding: 5px;';
var pstyleDetail = 'background-color: #F0F0C1; border: 1px solid #dfdfdf; padding: 5px;';
var config;
var idPLU, idPCU, itemSelectAuteur, itemSelectISBN, itemSelectVente, rsIsbnLivre, rsIsbnPrix, urlPDF=false;

function initDroit() {
	var tabsFichierVente = {
		active: 'tab0',
		tabs: [{ id: 'tab0', caption: "Rapports générés" },{ id: 'tab1', caption: "Détails des ventes" }
			,{ id: 'tab2', caption: "Détails des royalties" }],
		onClick: function (event) {
			if(event.target=="tab0"){
				clearTabs();
				initPdf();
			}else if(event.target=="tab1"){
				if(w2ui['grid_<?php echo $idPage;?>_detail'])w2ui['grid_<?php echo $idPage;?>_detail'].destroy();
				w2ui.layout_<?php echo $idPage;?>.content('main', $().w2grid(config.gridVenteDetail));
			}else if(event.target=="tab2"){
				if(w2ui['grid_<?php echo $idPage;?>_royalties'])w2ui['grid_<?php echo $idPage;?>_royalties'].destroy();
				w2ui.layout_<?php echo $idPage;?>.content('main', $().w2grid(config.gridVenteRoyalties));				
			}

			//récupère les identifiants sélectionnés
			var ids, table, c =  w2ui.layout_<?php echo $idPage;?>_top.content('main');
			if(c.name=='layout_<?php echo $idPage;?>_fichier'){
				table = 'fichier';
				ids = w2ui['grid_<?php echo $idPage;?>_fichier_import'].getSelection();
			}
			if(c.name=='grid_<?php echo $idPage;?>_vente_isbn'){
				table = 'isbn';
				ids = w2ui['grid_<?php echo $idPage;?>_vente_isbn'].getSelection();
			}
			if(c.name=='grid_<?php echo $idPage;?>_vente_auteur'){
				table = 'auteur';
				ids = w2ui['grid_<?php echo $idPage;?>_vente_auteur'].getSelection();
			}
			//affiche les données			
			getVenteData(ids, table);
		},
		onClose: function (event) {
			this.click('tab0');
		}
	};

	config = {

			formParam : {
				name   : 'form_<?php echo $idPage;?>_param',
				url    : //'server/post',
				{
					save : urlP+'crud/saveformparammail'
				},				
				fields : [
					{ field: 'sans_redevance',   type: 'textarea', html: { caption: 'Email <br><br> sans <br><br> redevance :', page: 0, column: 0, attr: 'style="height: 200px;width:400px"' }, required: true},
					{ field: 'avec_redevance',   type: 'textarea', html: { caption: 'Email <br><br> avec <br><br> redevance :', page: 0, column: 1, attr: 'style="height: 200px;width:400px"' }, required: true },
					{ field: 'email', type: 'email', html: { caption: "Email de l'envoyeur :", page: 0, column: 2 }, required: true },
					{ field: 'password', type: 'password', html: { caption: "Mot de passe email :", page: 0, column: 2 }, required: true },
					{ field: 'nom', type: 'text', html: { caption: "Nom de l'envoyeur :", page: 0, column: 2 }, required: true },
					{ field: 'sujet', type: 'text', html: { caption: "Sujet de l'email :", page: 0, column: 2 }, required: true },
					/*
					{ field: 'periode1', type: 'date', options:{ end: $('input[name=periode2]'),format: 'dd-mm-yyyy'},  html: {   caption: 'Début période :', page: 0, column: 2 }, required: true },
					{ field: 'periode2', type: 'date', options:{ start: $('input[name=periode1]'),format: 'dd-mm-yyyy'},  html: {  caption: 'Fin période :', page: 0, column: 2 }, required: true }
					*/
				],
				actions: {
					'Effacer': function () {
						this.clear();
					},
					'Enregistrer': function () {
						this.validate();
						this.save(function (data) {
							 	if (data.status == "success")
								 	w2alert(data.message); 
								else
									w2alert('Erreur : '+data.message);
							 });
					}
				},
				record: rsParamMail
			},

		    layoutVente: {
		        name: 'layout_<?php echo $idPage;?>',
		        padding: 4,
		        panels: [
		 		    { type: 'top', size: 400, style: pstyle},
					{ type: 'main',  
						style: 'background-color: white; border: 1px solid silver; border-top: 0px; padding: 10px;',
						tabs: tabsFichierVente
					},		 		        
		            { type: 'left', size: '100%', hidden:true, resizable: true, style: pstyleDetail},
		            { type: 'right', size: '50%', hidden:true, resizable: true, style: pstyleDetail},
		        ]
			},
		    layoutParam: {
		        name: 'layout_<?php echo $idPage;?>_param',
		        padding: 4,
		        panels: [
					{ type: 'main',size: '70%', hidden:false, resizable: true, style: pstyleDetail},		 		        
		            { type: 'left', size: '30%', hidden:false, resizable: true, style: pstyleDetail},
		        ]
			},
		    layoutFic: {
		        name: 'layout_<?php echo $idPage;?>_fic',
		        padding: 4,
		        panels: [
					{ type: 'main',size: '50%', hidden:false, resizable: true, style: pstyleDetail},		 		        
		            { type: 'right', size: '740px', hidden:false, resizable: true, style: pstyleDetail},
				],
				onRender : function (event) {
					event.onComplete = function () {
						console.log(event);
					}
				},
				
			},
		    layoutVenteTop: {
		        name: 'layout_<?php echo $idPage;?>_top',
		        padding: 2,
		        panels: [
		 		    { type: 'main', 
					    style: 'background-color: white; border: 1px solid silver; border-top: 0px; padding: 10px;',
					    tabs: {
					        active: 'tabTop2',
					        tabs: [{ id: 'tabTop2', caption: "Fichier de ventes" },{ id: 'tabTop0', caption: "Ventes par ISBN" },{ id: 'tabTop1', caption: "Ventes par auteur" }
					        	,{ id: 'tabTop3', caption: "Paramètres" }],
					        onClick: function (event) {
								// initTabs();
								// clearTabs();
						        if(event.target=="tabTop0"){
									initTabs();
									clearTabs();
						            if(w2ui['grid_<?php echo $idPage;?>_vente_isbn'])w2ui['grid_<?php echo $idPage;?>_vente_isbn'].destroy();
						            w2ui.layout_<?php echo $idPage;?>_top.content('main', $().w2grid(config.gridVenteISBN));
						        }else if(event.target=="tabTop1"){
									initTabs();
									clearTabs();
						            if(w2ui['grid_<?php echo $idPage;?>_vente_auteur'])w2ui['grid_<?php echo $idPage;?>_vente_auteur'].destroy();
						            w2ui.layout_<?php echo $idPage;?>_top.content('main', $().w2grid(config.gridVenteAuteur));
						        }else if(event.target=="tabTop2"){
									initTabs();
									clearTabs();
						            if(w2ui['layout_<?php echo $idPage;?>_fichier'])w2ui['layout_<?php echo $idPage;?>_fichier'].destroy();
						            if(w2ui['grid_ImportVenteData'])w2ui['grid_ImportVenteData'].destroy();
						            w2ui.layout_<?php echo $idPage;?>_top.content('main', $().w2layout(config.layoutVenteFichier));
						            w2ui.layout_<?php echo $idPage;?>_fichier.content('main', $().w2layout(config.gridImportVenteData));
						            getFichierImport();
						        }else if(event.target=="tabTop3"){
						            if(w2ui['layout_<?php echo $idPage;?>_param'])w2ui['layout_<?php echo $idPage;?>_param'].destroy();
									if(w2ui['grid_<?php echo $idPage;?>_devise'])w2ui['grid_<?php echo $idPage;?>_devise'].destroy();
									if(w2ui['grid_<?php echo $idPage;?>_param'])w2ui['grid_<?php echo $idPage;?>_param'].destroy();
									w2ui.layout_<?php echo $idPage;?>_top.content('main', $().w2layout(config.layoutParam));
									w2ui.layout_<?php echo $idPage;?>_param.content('main', $().w2grid(config.gridVenteDevise));
									w2ui.layout_<?php echo $idPage;?>_param.content('left', $().w2grid(config.gridDroitParam));
									
									//ajout tab paramètres en bas
									if (!w2ui.layout_<?php echo $idPage;?>_main_tabs.get('tab3'))
										w2ui.layout_<?php echo $idPage;?>_main_tabs.add({ id: 'tab3', text: 'Paramètres mails' });
									w2ui.layout_<?php echo $idPage;?>.content('main', '<div id="form" style="width: 100%;">');
									w2ui.layout_<?php echo $idPage;?>_main_tabs.hide('tab0','tab1','tab2');
									
									if (w2ui.form_<?php echo $idPage;?>_param)
										w2ui.form_<?php echo $idPage;?>_param.destroy();

									w2ui.layout_<?php echo $idPage;?>_fic.content('main', $('#form').w2form(config.formParam));
									
									
						        }
					        },
					        onClose: function (event) {
					            this.click('tabTop2');
					        }
					    }

			 		},
		            { type: 'right', size: '400px', hidden:true, resizable: true, style: pstyleDetail},
		        ]
		    },		    
		    layoutVenteFichier: {
		        name: 'layout_<?php echo $idPage;?>_fichier',
		        padding: 2,
		        panels: [
		            { type: 'left', size: '510px', resizable: true, style: pstyleDetail},
		            { type: 'main', size: '100%', resizable: true, style: pstyleDetail},
		        ]
		    },			    
		    gridVenteISBN: { 
		        name: 'grid_<?php echo $idPage;?>_vente_isbn', 
				header: 'Ventes par ISBN',		
		        show: { 
					header			: true,		
		            toolbar			: true,
					toolbarReload   	: true,
					toolbarColumns  	: true,
	            	toolbarSearch   	: true,
	            	toolbarAdd      	: true,
	            	toolbarDelete   	: false,
	            	toolbarSave		: false,
		            selectColumn		: true,
		            footer			: true,
		        },
		        multiSearch: true,
		        searches: [
				    { field: 'num', caption: 'ISBN', type: 'text' },
				    { field: 'titre', caption: 'Titre', type: 'text' },
				    { field: 'nom', caption: 'Nom auteur', type: 'text' },
		            { field: 'id_boutique', caption: 'Boutique', type: 'combo', options: { items: arrListes['boutique']} },
		            { field: 'date_vente', caption: 'Date de vente', type: 'date' },
		            { field: 'montant_euro', caption: 'Montant &euro;', type: 'float'},
		            { field: 'montant_livre', caption: 'Montant &pound;', type: 'float'},
		            { field: 'montant_dollar', caption: 'Montant $', type: 'float'},
		            { field: 'mt_r', caption: 'Mt. roy. &pound;', type: 'float'},
		            { field: 'mt_r_due', caption: 'Mt. roy. due &pound;', type: 'float'},
		        ],
		        columns: [         
		            { field: 'recid', caption: 'ID', size: '50px', hidden:true, sortable: true, resizable: true },
		            { field: 'num', caption: 'ISBN', size: '100px', sortable: true, resizable: true},
		            { field: 'titre_fr', caption: 'Titre FR', size: '180px', sortable: true, resizable: true},
		            { field: 'titre_en', caption: 'Titre EN', size: '180px', sortable: true, resizable: true},
		            { field: 'typeVente', caption: 'Type vente', size: '80px', sortable: true, resizable: true},		            
		            { field: 'type', caption: 'Type ISBN', size: '80px', sortable: true, resizable: true},		            
		            { field: 'auteurs', caption: 'Auteurs', size: '200px', sortable: true, resizable: true},
		            { field: 'mt_e_r', caption: 'Mt. roy. &pound;', size: '80px', sortable: true, resizable: true, render: 'money'},
		            { field: 'mt_rDue', caption: 'Mt. roy. due &pound;', size: '80px', sortable: true, resizable: true, render: 'money'},
		            { field: 'mt_rPaie', caption: 'Mt. roy. pay. &pound;', size: '80px', sortable: true, resizable: true, render: 'money'},
		            { field: 'boutiques', caption: 'Boutiques', size: '130px', sortable: true, resizable: true},
		            { field: 'date_first', caption: 'Première vente', size: '80px', sortable: true, resizable: true},
		            { field: 'date_last', caption: 'Dernière vente', size: '80px', sortable: true, resizable: true},
		            { field: 'nb_vente', caption: 'Nb vente', size: '100px', render: 'int', sortable: true, resizable: true},
		            { field: 'mt_l', caption: 'Mt. &pound;', size: '80px', sortable: true, resizable: true, render: function (record) {
						return '<div>&pound;' + record.mt_l + '</div>';
						}
					},
		        ],
		        toolbar: {
		            items: [
		                { id: 'export', type: 'button', caption: 'Exporter', icon: 'fa-file' }
		            ],
		            onClick: function (event) {
		                if (event.target == 'export') {
		                		open(urlP+'export?obj=venteISBN',"_blank")
		                }
		            }
		        },
		        records: rsVenteISBN,
		        onSelect: function (event) {
					event.onComplete = function () {
						var s = w2ui['grid_<?php echo $idPage;?>_vente_isbn'].getSelection();
			            getRapportFic(null,s,null)
					}
		        },	    
		        onAdd: function(event) {
			        openPopupAjoutVente();            
			    },
		        onSearch: function(event) {
		        		var grid = this;
		        		if(event.searchField=="multi"){
		            		event.onComplete = function () {
			            		$.get('<?php if(!$this->ajax) echo '../'; ?>cherche/vente',
							{"searchData":event.searchData, "bLivre":1},
			            		function(js){
			            			finsession(js);
			            			var ids = [];
			            			js.rs.forEach(function(d){
			            				rsVente.forEach(function(l, i){
				            				if(l.recid==d)ids.push(i);
			            				});
				            		});
		                        grid.last.searchIds = ids;
		                        grid.total      = grid.last.searchIds.length; 
		                        grid.buffered   = grid.total; 
		                        grid.refresh();
		                        w2alert(js.message);
			           		},"json");
		                }
		            }else{
			            	grid.localSearch();		            
		            }
		        },				    
		    },
		    gridVenteAuteur: { 
		        name: 'grid_<?php echo $idPage;?>_vente_auteur', 
				header: 'Ventes par auteur',		
		        show: { 
					header			: true,		
		            toolbar			: true,
					toolbarReload   	: true,
					toolbarColumns  	: true,
		            	toolbarSearch   	: true,
		            	toolbarAdd      	: true,
		            	toolbarDelete   	: false,
		            	toolbarSave		: false,
		            selectColumn		: true,
		            	footer			: true,
		        },
		        multiSearch: true,
		        searches: [
				    { field: 'titre', caption: 'Titre', type: 'text' },
				    { field: 'nom', caption: 'Nom auteur', type: 'text' },
		            { field: 'id_boutique', caption: 'Boutique', type: 'combo', options: { items: arrListes['boutique']} },
		            { field: 'num', caption: 'ISBN', type: 'text' },
		            { field: 'date_vente', caption: 'Date de vente', type: 'date' },
		            { field: 'montant_euro', caption: 'Montant &euro;', type: 'float', render: 'money'},
		            { field: 'montant_livre', caption: 'Montant &pound;', type: 'float', render: 'money'},
		            { field: 'montant_dollar', caption: 'Montant $', type: 'float', render: 'money'},
		            { field: 'mt_r', caption: 'Mt. roy. &pound;', type: 'float', render: 'money'},
		            { field: 'mt_r_due', caption: 'Mt. roy. due &pound;', type: 'float', render: 'money'},
		        ],
		        columns: [         
		            { field: 'recid', caption: 'ID', size: '50px', hidden:true, sortable: true, resizable: true },
		            { field: 'auteur', caption: 'Auteur', size: '200px', sortable: true, resizable: true},
		            { field: 'roles', caption: 'Roles', size: '160px', sortable: true, resizable: true},
		            { field: 'mt_rTot', caption: 'Mt. roy. &pound;', size: '80px', sortable: true, resizable: true},
		            { field: 'mt_rDue', caption: 'Mt. roy. due &pound;', size: '80px', sortable: true, resizable: true},
		            { field: 'mt_rPaie', caption: 'Mt. roy. pay. &pound;', size: '80px', sortable: true, resizable: true},
		            { field: 'boutiques', caption: 'Boutiques', size: '130px', sortable: true, resizable: true},
		            { field: 'livres', caption: 'Livres', size: '180px', sortable: true, resizable: true},
		            { field: 'isbns', caption: 'ISBNs', size: '100px', sortable: true, resizable: true},
		            { field: 'date_first', caption: 'Première vente', size: '80px', sortable: true, resizable: true},
		            { field: 'date_last', caption: 'Dernière vente', size: '80px', sortable: true, resizable: true},
		            { field: 'vAutnb_vente', caption: 'Nb vente aut.', size: '100px', render: 'int', sortable: true, resizable: true},
		            { field: 'vAutmt_l', caption: 'Mt. aut. &pound;', size: '80px', sortable: true, resizable: true},
		            { field: 'vCoornb_vente', caption: 'Nb vente coor.', size: '100px', render: 'int', sortable: true, resizable: true},
		            { field: 'vCoormt_l', caption: 'Mt. coor. &pound;', size: '80px', sortable: true, resizable: true},
		            { field: 'vDirnb_vente', caption: 'Nb vente dir.', size: '100px', render: 'int', sortable: true, resizable: true},
		            { field: 'vDirmt_l', caption: 'Mt. dir. &pound;', size: '80px', sortable: true, resizable: true},
		        ],
		        toolbar: {
		            items: [
		                { id: 'export', type: 'button', caption: 'Exporter', icon: 'fa-file' }
		            ],
		            onClick: function (event) {
		                if (event.target == 'export') {
		                		open(urlP+'export?obj=venteAuteur',"_blank")
		                }
		            }
		        },
		        records: rsVenteAuteur,
		        onSelect: function (event) {
					event.onComplete = function () {
						var s = w2ui['grid_<?php echo $idPage;?>_vente_auteur'].getSelection();
			            getRapportFic(null,null,s)
					}
		        },	    
		        onAdd: function(event) {
			        	openPopupAjoutVente();            
			    },
		        onSearch: function(event) {
		        		var grid = this;
		        		if(event.searchField=="multi"){
		            		event.onComplete = function () {
			            		$.get('<?php if(!$this->ajax) echo '../'; ?>cherche/vente',
							{"searchData":event.searchData, "bLivre":1},
			            		function(js){
			            			finsession(js);
			            			var ids = [];
			            			js.rs.forEach(function(d){
			            				rsVente.forEach(function(l, i){
				            				if(l.recid==d)ids.push(i);
			            				});
				            		});
		                        grid.last.searchIds = ids;
		                        grid.total      = grid.last.searchIds.length; 
		                        grid.buffered   = grid.total; 
		                        grid.refresh();
		                        w2alert(js.message);
			           		},"json");
		                }
		            }else{
			            	grid.localSearch();		            
		            }
		        },				    
		    },

			gridFichierImport: { 
                name: 'grid_<?php echo $idPage;?>_fichier_import', 
        		header: 'Fichiers importés',		
                show: { 
        			header			: true,		
                    toolbar			: true,
        			toolbarReload   : false,
        			toolbarColumns  : true,
                	toolbarSearch   : true,
                	toolbarAdd      : false,
                	toolbarDelete   : true,
                	toolbarSave		: false,
                	footer			: true,
                },
		        columns: [         
		            { field: 'recid', caption: 'ID', size: '50px', hidden:true, sortable: true, resizable: true },
		            { field: 'name', caption: 'Nom', size: '150px', sortable: true, resizable: true },
		            { field: 'size', caption: 'Taille', size: '56px', render: 'int', sortable: true, resizable: true },
		            { field: 'url', caption: 'Adresse', size: '150px', hidden:true, sortable: true, resizable: true },
		            { field: 'dateDeb', caption: 'Début', size: '80px', sortable: true, resizable: true },
		            { field: 'dateFin', caption: 'Fin', size: '80px', sortable: true, resizable: true },
		            { field: 'nbLigne', caption: 'Nb. ligne', size: '65px', render: 'int', sortable: true, resizable: true },
		            { field: 'nbVente', caption: 'Nb vente', size: '60px', render: 'int', sortable: true, resizable: true },
		            ],
                toolbar: {
                    items: [
		                { id: 'import', type: 'button', caption: 'Importer fichier de vente', icon: 'fa-cloud-upload' }
                    ],
                    onClick: function (event) {
		                if (event.target == 'import') {
		                	openPopupImportVente();
		                }
                    }
				},
		        onDelete: function(event) {            
					if(event.force){
			            	$.post(itemSelect.deleteUrl+"&type=vente&obj=import&dir=1",
							null,
			            		function(js){
		            				finsession(js);
			            			w2alert(js.message);
			           		},"json");
					}
			    },				
                onClick: function (event) {
                    itemSelect = this.get(event.recid);
					voirData(event.recid);
					getRapportFic(event.recid);
               }	    
            },	   		    
            gridImportVenteData: { 
                name: 'grid_ImportVenteData', 
        		header: 'Données importées',		
                show: { 
        			header			: true,		
                    toolbar			: true,
        			toolbarReload   : false,
        			toolbarColumns  : true,
					toolbarSearch   : true,
					toolbarAdd      : false,
					toolbarDelete   : false,
					toolbarSave		: false,
					footer			: true,
                },
                toolbar: {
                    items: [
                        { id: 'export', type: 'button', caption: 'Exporter', icon: 'fa-file' }
                    ],
                    onClick: function (event) {
                        if (event.target == 'export') {
                        		open(urlP+'export/datavente?idFic='+idFicImport,"_blank")
                        }
                    }
                },
                onClick: function (event) {
                    itemSelect = this.get(event.recid);
                }	    
            },	   
		    formVente: { 
		        name: 'form_<?php echo $idPage;?>',
		        fields: [
		            {name: 'date_vente', type: 'date', options:{format: 'yyyy-mm-dd',openOnFocus: true}, required: true,  html: {caption: 'Date de vente'} },
		            {required: true,  name: 'id_isbn', type: 'list', options: { items: arrListes['isbn'] }
		            		, html: { caption: 'ISBN', attr: 'size="20"' } 
		            		},
					{required: true, name: 'id_boutique', type: 'list', options: { items: arrListes['boutique'] }
		            		, html: { caption: 'Boutique', attr: 'size="20"' } 
		            		},
		            	{required: false,  name: 'prix_euro',  type: 'float', html: { caption: 'Prix &euro;' }},
		            	{required: false,  name: 'prix_livre',  type: 'float', html: { caption: 'Prix &pound;' }},
		            	{required: false,  name: 'prix_dollar',  type: 'float', html: { caption: 'Prix $' }},
		            {required: false,  name: 'id_licence', type: 'list', options: { items: arrListes['licence'] }
		            		, html: { caption: 'Licence', attr: 'size="30"' } 
		            		},
		            {required: true,  name: 'nombre', type: 'int', html: { caption: 'Nombre' } },
		            { name: 'montant_euro', type: 'float', html: { caption: 'Montant &euro;' } },
		            { name: 'montant_livre', type: 'float', html: { caption: 'Montant &pound;' } },
		            { name: 'montant_dollar', type: 'float', html: { caption: 'Montant $' } },
		            { name: 'avec_droit', type: 'checkbox', html: { caption: 'Avec Droit' } },
		            { name: 'prealable', type: 'checkbox', html: { caption: 'Préalable' } },
		            { name: 'acheteur', type: 'text', html: { caption: 'Acheteur' } },
		        ],
		        onChange: function (event) {
		           var r = this.record;
		           event.onComplete = function () {
			           /*calcul du prix
			           if(r.id_licence && r.id_licence.licence_unitaire && r.nombre){
			        	   		w2ui['form_<?php echo $idPage;?>'].record['montant_euro'] = r.id_licence.licence_unitaire * r.nombre; 
			        	   		w2ui['form_<?php echo $idPage;?>'].refresh();
			           }
			           */
			           if(r.prix_euro && r.nombre){
				        	   w2ui['form_<?php echo $idPage;?>'].record['montant_euro'] = r.prix_euro * r.nombre; 
				        	   w2ui['form_<?php echo $idPage;?>'].refresh();
			           }
			           if(r.prix_livre && r.nombre && !r.montant_livre){
			        	   		w2ui['form_<?php echo $idPage;?>'].record['montant_livre'] = r.prix_livre * r.nombre; 
			        	   		w2ui['form_<?php echo $idPage;?>'].refresh();
			           }
			           if(r.prix_dollar && r.nombre && !r.montant_dollar){
			        	   		w2ui['form_<?php echo $idPage;?>'].record['montant_dollar'] = r.prix_dollar * r.nombre; 
				           	w2ui['form_<?php echo $idPage;?>'].refresh();
			           }
		           }		           
		        },
		        actions: {
		            Reset: function () {
		                this.clear();
		                w2popup.close();
		            },
		            Save: function () {
		                var errors = this.validate();
		                if (errors.length > 0) return;
		                var data = this.record;
			            data.id_livre=data.id_isbn.id_livre;
			            data.id_isbn=data.id_isbn.id;
			            if(data.id_licence)data.id_licence=data.id_licence.id;			            
			            if(data.id_boutique)data.id_boutique=data.id_boutique.id;			            
		                data.obj = "vente";
			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/insert',
							data,
			            		function(js){
		            				finsession(js);
				                var g = w2ui['grid_<?php echo $idPage;?>'];
								g.add(js.rs);
								g.selectNone();
			            			w2alert(js.message);
			           		},"json");
		            }
		        }
		    },		    
		    gridVenteDetail: { 
		        name: 'grid_<?php echo $idPage;?>_detail',
		        header: "Détails des ventes",		
				show: {toolbar		: true,
	    				toolbarReload   : false,
	    				toolbarColumns  : false,
	                	toolbarSearch   : false,
	                	toolbarAdd      : true,
	                	toolbarDelete   : true,
	                	toolbarSave		: true,
	                	header			: false, 
	                	columnHeaders	: true},
		        columns: [      		  		           
		            { field: 'recid', caption: 'ID', size: '50px', hidden:true, sortable: true, resizable: true },
		            //{ field: 'devise', caption: 'Devise', size: '150px', sortable: true, resizable: true },
		            { field: 'livre', caption: 'Livre', size: '10%', sortable: true, resizable: true },
		            { field: 'num', caption: 'ISBN', size: '100px', sortable: true, resizable: true },
		            { field: 'type', caption: 'Type', size: '100px', sortable: true, resizable: true },		            
		            { field: 'date_parution', caption: 'Date parution', size: '80px', sortable: true, resizable: true },		            
		            { field: 'licence', caption: 'Licence', size: '100px', sortable: true, resizable: true 
		            		,editable: { type: 'list', items: arrListes['licence'], showAll: true },
		                render: function (record, index, col_index) {
		                    var html = this.getCellValue(index, col_index);
		                    return html.text ? html.text : html;
		                }},		                
		            { field: 'base_contrat', caption: 'Base contractuelle', size: '80px', sortable: true, resizable: true },
			        { field: 'date_contrat', caption: 'Signature contrat', size: '100px', sortable: true, resizable: true},
		            { field: 'date_vente', caption: 'Date de vente', size: '100px', sortable: true, resizable: true 
		            		,editable: { type: 'date'}},
		            { field: 'id_boutique', caption: 'Boutique', size: '80px', sortable: true, resizable: true 
	            			,editable: { type: 'select', items: arrListes['boutique'] }, 
			                render: function (record, index, col_index) {
			                    var html = '';
			                    for (var p in arrListes['boutique']) {
			                        if (arrListes['boutique'][p].id == this.getCellValue(index, col_index)) html = arrListes['boutique'][p].text;
			                    }
			                    return html;
			                }},
		            { field: 'prix_euro', caption: 'Prix &euro;', size: '80px', sortable: true, resizable: true 
				    		,editable:{type:'float'}},
				    	{ field: 'prix_livre', caption: 'Prix &pound;', size: '80px', sortable: true, resizable: true 
					    		,editable:{type:'float'}},
				    	{ field: 'prix_dollar', caption: 'Prix $', size: '80px', sortable: true, resizable: true 
				    		,editable:{type:'float'}},
		            { field: 'nombre', caption: 'Nombre', size: '80px', sortable: true, resizable: true 
				    		,editable:{type:'int'}},
		            { field: 'montant_euro', caption: 'Montant &euro;', size: '80px', sortable: true, resizable: true
		            		,editable:{type:'float'}},
		            { field: 'montant_livre', caption: 'Montant &pound;', size: '80px', sortable: true, resizable: true
			            	,editable:{type:'float'}},
			        { field: 'montant_dollar', caption: 'Montant $', size: '80px', sortable: true, resizable: true
			        		,editable:{type:'float'}},
		            { field: 'avec_droit', caption: 'Droit', size: '60px', sortable: true, resizable: true
		            		,editable:{type:'checkbox'}},
		            { field: 'prealable', caption: 'Préalable', size: '80px', sortable: true, resizable: true
		            		,editable:{type:'checkbox'}},
		            { field: 'acheteur', caption: 'Acheteur', size: '80px', sortable: true, resizable: true
		    		        ,editable:{type:'text'}},
		        ],
		        onSave: function(event) {
		            var changes = w2ui['grid_<?php echo $idPage;?>_detail'].getChanges();		            
		            changes.forEach(function(c, i){
			            c.obj = 'vente';
				        	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
			        			c,
			        			function(js){
			            			finsession(js);
			        				if(changes.length==i+1)w2alert(js.message);
			        			},"json");                        
		            });
		        },
		        onDelete: function(event) {            
					var p = {id:itemSelectVente.recid, obj:'vente'};
					if(event.force){
			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/delete',
							p,
			            		function(js){
		            				finsession(js);
					            getVenteData();
			            			w2alert(js.message);
			           		},"json");
					}
			    },
		        onClick: function (event) {
		            itemSelectVente = this.get(event.recid);
		        }	    
		    },			    	    		    
		    gridVenteRoyalties: { 
		        name: 'grid_<?php echo $idPage;?>_royalties', 
				header: "Détail des royalties",		
				show: {toolbar		: true,
	    				toolbarReload   : false,
	    				toolbarColumns  : false,
	                	toolbarSearch   : false,
	                	toolbarAdd      : false,
	                	toolbarDelete   : true,
	                	toolbarSave		: true,
	                	header			: false, 
	                	columnHeaders	: true},
		        columns: [      		  		           
		            { field: 'recid', caption: 'ID', size: '50px', hidden:true, sortable: true, resizable: true },
		            { field: 'id_vente', caption: 'id_vente', size: '50px', hidden:true, sortable: true, resizable: true},
		            { field: 'livre', caption: 'Livre', size: '10%', sortable: true, resizable: true },
		            { field: 'type_isbn', caption: 'Type', size: '80px', sortable: true, resizable: true },
		            { field: 'type_contrat', caption: 'Type de contrat', size: '100px', sortable: true, resizable: true},
		            { field: 'base_contrat', caption: 'Base contrat', size: '80px', sortable: true, resizable: true },
		            { field: 'annee', caption: 'Année', size: '80px', sortable: true, resizable: true },
		            { field: 'date_vente', caption: 'Date de vente', size: '80px', sortable: true, resizable: true },
		            { field: 'montant_vente', editable:{type:'float'}, caption: 'Vente &pound;', size: '80px', sortable: true, resizable: true},
		            { field: 'montant_euro', editable:{type:'float'}, caption: 'Montant &euro;', size: '80px', sortable: true, resizable: true},
		            { field: 'montant_livre', editable:{type:'float'}, caption: 'Montant &pound;', size: '80px', sortable: true, resizable: true},
		            { field: 'montant_dollar', editable:{type:'float'}, caption: 'Montant $', size: '80px', sortable: true, resizable: true},
		            { field: 'taxe_taux', editable:{type:'float'}, caption: 'Taxe taux', size: '80px', sortable: true, resizable: true},
		            { field: 'taxe_deduction', editable:{type:'float'}, caption: 'Taxe déduction', size: '100px', sortable: true, resizable: true},
		            { field: 'pourcentage', editable:{type:'float'}, caption: '%', size: '200px', sortable: true, resizable: true},
		            { field: 'date_edition', caption: 'Edition', size: '100px', sortable: true, resizable: true},
		            { field: 'date_paiement', caption: 'Paiement', size: '100px', sortable: true, resizable: true},
		            { field: 'date_encaissement', caption: 'Encaissement', size: '100px', sortable: true, resizable: true},
		        ],
		        onSave: function(event) {
		            var changes = w2ui['grid_<?php echo $idPage;?>_royalties'].getChanges();		            
		            changes.forEach(function(c, i){
			            c.obj = 'royalty';
			            if(c.date_paiement) c.date_paiement = w2utils.formatDate(c.date_paiement, 'yyyy-mm-dd');
			            if(c.date_encaissement) c.date_encaissement = w2utils.formatDate(c.date_encaissement, 'yyyy-mm-dd');			            
				        	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
			        			c,
			        			function(js){
			            			finsession(js);
			        				if(changes.length==i+1)w2alert(js.message);
			        			},"json");                        
		            });
		        },
		        onDelete: function(event) {            
					var p = {obj:'royalty'};
					if(event.force){
						var s = w2ui[event.target].getSelection();
						p.id = s[0];
						$.get('<?php if(!$this->ajax) echo '../'; ?>crud/delete',
							p,
			            		function(js){
			            			finsession(js);
			            			w2alert(js.message);
			           		},"json");
					}
			    },		    
		        onAdd: function(event) {
			        //	openPopupAjoutRoyalty();            
			    },
		    },	
		    gridVentePrix: { 
		        name: 'grid_<?php echo $idPage;?>_prix', 
				header: 'Prix pour le livre',		
				show: {toolbar		: true,
	    				toolbarReload   : false,
	    				toolbarColumns  : false,
	                	toolbarSearch   : false,
	                	toolbarAdd      : true,
	                	toolbarDelete   : true,
	                	toolbarSave		: true,
	                	header			: false, 
	                	columnHeaders	: true},
		        columns: [		  		           
		            { field: 'recid', caption: 'ID', size: '50px', hidden:true, sortable: true, resizable: true },
		            { field: 'id_isbn', caption: 'id_isbn', size: '50px', hidden:true, sortable: true, resizable: true},
		            { field: 'num', caption: 'ISBN', size: '120px', sortable: true, resizable: true},
		            { field: 'type_isbn', caption: "Type d'ISBN", size: '10%', sortable: true, resizable: true},
		            { field: 'type_prix', caption: 'Type de prix', size: '10%', sortable: true, resizable: true,editable: { type: 'list', items: arrListes['prix'], showAll: true },
		                render: function (record, index, col_index) {
		                    var html = this.getCellValue(index, col_index);
		                    return html.text ? html.text : html;
		                }},
		            { field: 'prix_euro', caption: 'Prix &euro;', size: '80px', sortable: true, resizable: true,editable:{type:'float'}},
		            { field: 'prix_livre', caption: 'Prix &pound;', size: '80px', sortable: true, resizable: true,editable:{type:'float'}},
		            { field: 'prix_dollar', caption: 'Prix $', size: '80px', sortable: true, resizable: true,editable:{type:'float'}},
		            { field: 'maj', caption: 'Date', size: '200px', sortable: true, resizable: true, editable: { type: 'date'}},
		        ],
		        onSave: function(event) {
		            var changes = w2ui['grid_<?php echo $idPage;?>_prix'].getChanges();		            
		            changes.forEach(function(c, i){
			            c.obj = 'prix';
				        	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
			        			c,
			        			function(js){
			            			finsession(js);
			        				if(changes.length==i+1)w2alert(js.message);
			        			},"json");                        
		            });
		        },
		        onDelete: function(event) {            
					var p = {obj:'prix'};
					if(event.force){
						var s = w2ui[event.target].getSelection();
						p.id = s[0];

						$.get('<?php if(!$this->ajax) echo '../'; ?>crud/delete',
							p,
			            		function(js){
		            				finsession(js);
					            getVenteData();
			            			w2alert(js.message);
			           		},"json");
					}
			    },		    
		        onAdd: function(event) {
			        	openPopupAjoutPrix();            
			    },
			},	
		    formPrix: { 
		        name: 'form_<?php echo $idPage;?>_prix',
		        fields: [
		            {name: 'maj', type: 'date', options:{format: 'yyyy-mm-dd',openOnFocus: true}, required: true,  html: {caption: 'Date du prix'} },
		            {required: true,  name: 'id_isbn', type: 'list', options: { items: rsIsbnLivre}
		            		, html: { caption: 'ISBN', attr: 'size="20"' } 
		            		},
		            { name: 'prix_euro', type: 'float', html: { caption: 'Prix &euro;' } },
		            { name: 'prix_livre', type: 'float', html: { caption: 'Prix &pound;' } },
		            { name: 'prix_dollar', type: 'float', html: { caption: 'Prix $' } },
		            {required: true, name: 'type', type: 'list', options: { items: arrListes['prix'] }
		            		, html: { caption: 'type', attr: 'size="20"' } 
		            		},
		        ],
		        actions: {
		            Reset: function () {
		                this.clear();
		                w2popup.close();
		            },
		            Save: function () {
		                var errors = this.validate();
		                if (errors.length > 0) return;
		                var data = this.record;
			            if(data.id_isbn){
				            data.id_isbn=data.id_isbn.id;
			            }			            
			            if(data.type)data.type=data.type.text;			            
			            data.pdf ? data.pdf=1 : data.pdf=0;			            
			            data.obj = "prix";
			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/insert',
							data,
			            		function(js){
			            			finsession(js);
			            			if(js.rs){
					                var g = w2ui['grid_<?php echo $idPage;?>_prix'];
									g.add(js.rs);
									g.selectNone();
			            			}
			            			w2alert(js.message);
			           		},"json");
		            }
		        }
		    },		    		    	    	    		    
		    gridVenteRapport: { 
		        name: 'grid_<?php echo $idPage;?>_rapport', 
				header: 'Rapport pour le livre',		
				show: {toolbar		: true,
	    				toolbarReload   : false,
	    				toolbarColumns  : false,
	                	toolbarSearch   : false,
	                	toolbarAdd      : false,
	                	toolbarDelete   : true,
	                	toolbarSave		: true,
	                	header			: false, 
	                	columnHeaders	: true},
		        columns: [		  		           
		            { field: 'recid', caption: 'ID', size: '50px', hidden:true, sortable: true, resizable: true },
		            { field: 'royIds', caption: 'royId', size: '50px', hidden:true, sortable: true, resizable: true },
		            { field: 'titre_fr', caption: "Titre FR", size: '10%', sortable: true, resizable: true},
		            { field: 'titre_en', caption: "Titre EN", size: '10%', sortable: true, resizable: true},
		            { field: 'base_contrat', caption: "Base contrat", size: '40px', sortable: true, resizable: true},
		            { field: 'periode', caption: "Periode", size: '170px', sortable: true, resizable: true},
		            { field: 'montant_livre', caption: "Montant Roy. &pound;", size: '120px', sortable: true, resizable: true},
		            { field: 'date_edition', caption: 'Edition', size: '80px', sortable: true, resizable: true},
		            { field: 'date_paiement', editable:{type:'date'}, caption: 'Paiement', size: '80px', sortable: true, resizable: true},
		            { field: 'date_encaissement', editable:{type:'date'}, caption: 'Encaissement', size: '80px', sortable: true, resizable: true},		            
		            { field: 'url', caption: 'URL', size: '30%', sortable: true, resizable: true},
		            ],
		        onDelete: function(event) {            
					var p = {obj:'rapport'};
					if(event.force){
						var s = w2ui[event.target].getSelection();
						p.id = s[0];
						$.get('<?php if(!$this->ajax) echo '../'; ?>crud/delete',
							p,
			            		function(js){
			            			finsession(js);
						        getVenteData();
			            			w2alert(js.message);
			           		},"json");
					}
			    },		
		        onSave: function(event) {
		            var changes = w2ui['grid_<?php echo $idPage;?>_rapport'].getChanges();
		            changes.forEach(function(c, i){
			            var r = w2ui[event.target].get(c.recid);
			            c.royIds = r["royIds"];		            
			            c.obj = 'royalty';
			            if(c.date_paiement) c.date_paiement = w2utils.formatDate(c.date_paiement, 'yyyy-mm-dd');
			            if(c.date_encaissement) c.date_encaissement = w2utils.formatDate(c.date_encaissement, 'yyyy-mm-dd');			            
				        	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
			        			c,
			        			function(js){
			            			finsession(js);
			        				if(changes.length==i+1)w2alert(js.message);
			        			},"json");                        
		            });
		        },
		        toolbar: {
		            items: [
		                { id: 'voirRapport', type: 'button', caption: "Voir le(s) édition(s)", icon: 'fa-file' }
		            ],
		            onClick: function (event) {
		                if (event.target == 'voirRapport') {
			                	var s = w2ui['grid_<?php echo $idPage;?>_rapport'].getSelection();
			                	if(s){
				                	s.forEach(function(r){
				                		var item = w2ui['grid_<?php echo $idPage;?>_rapport'].get(r);
				                		open(item["url"],"_blank");
				                	})
			                	}
		                }
		            }
		        },			        
			},		
			gridFicRapport: { 
		        name: 'grid_<?php echo $idPage;?>_ficRapport', 
				header: 'Rapport pour le fichier de vente',		
				show: {toolbar		: true,
	    				toolbarReload   : false,
	    				toolbarColumns  : false,
	                	toolbarSearch   : false,
	                	toolbarAdd      : false,
	                	toolbarDelete   : true,
	                	toolbarSave		: true,
	                	header			: false, 
	                	columnHeaders	: true},
		        columns: [		  		           
		            { field: 'recid', caption: 'ID', size: '50px', hidden:true, sortable: true, resizable: true },
		            { field: 'royIds', caption: 'royId', size: '50px', hidden:true, sortable: true, resizable: true },
		            { field: 'nom', caption: "Nom", size: '80px', sortable: true, resizable: true},
		            { field: 'prenom', caption: "Prénom", size: '80px', sortable: true, resizable: true},
		            { field: 'base_contrat', caption: "Base contrat", size: '40px', sortable: true, resizable: true},
		            { field: 'periode', caption: "Periode", size: '170px', sortable: true, resizable: true},
		            { field: 'montant_livre', caption: "Montant Roy. &pound;", size: '100px', sortable: true, resizable: true},
		            { field: 'date_edition', caption: 'Edition', size: '80px', sortable: true, resizable: true},
		            { field: 'date_envoi', caption: 'Envoi', size: '80px', sortable: true, resizable: true},
		            { field: 'date_paiement', editable:{type:'date'}, caption: 'Paiement', size: '80px', sortable: true, resizable: true},
		            { field: 'date_encaissement', editable:{type:'date'}, caption: 'Encaissement', size: '80px', sortable: true, resizable: true},		            
		            { field: 'url', caption: 'URL', hidden:true, size: '30%', sortable: true, resizable: true},
		            ],
		        onDelete: function(event) {            
					var p = {obj:'rapport'};
					if(event.force){
						var s = w2ui[event.target].getSelection();
						p.id = s[0];
						$.get('<?php if(!$this->ajax) echo '../'; ?>crud/delete',
							p,
							function(js){
								finsession(js);
								getVenteData();
								w2alert(js.message);
			           		},"json");
					}
			    },		
		        onSave: function(event) {
		            var changes = w2ui['grid_<?php echo $idPage;?>_rapport'].getChanges();
		            changes.forEach(function(c, i){
			            var r = w2ui[event.target].get(c.recid);
			            c.royIds = r["royIds"];		            
			            c.obj = 'royalty';
			            if(c.date_paiement) c.date_paiement = w2utils.formatDate(c.date_paiement, 'yyyy-mm-dd');
			            if(c.date_encaissement) c.date_encaissement = w2utils.formatDate(c.date_encaissement, 'yyyy-mm-dd');			            
				        	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
			        			c,
			        			function(js){
			            			finsession(js);
			        				if(changes.length==i+1)w2alert(js.message);
			        			},"json");                        
					});					
				},
		        onClick: function (event) {
					var item = this.get(event.recid);
					showPdf(item.url);
		        },	    
		        toolbar: {
		            items: [
		                { id: 'voirRapport', type: 'button', caption: "Télécharger", icon: 'fa-file' }
		                ,{ id: 'impRapport', type: 'button', caption: "Envoyer", icon: 'fa-envelope' }
		                ,{ id: 'groupRapport', type: 'button', caption: "Grouper", icon: 'fa-object-group' }
		                ,{ id: 'payerRapport', type: 'button', caption: "Payer", icon: 'fa-money' }
		                ,{ id: 'encaisserRapport', type: 'button', caption: "Encaisser", icon: 'fa-pencil' }
		            ],
		            onClick: function (event) {
						var s = w2ui['grid_<?php echo $idPage;?>_ficRapport'].getSelection();
						if(s.length){
							if (event.target == 'voirRapport') {
									s.forEach(function(r){
										var item = w2ui['grid_<?php echo $idPage;?>_ficRapport'].get(r);
										open(item["url"],"_blank");
									})
							}
							else if (event.target == 'impRapport'){
								w2ui['grid_<?php echo $idPage;?>_ficRapport'].lock('Veuillez patientez',true);
								var arraySel = [];
								s.forEach(function(r){
									var item = w2ui['grid_<?php echo $idPage;?>_ficRapport'].get(r);
									arraySel.push({
										recid : item["recid"],
										idAuteur: item["idAuteur"],
										url: item["url"]
									});
								})
								$.get('<?php if(!$this->ajax) echo '../'; ?>import/envoimail',
								{"data":arraySel},
									function(js){
										var strVar="";
										strVar += "<div id=\"grid\" style=\"width: 100%; height: 350px;\"><\/div>";
										strVar += "";
										strVar += "<script type=\"text\/javascript\">";
										strVar += "$(function () {";
										strVar += "if(w2ui['grid']) w2ui['grid'].destroy();";
										strVar += "    $('#grid').w2grid({ ";
										strVar += "        name: 'grid', ";
										strVar += "        columns: [                ";
										strVar += "            { field: 'recid', caption: 'ID', size: '50px' },";
										strVar += "            { field: 'nom', caption: 'Nom', size: '30%' },";
										strVar += "            { field: 'prenom', caption: 'Prénom', size: '30%' },";
										strVar += "            { field: 'etat', caption: 'Etat', size: '70%' }";
										strVar += "        ],";
										strVar += "        records: "+JSON.stringify(js);
										strVar += "    });    ";
										strVar += "});";
										strVar += "<\/script>";

										w2popup.open({ 
											title: "Résumé des mails envoyés",
											body: strVar
										});
										w2ui['grid_<?php echo $idPage;?>_ficRapport'].unlock();
										getRapportFic(w2ui['grid_<?php echo $idPage;?>_fichier_import'].getSelection()[0]);
								},"json");
							}
							else if (event.target=="groupRapport"){
								var rapport = "";
								for (var i = 0; i < s.length; i++) {
									var item = w2ui['grid_<?php echo $idPage;?>_ficRapport'].get(s[i]);
									rapport += item["recid"]+".";
								}
								rapport = rapport.substr(0,rapport.length-1);
								//TODO: Vérifier pour le php if(!$this->ajax) echo '../';
								var urlGroupe =  window.location.href + "../../../import/grouperpdf?data=" + rapport;
								

								var mapForm = document.createElement("form");
								mapForm.target = "Map";
								mapForm.method = "POST"; // or "post" if appropriate
								mapForm.action = window.location.href + "../../../import/grouperpdf";

								var mapInput = document.createElement("input");
								mapInput.type = "text";
								mapInput.name = "data";
								mapInput.value = rapport;
								mapForm.appendChild(mapInput);

								document.body.appendChild(mapForm);

								map = window.open("", "Map");

								if (map) {
									mapForm.submit();
								} else {
									alert('Veuillez autoriser les popups sur cette page.');
								}
							}
							else if(event.target =='payerRapport'){
								// if(s){
								// 	setPaiement(s);
								// }

								//TODO: vérifier avec samuel cette modification 
								// en bas c'est la mienne , en haut celle de samuel
								var strVar =  '   <div class="w2ui-field" >  '  + 
									'       <label>Date de paiement :</label>  '  + 
									'       <div> <input type="date" id="dateP"> </div>  '  + 
									'   </div>  '  + 
									'   <script>  '  + 
									"     $('input[type=date]').w2field('date',{ format: 'yyyy-mm-dd' });  "  + 
									'  <\/script>    ' ;

								w2popup.open({ 
											title: "Veuillez choisir la date de paiement pour la sélection",
											body: strVar,
											buttons: '<button class="w2ui-btn" onclick="validerPaiement()">Valider</button>'
								});
							}
							else if (event.target == "encaisserRapport"){
								
								var strVar =  '   <div class="w2ui-field" >  '  + 
									"       <label>Date d'encaissement :</label>  "  + 
									'       <div> <input type="date" id="dateE" > </div>  '  + 
									'   </div>  '  + 
									'   <script>  '  + 
									"     $('input[type=date]').w2field('date',{ format: 'yyyy-mm-dd' });  "  + 
									'  <\/script>    ' ;

								w2popup.open({ 
											title: "Veuillez choisir la date d'encaissement pour la sélection",
											body: strVar,
											buttons: '<button class="w2ui-btn" onclick="validerEncaissement()">Valider</button>'
								});
								
							}
						}	
					}
		        },
			        
			},					
			gridVenteDevise: { 
		        name: 'grid_<?php echo $idPage;?>_devise', 
				header: 'Taxes et taux de conversion',		
				show: {toolbar		: true,
	    				toolbarReload   : false,
	    				toolbarColumns  : false,
	                	toolbarSearch   : false,
	                	toolbarAdd      : true,
	                	toolbarDelete   : true,
	                	toolbarSave		: true,
	                	header			: true, 
	                	footer			: true, 
	                	columnHeaders	: true},
		        columns: [		  		           
		            { field: 'recid', caption: 'ID', size: '50px', hidden:true, sortable: true, resizable: true },
		            { field: 'base_contrat', caption: 'Base contrat', size: '80px', sortable: true, resizable: true},
		            { field: 'annee', caption: 'Année', size: '80px', sortable: true, resizable: true},
		            { field: 'date_taux', caption: 'Deb. période',editable: { type: 'date'}, size: '80px', sortable: true, resizable: true},
		            { field: 'date_taux_fin', caption: 'Fin période',editable: { type: 'date'}, size: '80px', sortable: true, resizable: true},
					{ field: 'taxe_taux', caption: 'Taxe taux',editable: { type: 'float'}, size: '80px', sortable: true, resizable: true},
					{ field: 'taxe_deduction', caption: 'Taxe déduction',editable: { type: 'float'}, size: '110px', sortable: true, resizable: true},
		            { field: 'taux_livre_dollar', caption: '&pound; -> $',editable: { type: 'float'}, size: '80px', sortable: true, resizable: true},
		            { field: 'taux_livre_euro', caption: '&pound; -> &euro;',editable: { type: 'float'}, size: '80px', sortable: true, resizable: true},
		            { field: 'taux_euro_livre', caption: '&euro; -> &pound;',editable: { type: 'float'}, size: '80px', sortable: true, resizable: true},
		            { field: 'taux_dollar_livre', caption: '$ -> &pound;',editable: { type: 'float'}, size: '80px', sortable: true, resizable: true},
		            { field: 'taux_euro_dollar', caption: '&euro; -> $',editable: { type: 'float'}, size: '80px', sortable: true, resizable: true},
		            { field: 'taux_dollar_euro', caption: '$ -> &euro;',editable: { type: 'float'}, size: '80px', sortable: true, resizable: true},
		        ],
		        records:rsDev,
		        onDelete: function(event) {            
					var p = {obj:'devise'};
					if(event.force){
						var s = w2ui[event.target].getSelection();
						p.id = s[0];
						$.get('<?php if(!$this->ajax) echo '../'; ?>crud/delete',
							p,
			            		function(js){
			            			finsession(js);
			            			w2alert(js.message);
			           		},"json");
					}
			    },		
	            onAdd: function(event) {
		        		openPopupAjoutDevise();
			    },
		        onSave: function(event) {
		            var changes = w2ui['grid_<?php echo $idPage;?>_devise'].getChanges();
		            changes.forEach(function(c, i){
			            c.obj = 'devise';
			            if(c.date_taux) c.date_taux = w2utils.formatDate(c.date_taux, 'yyyy-mm-dd');
			            if(c.date_taux_fin) c.date_taux_fin = w2utils.formatDate(c.date_taux_fin, 'yyyy-mm-dd');
				        	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
			        			c,
			        			function(js){
			            			finsession(js);
			        				if(changes.length==i+1)w2alert(js.message);
			        			},"json");                        
		            });
		        },
			        
			},				
			formDevise: { 
		        name: 'form_<?php echo $idPage;?>_devise',
		        fields: [
				    { name: 'base_contrat', type: 'list', required: false, html: { caption: 'Base contrat'}
		            		,options: { items: arrListes['contratBase']}} , 
				    {required: true,  name: 'annee', type: 'int', options:{min: '2000',autoFormat:false}, required: true,  html: {caption: 'Année'} },
		            //{required: true,  name: 'date_taux', type: 'date', options:{format: 'yyyy-mm-dd',openOnFocus: true}, required: true,  html: {caption: 'Date du prix'} },
		            //{required: true,  name: 'date_taux_fin', type: 'date', options:{format: 'yyyy-mm-dd',openOnFocus: true}, required: true,  html: {caption: 'Date du prix'} },
					
		            { name: 'taxe_taux', type: 'float', html: { caption: 'Taux des taxes' } },
		            { name: 'taxe_deduction', type: 'float', html: { caption: 'Taux de déduction' } },
		            { name: 'taux_livre_dollar', type: 'float', html: { caption: '&pound; -> $' } },
		            { name: 'taux_livre_euro', type: 'float', html: { caption: '&pound; -> &euro;' } },
		            { name: 'taux_euro_livre', type: 'float', html: { caption: '&euro; -> &pound;' } },
		            { name: 'taux_euro_dollar', type: 'float', html: { caption: '&euro; -> $' } },
		            { name: 'taux_dollar_livre', type: 'float', html: { caption: '$ -> &pound;' } },
		            { name: 'taux_dollar_euro', type: 'float', html: { caption: '$ -> &euro;' } },
	            ],
		        actions: {
		            Reset: function () {
		                this.clear();
		                w2popup.close();
		            },
		            Save: function () {
		                var errors = this.validate();
		                if (errors.length > 0) return;
		                var data = this.record;
			            data.obj = "devise";
			            if(data.base_contrat)data.base_contrat=data.base_contrat.text;			            
			            if(data.date_taux) data.date_taux = w2utils.formatDate(data.date_taux, 'yyyy-mm-dd');
			            if(data.date_taux_fin) data.date_taux_fin = w2utils.formatDate(data.date_taux_fin, 'yyyy-mm-dd');
			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/insert',
							data,
			            		function(js){
			            			finsession(js);
			            			if(js.rs){
					                var g = w2ui['grid_<?php echo $idPage;?>_devise'];
									g.add(js.rs);
									g.selectNone();
			            			}
			            			w2alert(js.message);
			           		},"json");
		            }
		        }
		    },	
			gridDroitParam: { 
                name: 'grid_<?php echo $idPage;?>_param', 
        		header: 'Paramètres des droits',		
                show: { 
        			header			: true,		
                    toolbar			: true,
        			toolbarReload   : false,
        			toolbarColumns  : false,
                	toolbarSearch   : false,
                	toolbarAdd      : false,
                	toolbarDelete   : false,
                	toolbarSave		: true,
                	footer			: true,
				},
				records: rsDroitParam,
		        columns: [         
		            { field: 'recid', caption: 'ID', size: '50px', hidden:true, sortable: true, resizable: true },
		            { field: 'nom', caption: 'Nom du contrat', size: '150px', sortable: true, resizable: true },
		            { field: 'base_contrat', caption: 'Base contrat', size: '56px', sortable: true, resizable: true },
					{ field: 'moisDeb', caption: 'Mois début exercice', size: '150px', sortable: true, resizable: true, 
							editable: { type: 'list', items: arrListes['mois'], showAll: true },
						render: function (record, index, col_index) {
							var html = this.getCellValue(index, col_index);
							return html.text ? html.text : html;
						}
					},		            

					//{ field: 'dateDeb', caption: 'Date début exercice', size: '150px', editable: { type: 'text' }, sortable: true, resizable: true },
		            //{ field: 'dateFin', caption: 'Date fin exercice', size: '150px', editable: { type: 'text' }, sortable: true, resizable: true },
		            ],
				onSave: function(event) {
			        saveParam(event);            
			    },
            },	   			    

		};
	
	//initialisation
	initTabs();	
	initPdf();
	//charge les données
	getFichierImport();


}

function initTabs(){
    // initialisation
	if(!w2ui.layout_<?php echo $idPage;?>){
		$('#<?php echo $idPage;?>').w2layout(config.layoutVente);	
		w2ui.layout_<?php echo $idPage;?>.content('top', $().w2layout(config.layoutVenteTop));
		w2ui.layout_<?php echo $idPage;?>.content('main', $().w2layout(config.layoutFic));				
		w2ui.layout_<?php echo $idPage;?>_fic.content('main', $().w2grid(config.gridFicRapport));
		w2ui.layout_<?php echo $idPage;?>_top.content('main', $().w2layout(config.layoutVenteFichier));
	}

	if (w2ui.layout_<?php echo $idPage;?>_main_tabs.get('tab0').hidden){
		w2ui.layout_<?php echo $idPage;?>_main_tabs.show('tab0','tab1','tab2');
		w2ui.layout_<?php echo $idPage;?>_main_tabs.remove('tab3');
	}

}

function clearTabs(){

    if(w2ui['layout_<?php echo $idPage;?>_fic'])w2ui['layout_<?php echo $idPage;?>_fic'].destroy();
	w2ui.layout_<?php echo $idPage;?>.content('main', $().w2layout(config.layoutFic));
	if(w2ui['grid_<?php echo $idPage;?>_ficRapport'])w2ui['grid_<?php echo $idPage;?>_ficRapport'].destroy();				
	w2ui.layout_<?php echo $idPage;?>_fic.content('main', $().w2grid(config.gridFicRapport));
	initPdf();
	
}


function getVenteData(ids, table){
    if(!ids.length) return;   
    //récupère le infos liées
    if(w2ui['grid_<?php echo $idPage;?>_detail']){
		$.get('<?php if(!$this->ajax) echo '../'; ?>crud/ventedata',
			{'ids':ids, 'table':table, 'obj':'vente'},
	    		function(js){
    				finsession(js);
					var g = w2ui['grid_<?php echo $idPage;?>_detail'];
					g.clear();		            		
	    			if(js.rs.length){
	        			//mise à jour de la grille 			        
						g.add(js.rs);
					}else{
            			w2alert("Pas de royalty.");		    			
	    			}
	    },"json");
    }
    if(w2ui['grid_<?php echo $idPage;?>_royalties']){
		$.get('<?php if(!$this->ajax) echo '../'; ?>crud/ventedata',
			{'ids':ids, 'table':table, 'obj':'royalty'},
	    		function(js){
    				finsession(js);
					g = w2ui['grid_<?php echo $idPage;?>_royalties'];
					g.clear();		            		
	    			if(js.rs.length){
	        			//mise à jour de la grille 			        
			            g.add(js.rs);
	    			}else{
            			w2alert("Pas de royalty.");		    			
	    			}
	    },"json");           		           
    }
}




function openPopupImportVente () {

    w2popup.open({
        title: 'Importation des fichiers de vente',
        body: '<iframe height="100%" width="100%" scrolling="no" src="<?php if(!$this->ajax) echo '../'; ?>import/droit?obj=import&id=0"></iframe>',
        width     : 1080,
        height    : 740,
        overflow  : 'hidden',
        color     : '#333',
        speed     : '0.3',
        opacity   : '0.8',
        modal     : true,
        showClose : true,
        showMax   : false,
    });
}

function openPopupAjoutVente() {
    w2popup.open({
        title   : 'Ajouter une vente',
        width   : 400,
        height  : 550,
        showMax : true,
        body    : '<div id="main" style="position: absolute; left: 5px; top: 5px; right: 5px; bottom: 5px;"></div>',
        onOpen  : function (event) {
            event.onComplete = function () {
            	 	if(w2ui['form_<?php echo $idPage;?>'])w2ui['form_<?php echo $idPage;?>'].destroy();
                $('#w2ui-popup #main').w2form(config.formVente)
                w2ui['form_<?php echo $idPage;?>'].clear();
            };
        },
        onToggle: function (event) { 
            event.onComplete = function () {
                w2ui.layout.resize();
            }
        }
    });
}
function openPopupAjoutPrix() {
    w2popup.open({
        title   : 'Ajouter un prix',
        width   : 400,
        height  : 500,
        showMax : true,
        body    : '<div id="main" style="position: absolute; left: 5px; top: 5px; right: 5px; bottom: 5px;"></div>',
        onOpen  : function (event) {
            event.onComplete = function () {
            	 	if(w2ui['form_<?php echo $idPage;?>_prix'])w2ui['form_<?php echo $idPage;?>_prix'].destroy();
    		        rsIsbnLivre = arrListes['isbn'].filter(function(p){return p.id_livre==itemSelectAuteur.recid});
    		        config.formPrix.fields[1].options.items = rsIsbnLivre;
                $('#w2ui-popup #main').w2form(config.formPrix)
                w2ui['form_<?php echo $idPage;?>_prix'].refresh();
                w2ui['form_<?php echo $idPage;?>_prix'].clear();
            };
        },
        onToggle: function (event) { 
            event.onComplete = function () {
                w2ui.layout.resize();
            }
        }
    });
}
function openPopupAjoutDevise() {
    w2popup.open({
        title   : 'Ajouter une devise',
        width   : 400,
        height  : 550,
        showMax : true,
        body    : '<div id="main" style="position: absolute; left: 5px; top: 5px; right: 5px; bottom: 5px;"></div>',
        onOpen  : function (event) {
            event.onComplete = function () {
            	 	if(w2ui['form_<?php echo $idPage;?>_devise'])w2ui['form_<?php echo $idPage;?>_devise'].destroy();
                $('#w2ui-popup #main').w2form(config.formDevise)
                w2ui['form_<?php echo $idPage;?>_devise'].clear();
            };
        },
        onToggle: function (event) { 
            event.onComplete = function () {
                w2ui.layout.resize();
            }
        }
    });
}
function voirData(id){
	console.log("voirData : "+id);
	var e = window.event;
	idFicImport = id;
	$.get(urlP+'import/getdataficvente',
			{idFic:id},
        		function(js){
				//ajoute la définition des colonnes
				config.gridImportVenteData.columns=js.col;
				//met en forme les lignes suivant les problèmes
				var s = 'color:#3322b1;';
				js.prob.data_sans_basecontrat.forEach(function(p) {
					var arrf = js.rs.filter(function(e) {
						return e.col1 == p.num;
					  });
					arrf.forEach(function(f){
						if(f.w2ui)f.w2ui.style += s;
						else f.w2ui = {'style':s};
						var c = "pas de base contrat pour la proposition";
						if(f.commentaire)f.commentaire += ", "+c;
						else f.commentaire = c;	
					});  
				})				
				var s = 'background-color:#34bf31;color:';
				js.prob.data_sans_vente.forEach(function(p) {
					var f = js.rs.find(function(e) {
						return e.recid == p.recid;
					  });
					var sc = "black;";
					if(f.col4=='0,00' && f.col5=='0,00') sc = "white;";
					if(!f.col4 && !f.col5) sc = "white;";
					if(f.w2ui)f.w2ui.style += s+sc;
					else f.w2ui = {'style':s+sc};
					var c = "pas de vente associée";						
					if(f.commentaire)f.commentaire += ", "+c;
					else f.commentaire = c;	
				})				
				var s = 'background-color:#dc0d20;';
				js.prob.commentaires.forEach(function(p) {
					var f = js.rs.find(function(e) {
						return e.recid == p.recid;
					  });
					if(f.w2ui)f.w2ui.style += s;
					else f.w2ui = {'style':s};
				})
				var s = 'background-color:#dc800d;';
				js.prob.data_sans_contrat.forEach(function(p) {
					var arrf = js.rs.filter(function(e) {
						return e.col1 == p.num;
					  });
					arrf.forEach(function(f){
						if(f.w2ui)f.w2ui.style += s;
						else f.w2ui = {'style':s};
						var c = "pas de contrat pour "+p.prenom+" "+p.nom+" "+p.role;
						if(f.commentaire)f.commentaire += ", "+c;
						else f.commentaire = c;	
					});  
				})
				config.gridImportVenteData.records=js.rs;
				if(w2ui.grid_ImportVenteData)
					w2ui.grid_ImportVenteData.destroy();        
				w2ui.layout_<?php echo $idPage;?>_fichier.content('main', $().w2grid(config.gridImportVenteData));				
       		},'json');		
}
function getFichierImport(){
    $.ajax({
        // Uncomment the following to send cross-domain cookies:
        //xhrFields: {withCredentials: true},
		url: urlP+'/import/upload/',
		data:{'type':'vente','obj':'import','dir':'droit'},
        dataType: 'json',
    }).done(function (result) {
    	rsFichierImport = result.files;
	    config.gridFichierImport.records=rsFichierImport;
	    if(w2ui.grid_Droit_fichier_import)
	    		w2ui.grid_Droit_fichier_import.destroy();        
	    w2ui.layout_<?php echo $idPage;?>_fichier.content('left', $().w2grid(config.gridFichierImport));
    	
    });
}
function finProcessImport(idFic){
	w2popup.close();	
	getFichierImport();
	voirData(idFic);
	getRapportFic(idFic);
	getVenteAuteurISBN();
}
function getRapportFic(idFic,idsISBN,idsAuteur){
	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/rapportdata',
		{'idFichier':idFic,'idsISBN':idsISBN,'idsAuteur':idsAuteur},
			function(js){
				finsession(js);
				g = w2ui['grid_<?php echo $idPage;?>_ficRapport'];
				g.clear();		            		
				if(js.rs.length){
					g.add(js.rs);
				}
	},"json");           		           		
}
function getVenteAuteurISBN(){
	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/rapportdata',
		{'getDatas':1},
			function(js){
				finsession(js);
				rsVenteISBN = js.rs.isbn;				
				config.gridVenteISBN.records=rsVenteISBN
				if(w2ui['grid_<?php echo $idPage;?>_vente_isbn']){
					w2ui.grid_<?php echo $idPage;?>_vente_isbn.destroy();        
				};
				rsVenteAuteur = js.rs.auteur;
				config.gridVenteAuteur.records=rsVenteAuteur;
				if(w2ui['grid_<?php echo $idPage;?>_vente_auteur']){
					w2ui.grid_<?php echo $idPage;?>_vente_auteur.destroy();        
				}
	},"json");           		           		
}
function saveParam(event){

	var changes = w2ui['grid_<?php echo $idPage;?>_param'].getChanges();

	changes.forEach(function(c, i){
		var item = w2ui[event.target].get(c.recid);
		c = {"obj":obj,"recid":c.recid,"id_contrat":item.id_contrat};
		if(c.moisDeb){
			c.nom='moisDeb';
			c.val=c.moisDeb.text;
		}
		$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
			c,
			function(js){
				finsession(js);
				setListe(js.rs[0],typeP);
				if(changes.length==i+1)w2alert(js.message);
			},"json");                        
	});	
}

function initPdf(){
	var urlLoad = '../js/pdfjs/web/viewer.html';
	w2ui.layout_<?php echo $idPage;?>_fic.load('right', urlLoad, null, function (event) {
		console.log('pdf chargé :'+urlLoad);
	});	
}

function showPdf(url){
	//url = "../../../../data/editions/Barthn©s-Labrousse.Ma..livre.3012-3013.2018-05-31.2018-06-30.pdf";
	var urlLoad = 'http://localhost/gestedit/admin/js/pdfjs/web/viewer.html?file='+encodeURIComponent(url);
	PDFViewerApplication.open(url);
}
function setPaiement(idsRapport){
	$.get('<?php if(!$this->ajax) echo '../'; ?>calculer/paiement',
		{'type':'rapport','idsRapport':idsRapport},
			function(js){
				finsession(js);
				g = w2ui['grid_<?php echo $idPage;?>_ficRapport'];
				g.clear();		            		
				if(js.rs.length){
					g.add(js.rs);
				}
	},"json");           		           		
}

function validerPaiement (){
	var date = document.getElementById("dateP").value;
	if (date){
		var s = w2ui['grid_<?php echo $idPage;?>_ficRapport'].getSelection();
		var arraySel = [];
		s.forEach(function(r){
			var item = w2ui['grid_<?php echo $idPage;?>_ficRapport'].get(r);
			arraySel.push({
				recid : item["recid"]
			});
		})
		console.log("arraySel: "+JSON.stringify(arraySel));
		$.get('<?php if(!$this->ajax) echo '../'; ?>import/paiement',
								{"data":arraySel,"date":date},
									function(js){
										w2alert(js);
										w2ui['grid_<?php echo $idPage;?>_ficRapport'].unlock();
										getRapportFic(w2ui['grid_<?php echo $idPage;?>_fichier_import'].getSelection()[0]);
								},"json");
		w2popup.close();
	}
	else{
		w2alert("Veuillez sélectionner une date avant de valider")
	}
}

function validerEncaissement (){
	var date = document.getElementById("dateE").value;
	if (date){
		var s = w2ui['grid_<?php echo $idPage;?>_ficRapport'].getSelection();
		var arraySel = [];
		s.forEach(function(r){
			var item = w2ui['grid_<?php echo $idPage;?>_ficRapport'].get(r);
			arraySel.push({
				recid : item["recid"]
			});
		})
		console.log("arraySel: "+JSON.stringify(arraySel));
		$.get('<?php if(!$this->ajax) echo '../'; ?>import/encaissement',
								{"data":arraySel,"date":date},
									function(js){
										w2alert(js);
										w2ui['grid_<?php echo $idPage;?>_ficRapport'].unlock();
										getRapportFic(w2ui['grid_<?php echo $idPage;?>_fichier_import'].getSelection()[0]);
								},"json");
		w2popup.close();
	}
	else{
		w2alert("Veuillez sélectionner une date avant de valider")
	}
}


</script>

<?php 
if(!$this->ajax){
	echo '</body>
</html>';
}else{
	echo '<script type="text/javascript">
			$(function () {initDroit(); });                       		
		</script>		
		';	
}
?>