<?php 
if(!$this->ajax){
	echo '<!DOCTYPE html>
<html>
	<head>
		<title>ISTE - Editions</title>
		<link rel="stylesheet" type="text/css" href="../css/gestedit.css" />
		<link rel="stylesheet" type="text/css" href="../css/w2ui.css" />
		<link rel="stylesheet" type="text/css" href="../fonts/font-awesome/font-awesome.css" />
		<script type="text/javascript">
			var urlP = "../";
			var uti = '.$this->uti.';
			var fctInit;			
		</script>		
		<script type="text/javascript" src="../js/jquery.min.js"></script>
		<script type="text/javascript" src="../js/w2ui.js"></script>
		<script type="text/javascript" src="../js/global.js"></script>
		<script type="text/javascript" src="../js/data.js"></script>
		<script type="text/javascript" src="../js/log.js"></script>
		<script type="text/javascript">
			$(function () {
				initAll(initEdition); 
	  			if(uti)
					utiIsConnect();
	  			else
		    	  		diagLogin.showModal();				
			});                       		
		</script>		
		</head>
<body>
';
}
$idPage = "Edition";
?>

<div id="<?php echo $idPage;?>" style="width: 100%; height: 1000px;">
    <div class="w2ui-page page-0">
        <iframe height="100%" width="100%" scrolling="yes" src="<?php if(!$this->ajax) echo '../'; ?>import/vente?obj=import&id=0"></iframe>
    </div>    
    <div class="w2ui-page page-1">
        <div class="w2ui-field">
            <label>First Name:</label>
            <div>
                <input name="first_name" type="text" maxlength="100" size="60"/>
            </div>
        </div>
        <div class="w2ui-field">
            <label>Last Name:</label>
            <div>
                <input name="last_name" type="text" maxlength="100" size="60"/>
            </div>
        </div>
        <div class="w2ui-field">
            <label>Comments:</label>
            <div>
                <textarea name="comments" type="text" style="width: 100%; height: 80px; resize: none"></textarea>
            </div>
        </div>
    </div>
    <div class="w2ui-page page-2">
        <div class="w2ui-field">
            <label>Address:</label>
            <div>
                <input name="address1" type="text" maxlength="100" style="width: 100%"/>
            </div>
        </div>
        <div class="w2ui-field">
            <label>Line 2:</label>
            <div>
                <input name="address2" type="text" maxlength="100" style="width: 100%"/>
            </div>
        </div>
        <div class="w2ui-field">
            <label>City:</label>
            <div>
                <input name="city" type="text" maxlength="50" size="25"/>
            </div>
        </div>
        <div class="w2ui-field">
            <label>State:</label>
            <div>
                <input name="state" type="text" maxlength="2" size="2"/>
            </div>
        </div>
        <div class="w2ui-field">
            <label>Zip:</label>
            <div>
                <input name="zip" type="text" maxlength="10" size="10"/>
            </div>
        </div>
    </div>
    <div class="w2ui-page page-3">
        <div class="w2ui-field">
            <label>Short Bio:</label>
            <div>
                <textarea name="short_bio" type="text" style="width: 100%; height: 80px; resize: none"></textarea>
            </div>
        </div>
        <div class="w2ui-field">
            <label>Talk Name:</label>
            <div>
                <input name="talk_name" type="text" maxlength="100" style="width: 100%"/>
            </div>
        </div>
        <div class="w2ui-field">
            <label>Talk Description:</label>
            <div>
                <textarea name="description" type="text" style="width: 100%; height: 80px; resize: none"></textarea>
            </div>
        </div>
    </div>

    <div class="w2ui-buttons">
        <button class="w2ui-btn" name="reset">Reset</button>
        <button class="w2ui-btn" name="save">Save</button>
    </div>
</div>


<script type="text/javascript">
// var rsVente = <?php echo $this->json; ?>;
// var rsDev = <?php echo $this->rsDev; ?>;


//widget configuration
var pstyle = 'border: 1px solid #dfdfdf; padding: 5px;';
var pstyleDetail = 'background-color: #F0F0C1; border: 1px solid #dfdfdf; padding: 5px;';
var config;
var idPLU, idPCU, itemSelectAuteur, itemSelectVente, rsIsbnLivre, rsIsbnPrix;
function initEdition() {

	config = {
        form : { 
            name   : 'formEditions',
            header : 'Gestion des éditions',
            url    : 'server/post',
            fields : [
                { field: 'first_name', type: 'text', required: true },
                { field: 'last_name',  type: 'text', required: true },
                { field: 'comments',   type: 'text'},
                { field: 'address1', type: 'text', required: true },
                { field: 'address2', type: 'text' },
                { field: 'city', type: 'text', required: true },
                { field: 'state', type: 'text', required: true },
                { field: 'zip', type: 'int', required: true },
                { field: 'short_bio', type: 'text' },
                { field: 'talk_name', type: 'text', required: true },
                { field: 'description', type: 'text' }
            ],
            tabs: [
                { id: 'tab1', caption: 'Import' },
                { id: 'tab2', caption: 'General' },
                { id: 'tab3', caption: 'Address'},
                { id: 'tab4', caption: 'About' }
            ],
            actions: {
                reset: function () {
                    this.clear();
                },
                save: function () {
                    this.save();
                }
            }
        }
    };

    if(w2ui['formEditions']){
		console.log("destroy Editions dans view");
        w2ui['formEditions'].destroy();
	}
    // initialisation
    $('#<?php echo $idPage;?>').w2form(config.form);
    // w2ui.layout_<?php echo $idPage;?>.content('top', $().w2layout(config.layoutVenteTop));
    // w2ui.layout_<?php echo $idPage;?>.content('main', $().w2grid(config.gridVenteDetail)); 
    // w2ui.layout_<?php echo $idPage;?>_top.content('main', $().w2grid(config.gridVente));
    // w2ui.layout_<?php echo $idPage;?>_top.content('right', $().w2grid(config.gridVenteDevise));
     	
}
</script>

<?php 
if(!$this->ajax){
	echo '</body>
</html>';
}else{
	echo '<script type="text/javascript">
			$(function () {initEdition(); });                       		
		</script>		
		';	
}

?>