<?php
if($this->ajax)$urlP = ""; else $urlP = "../";
if($this->inc)$urlP = "";

if(!$this->ajax){
	echo '<!DOCTYPE html>
<html>
	<head>
		<title>ISTE - Statistiques</title>
    		<meta charset="utf-8">
		<link rel="stylesheet" type="text/css" href="../css/gestedit.css" />
		<link rel="stylesheet" type="text/css" href="../css/w2ui.css" />
		<link rel="stylesheet" type="text/css" href="../fonts/font-awesome/font-awesome.css" />
		<script type="text/javascript">
			var urlP = "../";
			var uti = '.$this->uti.';
			var fctInit;
			var alerteSelect = false;			
		</script>		
		<script type="text/javascript" src="../js/jquery.min.js"></script>
		<script type="text/javascript" src="../js/w2ui.js"></script>
		<script type="text/javascript" src="../js/global.js"></script>
		<script type="text/javascript" src="../js/data.js"></script>
		<script type="text/javascript" src="../js/log.js"></script>
		<script type="text/javascript">
			$(function () {
				initAll(initKshf); 
	  			if(uti.id_uti!=0)
					utiIsConnect();
			});                       		
		</script>		
		</head>
<body>
';
}
$idPage = "stats";
?>
    <script type="text/javascript" src="<?php echo $urlP;?>js/d3.js" charset="utf-8"></script>
    <script type="text/javascript" src="<?php echo $urlP;?>js/keshif.js" charset="utf-8"></script>
	<script type="text/javascript" src="<?php echo $urlP;?>js/papaparse.min.js" charset="utf-8"></script>
	<script type="text/javascript" src="<?php echo $urlP;?>js/moment.min.js" charset="utf-8"></script>

    <link rel="stylesheet" href="<?php echo $urlP;?>css/keshif.css" type="text/css" />
    <link rel="stylesheet" href="<?php echo $urlP;?>css/keshifStyle.css" type="text/css" />    
    <style>
    #chart_div {
        width: 90%;
        width: calc(100% - 100px);
        height: 800px;
    }
    .listItem{
        width: 20%;
    }
    .content{
        padding: 3px;
    }
    .thumbnail{
        border-radius: 10px;
        border: solid 1px lightgray;
    }
    </style>    
    <script type="text/javascript" >

	var socialShare = false;
    var noRibbon = true;
    var showLogo = false;
    var githubButton = false;
    
    function resizeBrowser(minWidth, minHeight){
        if(minWidth) $('#chart_div').width($(window).width()-minWidth);
        if(minHeight) $('#chart_div').height($(window).height()-minHeight);
    };
    
    function loadData(browser){
        browser.primaryTableName = "Visualizations";

        kshf.dt.Visualizations = [];
        kshf.dt_id.Visualizations = {};

        kshf.dt.Categories = [];
        kshf.dt_id.Categories = {};
		//récupère les livres
        $.ajax( {
            url: "../export?obj=keshifLivre&json=1",
            async: false, dataType:'json',
            success: function(data){
                data.forEach(function(v){
                    var kshfItem = new kshf.Item(v,'recid');
                    kshf.dt.Visualizations.push(kshfItem);
                    kshf.dt_id.Visualizations[kshfItem.id()] = kshfItem;
                });
            }
        });
        /*ajoute les catégories
        $.ajax( {
            url: "./data/textvis_categories.json",
            async: false,
            success: function(data){
                data.forEach(function(c){
                    var kshfItem = new kshf.Item(c,'title');
                    kshf.dt.Categories.push(kshfItem);
                    kshf.dt_id.Categories[kshfItem.id()] = kshfItem;
                });
            }
        });
		*/
        browser.loadCharts();
    };

    function initKshf(){
        resizeBrowser(100,80);
        $(window).resize(function() {
            resizeBrowser(100,80);
            browser.updateLayout();
        });

    		browser = new kshf.Browser({
            domID: "#chart_div",
            categoryTextWidth: 150,
            itemName: "Livres ISTE",
            source: {
                url: "http://localhost/gestedit/admin/index/keshif",
                callback: loadData
            },
            summaries: [
                {   title: "Tasks: Analytics",
                    value: function(){
                        return this.categories.filter(function(c){
                            return c==="sentiment-analysis" ||
                                c==="text-summarization" ||
                                c==="discourse-analysis" ||
                                c==="stance-analysis" ||
                                c==="event-analysis" ||
                                c==="trend-analysis" ||
                                c==="lexical-analysis" ||
                                c==="relation-analysis" ||
                                c==="category-entry";
                        });
                    }
                },{ title: "Tasks: Visualizations",
                    value: function(){
                        return this.categories.filter(function(c){
                            return c==="roi" ||
                                c==="classification" ||
                                c==="comparison" ||
                                c==="overview" ||
                                c==="monitoring" ||
                                c==="navigation" ||
                                c==="uncertainty";
                        });
                    }
                },{ title: "Data: Sources", layout: 'right',
                    value: function(){
                        return this.categories.filter(function(c){
                            return c==="document" || c==="corpora" || c==="streams";
                        });
                    }
                },{ title: "Data: Properties", layout: 'right',
                    value: function(){
                        return this.categories.filter(function(c){
                            return c==="geospatial" || c==="time-series" || c==="networks";
                        });
                    }
                },{ title: "Domains",
                    value: function(){
                        return this.categories.filter(function(c){
                            return c==="social-media" ||
                                c==="communication" ||
                                c==="patents" ||
                                c==="reviews" ||
                                c==="literature" ||
                                c==="papers" ||
                                c==="editorial-media";
                        });
                    }
                },{ title: "Vis: Dimensionalities", layout: 'right',
                    value: function(){
                        return this.categories.filter(function(c){
                            return c==="1d" || c==="2d" || c==="3d";
                        });
                    }
                },{ title: "Vis: Representations", layout: 'right',
                    value: function(){
                        return this.categories.filter(function(c){
                            return c==="line-plot" ||
                                c==="pixel-area" ||
                                c==="node-link" ||
                                c==="clouds" ||
                                c==="maps" ||
                                c==="text" ||
                                c==="glyph";
                        });
                    }
                },{ title: "Vis: Alignments", layout: 'right',
                    value: function(){
                        return this.categories.filter(function(c){
                            return c==="radial" || c==="linear" || c==="metric";
                        });
                    }
                },{ title: "Year", layout: 'bottom', 
                    value: function(){ return new Date(this.year,1,1); },
                }
            ],
            itemDisplay: {
                sortingOpts: "year",
                displayType: 'grid',
                textSearch: "title",
                recordView: function(){
                    return "<a target='_blank' href='"+this.url+"' class='thumbnail'><img class='thumbImg'></a></span>"+
                        "<span class='title'>"+this.title+"</span>";
                },
            }
        });
    }
            </script>

        <div class="contents"><div id="chart_div"></div></div>

<?php 
if(!$this->ajax){
	echo '</body>
</html>';
}else{
	echo '<script type="text/javascript">
			$(function () {initKshf(); });                       		
		</script>		
		';	
}

?>