<?php 
if(!$this->ajax){
	echo '<!DOCTYPE html>
<html>
	<head>
		<title>ISTE - Livres</title>
		<link rel="stylesheet" type="text/css" href="../css/gestedit.css" />
		<link rel="stylesheet" type="text/css" href="../css/w2ui.css" />
		<link rel="stylesheet" type="text/css" href="../fonts/font-awesome/font-awesome.css" />
		<script type="text/javascript">
			var urlP = "../";
			var uti = '.$this->uti.';
			var fctInit;
			var alerteSelect = false;			
		</script>		
		<script type="text/javascript" src="../js/jquery.min.js"></script>
		<script type="text/javascript" src="../js/w2ui.js"></script>
		<script type="text/javascript" src="../js/global.js"></script>
		<script type="text/javascript" src="../js/data.js"></script>
		<script type="text/javascript" src="../js/log.js"></script>
		<script type="text/javascript">
			$(function () {
				initAll(initLivre); 
	  			if(uti.id_uti!=0)
					utiIsConnect();
	  			else
		    	  		diagLogin.showModal();				
			});                       		
		</script>		
		</head>
<body>
	<p id="promptCompat">Votre navigateur ne pend pas en charge les balises <code><dialog></code></p> 
	<div id="utiConnect"></div>
	<dialog id="diagLogin" close> 
		<label for="iptLogin">Login : </label>
        <input type="text" name="iptLogin" id="iptLogin" required="required">
        <label for="iptlogin">Mot de passe : </label>
        <input type="password" name="iptMdp" id="iptMdp" required="required">
	    <div class="boutons">
			<button onclick="diagLogin.close()">Fermer</button> 
			<button onclick="connecte()">Connexion</button> 
		</div> 
	</dialog> 
';
}
$idPage = "Livre";
?>
<div id="<?php echo $idPage;?>" style="width: 100%; height: 1000px;"></div>

<script type="text/javascript">
var rsLivre = <?php echo $this->json; ?>;

//widget configuration
var pstyle = 'border: 1px solid #dfdfdf; padding: 3px;';
var pstyleDetail = 'background-color: #F0F0C1; border: 1px solid #dfdfdf; padding: 2px;';
var config, itemIsbnSelect,rsIsbnLivre;

function initLivre() {

	config = {
		    layoutLivre: {
		        name: 'layout_<?php echo $idPage;?>',
		        padding: 4,
		        panels: [
		 		    { type: 'top', size: "350px", style: pstyle},
					{ type: 'main', size: 306, resizable: true, style: pstyleDetail},
		            { type: 'left', size: 1200, resizable: true, hidden: true, style: pstyle},
		            { type: 'right', size: 894, resizable: true, hidden: false, style: pstyleDetail}
		        ],
		    },
			layoutDetail : {
		        name: 'layoutDetail_<?php echo $idPage;?>',
		        panels: [
		            { type: 'main', size: '376px', style: pstyleDetail, resizable: true },
		            //{ type: 'left', size: '505px', style: pstyleDetail, resizable: true },
		            { type: 'right', size: '40%', resizable: true, hidden:true, style: pstyleDetail},
		            { type: 'top', size: '266px', style: pstyleDetail, resizable: true },
		            { type: 'bottom', size: '160px', style: pstyleDetail, resizable: true }
		        ]
		    },
		    layoutDetail1 : {
		        name: 'layoutDetail1_<?php echo $idPage;?>',
		        panels: [
		            { type: 'left', size: '305px', resizable: true, style: pstyleDetail},
		            { type: 'main', size: '450px', resizable: true, style: pstyleDetail},
		        ]
		    },		    
		    layoutThemes : {
		        name: 'layoutThemes_<?php echo $idPage;?>',
		        panels: [
		            { type: 'left', size: '30%', hidden: true, resizable: true, style: pstyleDetail},
		            { type: 'main', size: '30%', resizable: true, style: pstyleDetail},
		            { type: 'right', size: '40%', resizable: true, style: pstyleDetail},
		            { type: 'top', size: '160px', hidden: true, resizable: true, style: pstyleDetail}
		        ]
		    },		    
		    layoutPropo : {
		        name: 'layoutPropo_<?php echo $idPage;?>',
		        panels: [
		            { type: 'top', size: '430px', resizable: true, style: pstyleDetail},
		            //{ type: 'left', size: '305px', resizable: true, style: pstyleDetail},
		            { type: 'main', size: '229px', resizable: true, style: pstyleDetail},
		            //{ type: 'right', size: '450px', resizable: true, style: pstyleDetail},
		        ]
		    },		    
		    layoutPropo1 : {
		        name: 'layoutPropo1_<?php echo $idPage;?>',
		        panels: [
		            { type: 'left', size: '305px', resizable: true, style: pstyleDetail},
		            { type: 'main', size: '450px', resizable: true, style: pstyleDetail},
		            { type: 'bottom', size: '160px', resizable: true, style: pstyleDetail},
		        ]
		    },		    
		    
		    gridLivre: { 
		        name: 'grid_<?php echo $idPage;?>', 
				header: 'Livres',		
		        show: { 
					header			: true,		
		            toolbar			: true,
					toolbarReload   : true,
					toolbarColumns  : true,
		            	toolbarSearch   : true,
		            	toolbarAdd      : true,
		            	toolbarDelete   : true,
		            	toolbarSave		: true,
		            	footer: true,
		        },
		        multiSearch: true,
		        searches: [
				    { field: 'titre_fr', caption: 'Titre FR', type: 'text' },
				    { field: 'titre_en', caption: 'Titre EN', type: 'text' },
		            { field: 'prenom', caption: 'Prénom auteur', type: 'text' },
		            { field: 'nom', caption: 'Nom auteur', type: 'text' },
		            { field: 'num', caption: 'ISBN', type: 'text' },
		            { field: 'id_comite', caption: 'Comité', type: 'combo', options: { items: arrListes['comite']} },
		            { field: 'id_serie', caption: 'Série', type: 'combo', options: { items: arrListes['serie']} },
		        ],
		        columns: [                
		            { field: 'recid', caption: 'ID', size: '50px', sortable: true, resizable: true },
		            { field: 'reference', caption: 'Référence', size: '80px', sortable: true, resizable: true, 
		                editable: { type: 'int'}
		            },
		            { field: 'titre_fr', caption: 'Titre français', size: '20%', sortable: true, resizable: true, 
		                editable: { type: 'text' }
		            },
		            { field: 'titre_en', caption: 'Titre anglais', size: '20%', sortable: true, resizable: true, 
		                editable: { type: 'text' }
		            },
		            { field: 'soustitre_fr', caption: 'Sous titre français', size: '20%', sortable: true, resizable: true, 
		                editable: { type: 'text'},
		            },		            
		            { field: 'soustitre_en', caption: 'Sous titre anglais', size: '20%', sortable: true, resizable: true, 
		                editable: { type: 'text'},
		            },		            
		            { field: 'num_vol', caption: 'N° vol.', size: '60px', sortable: true, resizable: true, 
		                editable: { type: 'int'},
		            },		            
		            { field: 'type_1', caption: 'Type 1', size: '60px', sortable: true, resizable: true, 
			            	editable: { type: 'list', items: arrListes['type1'], showAll: true },
		                render: function (record, index, col_index) {
		                    var html = this.getCellValue(index, col_index);
		                    return html.text ? html.text : html;
		                }
		            },		            
		            { field: 'type_2', caption: 'Type 2', size: '60px', sortable: true, resizable: true, 
		            		editable: { type: 'list', items: arrListes['type2'], showAll: true },
		                render: function (record, index, col_index) {
		                    var html = this.getCellValue(index, col_index);
		                    return html.text ? html.text : html;
		                }
		            },
		            /*		            
		            { field: 'auteurs', caption: 'Auteur', size: '200px', sortable: true, resizable: true},		            
		            { field: 'isbns', caption: 'ISBNS', size: '200px', sortable: true, resizable: true},		            
		            */
		        ],
		        toolbar: {
		            items: [
		                { id: 'export', type: 'button', caption: 'Exporter', icon: 'fa-file' }
		            ],
		            onClick: function (event) {
		                if (event.target == 'export') {
		                		open(urlP+'export?obj=livre',"_blank")
		                }
		            }
		        },
		        records: rsLivre,
		        onSearch: function(event) {
		        		var grid = this;
		        		if(event.searchField=="multi"){
		            		event.onComplete = function () {
			            		$.get('<?php if(!$this->ajax) echo '../'; ?>cherche/livre',
							{"searchData":event.searchData},
			            		function(js){
			            			var ids = [];
			            			js.rs.forEach(function(d){
			            				rsLivre.forEach(function(l, i){
				            				if(l.id_livre==d)ids.push(i);
			            				});
				            		});
		                        grid.last.searchIds = ids;
		                        grid.total      = grid.last.searchIds.length; 
		                        grid.buffered   = grid.total; 
		                        grid.refresh();
		                        w2alert(js.message);
			           		},"json");
		                }
		            }else{
			            	grid.localSearch();		            
		            }
		        },		        
		        onRender: function(event) {
		        		w2ui.grid_<?php echo $idPage;?>.lock('Loading...', true);	
		        		event.onComplete = function () {
		        			w2ui.grid_<?php echo $idPage;?>.unlock();
		            		if(alerteSelect){
		                		selectRowInGrid(alerteSelect.recid, 'grid_Livre');
		            		}
		        			
		        	    }		        
		        },
		        onSave: function(event) {
		            var changes = w2ui['grid_<?php echo $idPage;?>'].getChanges();
		            changes.forEach(function(c, i){
			            c.obj = 'livre';
			            if(c.type_1)c.type_1=c.type_1.text;			            
			            if(c.type_2)c.type_2=c.type_2.text;			            
				        	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
			        			c,
			        			function(html){
			        				if(changes.length==i+1)w2alert(html);
			        			});                        
		            });
		        },
		        onDelete: function(event) {            
					var p = {id:itemSelect.recid, obj:'livre'};
					if(event.force){
			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/delete',
							p,
			            		function(js){
			            			w2alert(js.message);
			           		},"json");
					}
			    },
		        onAdd: function(event) {            
		            w2ui['layout_<?php echo $idPage;?>'].toggle('left', true);
		            w2ui['layout_<?php echo $idPage;?>'].hide('main', true);
		            w2ui['layout_<?php echo $idPage;?>'].hide('right', true);
			    },
		        onClick: function (event) {
		            itemSelect = this.get(event.recid);
					showDataLivre();           			           		           
		        }	    
		    },	    
		    formLivre: { 
		        header: 'Ajouter un livre',
		        name: 'form_<?php echo $idPage;?>',
		        fields: [
		            { name: 'reference', type: 'int', required: false, html: { caption: 'Référence', attr: 'size="40" maxlength="40"' } },
		            { name: 'titre_fr', type: 'text', required: false, html: { caption: 'Titre français', attr: 'size="200" ' } },
		            { name: 'titre_en', type: 'text', required: false, html: { caption: 'Titre anglais', attr: 'size="200" ' } },
		            { name: 'soustitre_fr', type: 'text', html: { caption: 'Sous titre français', attr: 'size="200"' } },
		            { name: 'soustitre_en', type: 'text', html: { caption: 'Sous titre anglais', attr: 'size="200"' } },
		            { name: 'num_vol', type: 'int', html: { caption: 'N° vol.', attr: 'size="10"' } },
		            { name: 'type_1', type: 'list', options: { items: arrListes['type1'] }
		            		, html: { caption: 'Type 1', attr: 'size="20"' } 
		            		},
		            { name: 'type_2', type: 'list', options: { items: arrListes['type2'] }
		            		, html: { caption: 'Type 2', attr: 'size="20"' } 
		            		}
		        ],
		        actions: {
		            Reset: function () {
		                w2ui['layout_<?php echo $idPage;?>'].toggle('left', true);
		                w2ui['layout_<?php echo $idPage;?>'].toggle('main', true);
		                w2ui['layout_<?php echo $idPage;?>'].toggle('right', true);
		                this.clear();
		            },
		            Save: function () {
		                var errors = this.validate();
		                if (errors.length > 0) return;
		                var data = this.record;
			            if(data.type_1)data.type_1=data.type_1.text;			            
			            if(data.type_2)data.type_2=data.type_2.text;			            
		                data.obj = "livre";
		                this.clear();		                
			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/insert',
							data,
			            		function(js){
				                var g = w2ui['grid_<?php echo $idPage;?>'];
								g.add(js.rs.rsLivre);
								g.selectNone();
				                g = w2ui['form_<?php echo $idPage;?>'];
								g.clear();
		                        	w2ui['layout_<?php echo $idPage;?>'].toggle('left', true);
		                        	w2ui['layout_<?php echo $idPage;?>'].toggle('main', true);
		    		                w2ui['layout_<?php echo $idPage;?>'].toggle('right', true);
			            			w2alert(js.message);
			           		},"json");
		            }
		        }
		    },
	    		formPropo: { 
			        header: 'Proposition',
			        name: 'form_<?php echo $idPage;?>_propo',
			        fields: [
			            { name: 'date_debut', type: 'date', options:{format: 'yyyy-mm-dd'}, required: true,  html: {caption: 'Date entrée base'} },
			            //{ name: 'date_contrat', type: 'date', options:{format: 'yyyy-mm-dd'}, required: false, html: { caption: 'Date de contrat'} },
			            { name: 'base_contrat', type: 'list', required: false, html: { caption: 'Base contrat'}
			            		,options: { items: arrListes['contrat'].base }} , 
			            //{ name: 'date_manuscrit', type: 'date', options:{format: 'yyyy-mm-dd'}, html: { caption: 'Date du manuscrit' } },
			            { name: 'langue', type: 'list', html: { caption: 'Langue'}
			            		,options: { items: arrListes['langues'] }} , 
				        { name: 'traduction', type: 'list', html: { caption: 'Traduction'}
						    ,options: { items: arrListes['traduction'] }},
			            { name: 'publication_fr', type: 'checkbox', html: { caption: 'Publication français' } },
			            { name: 'publication_en', type: 'checkbox', html: { caption: 'Publication anglais' } },
			            //{ name: 'nb_page_fr', type: 'int', html: { caption: 'Nb. page fr' } },
			            //{ name: 'nb_page_en', type: 'int', html: { caption: 'Nb. page en' } }
			        ],
			        actions: {
			            Save: function () {
			                var errors = this.validate();
			                if (errors.length > 0) return;
			                var data = this.record;
				            if(data.base_contrat)data.base_contrat=data.base_contrat.text;			            
				            if(data.langue)data.langue=data.langue.text;			            
				            if(data.traduction)data.traduction=data.traduction.text;			            
				            data.id_livre = itemSelect.recid;			            
			                data.obj = "proposition";
				            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
								data,
				            		function(message){
				            			w2alert(message);
				           		});
			            }
			        }
			    },
			    gridProcessLivre: { 
			        name: 'grid_<?php echo $idPage;?>_process_livre', 
					header: 'Planning du livre',		
					show: {toolbar		: true,
		    				toolbarReload   : false,
		    				toolbarColumns  : false,
		                	toolbarSearch   : false,
		                	toolbarAdd      : true,
		                	toolbarDelete   : true,
		                	toolbarSave		: true,
		                	header			: true, 
		                	columnHeaders	: true},
			        columns: [      		  		           
			            { field: 'recid', caption: 'ID', size: '50px', hidden:true, sortable: true, resizable: true },
			            { field: 'tache', caption: 'Tâche', size: '175px', sortable: true, resizable: true},
			            { field: 'debut', caption: 'Début', editable: { type: 'date'}, size: '80px', sortable: true, resizable: true},
			            { field: 'prevision', caption: 'Prévision', editable: { type: 'date'}, size: '80px', sortable: true, resizable: true},
			            { field: 'fin', caption: 'Fin', editable: { type: 'date'}, size: '80px', sortable: true, resizable: true},
			            { field: 'commentaire', caption: 'Commentaires', editable: { type: 'text'}, size: '200px', sortable: true, resizable: true},
			            { field: 'alerte', caption: 'Date alerte', editable: { type: 'date'}, size: '80px', sortable: true, resizable: true},
			        ],
			        onClick: function (event) {
			        },
			        onSave: function(event) {
			            var changes = w2ui['grid_<?php echo $idPage;?>_process_livre'].getChanges();
			            changes.forEach(function(c, i){
				            c.obj = 'prevision';
				            if(c.debut) c.debut = w2utils.formatDate(c.debut, 'yyyy-mm-dd');
				            if(c.prevision) c.prevision = w2utils.formatDate(c.prevision, 'yyyy-mm-dd');
				            if(c.fin) c.fin = w2utils.formatDate(c.fin, 'yyyy-mm-dd');
				            if(c.alerte) c.alerte = w2utils.formatDate(c.alerte, 'yyyy-mm-dd');
					        	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
				        			c,
				        			function(html){
				        				if(changes.length==i+1)w2alert(html);
				        			});                        
			            });
			        },
	    		        onDelete: function(event) {            
						var s = w2ui[event.target].getSelection();
	    					var p = {id:s.recid, obj:'prevision'};
	    					if(event.force){
	    			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/delete',
	    							p,
	    			            		function(js){
	    			            			w2alert(js.message);
	    			           		},"json");
	    					}
	    			    },
	    		        onAdd: function(event) {            
	    		        		openPopupAjoutTache();
	    		        	}					        
			    },
			    formTache: { 
			        name: 'form_<?php echo $idPage;?>_tache',
			        fields: [
			            { name: 'id_tache', required: true, type: 'combo', options: { items: arrListes['tache'] }
			            		, html: { caption: 'Nom de la Tâche', attr: 'size="20"' } 
			            		},
			        ],
			        actions: {
			            Reset: function () {
			                this.clear();
			                w2popup.close();
			            },
			            Save: function () {
			                var errors = this.validate();
			                if (errors.length > 0) return;
			                var g = w2ui['grid_<?php echo $idPage;?>_process_livre'];
			                var data = this.record;
			                data.id_processus = g.records[0].id_processus;
			                if(data.id_tache.recid)data.id_tache = data.id_tache.recid;
			                else data.tache = data.id_tache;
			                data.id_pxu = g.records[0].id_plu;
			                data.obj = "prevision";
			                data.pxu_obj = "livre";
				            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/insert',
								data,
				            		function(js){
				            			if(js.rs){					            			
										g.add(js.rs);
										g.selectNone();
				            			}
						            w2alert(js.message);
				           		},"json");
			            }
			        }
			    },	
			    gridPage : {
		            header: 'Nb. de page',
		            show: {toolbar		: true,
		    				toolbarReload   : false,
		    				toolbarColumns  : false,
		                	toolbarSearch   : false,
		                	toolbarAdd      : true,
		                	toolbarDelete   : true,
		                	toolbarSave		: false,
		                	header			: true, 
		                	columnHeaders	: true},
		            name: 'grid_<?php echo $idPage;?>_page', 
		            columns: [                
		  		            { field: 'recid', caption: 'ID', size: '5px',hidden:true, sortable: true, resizable: true },
				            { field: 'type', caption: 'Type', size: '80px', sortable: true, resizable: true},
				            { field: 'nombre', caption: 'Nb.', size: '60px', sortable: true, resizable: true},
				            { field: 'maj', caption: 'Date', size: '100px', sortable: true, resizable: true},
		            ],
		            onAdd: function(event) {
			        		openPopupAjoutPage();
				    },
			        onDelete: function(event) {            
						var p = {'obj':'page'};
						if(event.force){
							var s = w2ui[event.target].getSelection();
							p.id = s[0];
				            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/delete',
									p,
					            		function(js){
					            			w2alert(js.message);
					           		},"json");
						}
				    },
		    		},
		    		formPage: { 
				        name: 'form_<?php echo $idPage;?>_page',
				        fields: [
				            { name: 'type', required: true, type: 'list', options: { items: arrListes['page'] }
				            		, html: { caption: 'Type', attr: 'size="20"' } 
				            		},
						 	{ name: 'maj', required: true, type: 'date', options:{format: 'yyyy-mm-dd'}
				            		, html: { caption: 'Date', attr: 'size="20"' } 
				            		},
						 	{ name: 'nombre', required: true, type: 'int', html: { caption: 'Nombre', attr: 'size="20"' } 
				            		},           		
				        ],
				        actions: {
				            Reset: function () {
				                this.clear();
				                w2popup.close();
				            },
				            Save: function () {
				                var errors = this.validate();
				                if (errors.length > 0) return;
				                var g = w2ui['grid_<?php echo $idPage;?>_page'];
				                var data = this.record;
				                data.id_livre = itemSelect.recid;
				                data.type = data.type.text;
				                data.obj = "page";
					            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/insert',
									data,
					            		function(js){
					            			if(js.rs){					            			
											g.add(js.rs);
											g.selectNone();
					            			}
							            w2alert(js.message);
					           		},"json");
				            }
				        }
				    },				    			    			    
	    			formCommentaire: { 
			        name: 'form_<?php echo $idPage;?>_commentaire',
			        fields: [
			            { name: 'commentaire', type: 'textarea'
				            , html: { caption: 'Commentaires :', attr: 'style="width: 100%; height: 150px; resize: none"'} 
			           	}
			        ],
			        actions: {
			            Save: function () {
			                var errors = this.validate();
			                if (errors.length > 0) return;
			                var data = this.record;
			                data.obj = "proposition";
				            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
								data,
				            		function(html){
				            			w2alert(html);
				           		});
			            }
			        }
			    },	
		    gridCollection : {
	            header: 'Collection',
	            show: {toolbar		: true,
	    				toolbarReload   : false,
	    				toolbarColumns  : false,
	                	toolbarSearch   : false,
	                	toolbarAdd      : true,
	                	toolbarDelete   : true,
	                	toolbarSave		: false,
	                	header			: true, 
	                	columnHeaders	: false},
	            name: 'grid_<?php echo $idPage;?>_collection', 
	            columns: [                
	  		            { field: 'recid', caption: 'ID', size: '5px',hidden:true, sortable: true, resizable: true },
			            { field: 'titre', caption: 'Titre', size: '80%', sortable: true, resizable: true},
	            ],
	            onAdd: function(event) {
		            w2ui['layoutThemes_<?php echo $idPage;?>'].hide('main', true);
		            w2ui['layoutThemes_<?php echo $idPage;?>'].hide('right', true);	
	                if(w2ui['form_<?php echo $idPage;?>_collection'])w2ui['form_<?php echo $idPage;?>_collection'].destroy();	            
		            w2ui['layoutThemes_<?php echo $idPage;?>'].content('top', $().w2form(config.formCollection));
		            w2ui['layoutThemes_<?php echo $idPage;?>'].toggle('top', true);
			    },
		        onDelete: function(event) {            
					console.log(event);
					var p = {'id_livre':itemSelect.recid,'obj':'livrexcollection'};
					if(event.force){
						var s = w2ui[event.target].getSelection();
						p.id_collection = s[0];
			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/delete',
								p,
				            		function(js){
				            			w2alert(js.message);
				           		},"json");
					}
			    },
	    		},
		    formCollection: { 
		        header: 'Ajouter une collection',
		        name: 'form_<?php echo $idPage;?>_collection',
		        fields: [
		            { name: 'collection', type: 'list', required: true
			            	, html: { caption: 'Collection', attr: 'size="60" maxlength="60"' } 
		            		, options: { items: arrListes['collection'] }
		           	}
		        ],
		        actions: {
		            Reset: function () {
			            w2ui['layoutThemes_<?php echo $idPage;?>'].toggle('main', true);
			            w2ui['layoutThemes_<?php echo $idPage;?>'].toggle('right', true);		            
		                w2ui['form_<?php echo $idPage;?>_collection'].destroy();	            
			            w2ui['layoutThemes_<?php echo $idPage;?>'].hide('top', true);
		                this.clear();
		            },
		            Save: function () {
		                var errors = this.validate();
		                if (errors.length > 0) return;
		                var g = w2ui['grid_<?php echo $idPage;?>_collection'];
		                var data = this.record;
		                this.clear();		                
			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/insert',
							{obj:"livrexcollection",id_livre:itemSelect["id_livre"],id_collection:data.collection.id},
			            		function(js){
			            			if(js.rs){					            			
									g.add(js.rs);
									g.selectNone();
			            			}
					            w2ui['layoutThemes_<?php echo $idPage;?>'].toggle('main', true);
					            w2ui['layoutThemes_<?php echo $idPage;?>'].toggle('right', true);		            
				                w2ui['form_<?php echo $idPage;?>_collection'].destroy();	            
					            w2ui['layoutThemes_<?php echo $idPage;?>'].hide('top', true);
					            w2alert(js.message);
			           		},"json");
		            }
		        }
		    },	    					    
		    gridComite : {
	            header: 'Comité',
	            show: {toolbar		: true,
	    				toolbarReload   : false,
	    				toolbarColumns  : false,
	                	toolbarSearch   : false,
	                	toolbarAdd      : true,
	                	toolbarDelete   : true,
	                	toolbarSave		: false,
	                	header			: true, 
	                	columnHeaders	: false},
	            name: 'grid_<?php echo $idPage;?>_comite', 
	            columns: [                
	  		            { field: 'recid', caption: 'ID', size: '5px',hidden:true, sortable: true, resizable: true },
			            { field: 'titre', caption: 'Titre', size: '80%', sortable: true, resizable: true},
	            ],
	            onAdd: function(event) {
		            w2ui['layoutThemes_<?php echo $idPage;?>'].hide('main', true);
		            w2ui['layoutThemes_<?php echo $idPage;?>'].hide('right', true);	
	                if(w2ui['form_<?php echo $idPage;?>_comite'])w2ui['form_<?php echo $idPage;?>_comite'].destroy();	            
		            w2ui['layoutThemes_<?php echo $idPage;?>'].content('top', $().w2form(config.formComite));
		            w2ui['layoutThemes_<?php echo $idPage;?>'].toggle('top', true);
			    },
		        onDelete: function(event) {            
					console.log(event);
					var p = {'id_livre':itemSelect.recid,'obj':'comitexlivre'};
					if(event.force){
						var s = w2ui[event.target].getSelection();
						p.id_comite = s[0];
			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/delete',
								p,
				            		function(js){
				            			w2alert(js.message);
				           		},"json");
					}
			    },
	    		},
	    		formComite: { 
		        header: 'Ajouter un comite',
		        name: 'form_<?php echo $idPage;?>_comite',
		        fields: [
		            { name: 'comite', type: 'list', required: true
			            	, html: { caption: 'Comité', attr: 'size="60" maxlength="60"' } 
		            		, options: { items: arrListes['comite'] }
		           	}
		        ],
		        actions: {
		            Reset: function () {
			            w2ui['layoutThemes_<?php echo $idPage;?>'].toggle('main', true);
			            w2ui['layoutThemes_<?php echo $idPage;?>'].toggle('right', true);	
		                w2ui['form_<?php echo $idPage;?>_comite'].destroy();	            
			            w2ui['layoutThemes_<?php echo $idPage;?>'].hide('top', true);
		                this.clear();
		            },
		            Save: function () {
		                var errors = this.validate();
		                if (errors.length > 0) return;
		                var g = w2ui['grid_<?php echo $idPage;?>_comite'];
		                var data = this.record;
		                this.clear();		                
			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/insert',
							{obj:"comitexlivre",id_livre:itemSelect["id_livre"],id_comite:data.comite.id},
			            		function(js){
			            			if(js.rs){					            			
									g.add(js.rs);
									g.selectNone();
			            			}
					            w2ui['layoutThemes_<?php echo $idPage;?>'].toggle('main', true);
					            w2ui['layoutThemes_<?php echo $idPage;?>'].toggle('right', true);	
				                w2ui['form_<?php echo $idPage;?>_comite'].destroy();	            
					            w2ui['layoutThemes_<?php echo $idPage;?>'].hide('top', true);
					            w2alert(js.message);
			           		},"json");
		            }
		        }
		    },
		    gridSerie : {
	            header: 'Série',
	            show: {toolbar		: true,
	    				toolbarReload   : false,
	    				toolbarColumns  : false,
	                	toolbarSearch   : false,
	                	toolbarAdd      : true,
	                	toolbarDelete   : true,
	                	toolbarSave		: false,
	                	header			: true, 
	                	columnHeaders	: false},
	            name: 'grid_<?php echo $idPage;?>_serie', 
	            columns: [                
	  		            { field: 'recid', caption: 'ID', size: '5px',hidden:true, sortable: true, resizable: true },
			            { field: 'titre', caption: 'Titre', size: '80%', sortable: true, resizable: true},
	            ],
	            onAdd: function(event) {
		            w2ui['layoutThemes_<?php echo $idPage;?>'].hide('main', true);
		            w2ui['layoutThemes_<?php echo $idPage;?>'].hide('right', true);	
	                if(w2ui['form_<?php echo $idPage;?>_serie'])w2ui['form_<?php echo $idPage;?>_serie'].destroy();	            
		            w2ui['layoutThemes_<?php echo $idPage;?>'].content('top', $().w2form(config.formSerie));
		            w2ui['layoutThemes_<?php echo $idPage;?>'].toggle('top', true);
			    },
		        onDelete: function(event) {            
					console.log(event);
					var p = {'id_livre':itemSelect.recid,'obj':'livrexserie'};
					if(event.force){
						var s = w2ui[event.target].getSelection();
						p.id_serie = s[0];
			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/delete',
								p,
				            		function(js){
				            			w2alert(js.message);
				           		},"json");
					}
			    },
	    		},
	    		formSerie: { 
		        header: 'Ajouter une série',
		        name: 'form_<?php echo $idPage;?>_serie',
		        fields: [
		            { name: 'serie', type: 'list', required: true
			            	, html: { caption: 'Série', attr: 'size="60" maxlength="60"' } 
		            		, options: { items: arrListes['serie'] }
		           	}
		        ],
		        actions: {
		            Reset: function () {
			            w2ui['layoutThemes_<?php echo $idPage;?>'].toggle('main', true);
			            w2ui['layoutThemes_<?php echo $idPage;?>'].toggle('right', true);	
		                w2ui['form_<?php echo $idPage;?>_serie'].destroy();	            
			            w2ui['layoutThemes_<?php echo $idPage;?>'].hide('top', true);
		                this.clear();
		            },
		            Save: function () {
		                var errors = this.validate();
		                if (errors.length > 0) return;
		                var g = w2ui['grid_<?php echo $idPage;?>_serie'];
		                var data = this.record;
		                this.clear();		                
			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/insert',
							{obj:"livrexserie",id_livre:itemSelect["id_livre"],id_serie:data.serie.id},
			            		function(js){
			            			if(js.rs){					            			
									g.add(js.rs);
									g.selectNone();
			            			}
					            w2ui['layoutThemes_<?php echo $idPage;?>'].toggle('main', true);
					            w2ui['layoutThemes_<?php echo $idPage;?>'].toggle('right', true);	
				                w2ui['form_<?php echo $idPage;?>_serie'].destroy();	            
					            w2ui['layoutThemes_<?php echo $idPage;?>'].hide('top', true);
					            w2alert(js.message);
			           		},"json");
		            }
		        }
		    },
		    gridISBN : {
	            header: 'ISBN',
	            show: {toolbar		: true,
	    				toolbarReload   : false,
	    				toolbarColumns  : false,
	                	toolbarSearch   : false,
	                	toolbarAdd      : true,
	                	toolbarDelete   : true,
	                	toolbarSave		: true,
	                	header			: true, 
	                	columnHeaders	: true},
	            name: 'grid_<?php echo $idPage;?>_isbn', 
	            columns: [                
	  		            { field: 'recid', caption: 'ID', size: '5px',hidden:true, sortable: true, resizable: true },
			            { field: 'num', caption: 'ISBN', size: '140px', sortable: true, resizable: true,
			                editable: { type: 'text'}},
			            { field: 'date_parution', caption: 'Parution', size: '90px', sortable: true, resizable: true,
			                editable: { type: 'date'}},
			            { field: 'id_editeur', caption: 'Editeur', size: '130px', sortable: true, resizable: true,
			            	editable: { type: 'select', items: arrListes['editeur'] }, 
			                render: function (record, index, col_index) {
			                    var html = '';
			                    for (var p in arrListes['editeur']) {
			                        if (arrListes['editeur'][p].id == this.getCellValue(index, col_index)) html = arrListes['editeur'][p].text;
			                    }
			                    return html;
			                }},
			            { field: 'tirage', caption: 'Tirage', size: '60px', sortable: true, resizable: true, render: 'int',
			                    editable: { type: 'int', min: 0}},
			            { field: 'nb_page', caption: 'Nb. page', size: '70px', sortable: true, resizable: true, render: 'int',
			                        editable: { type: 'int', min: 0}},
			            { field: 'type', caption: 'Type', size: '40%', sortable: true, resizable: true,
			            		editable: { type: 'list', items: arrListes['typeISBN'], showAll: true },
				                render: function (record, index, col_index) {
				                    var html = this.getCellValue(index, col_index);
				                    return html.text ? html.text : html;
				                }},
	            ],
	            onAdd: function(event) {
		        		openPopupAjoutISBN();
			    },
		        onClick: function (event) {
				    itemIsbnSelect = this.get(event.recid);
		        },	    
		        onSave: function(event) {
		            var changes = w2ui['grid_<?php echo $idPage;?>_isbn'].getChanges();
		            changes.forEach(function(c, i){
			            c.obj = 'isbn';
		                if(c.type)c.type = c.type.text;
			            if(c.date_parution)c.date_parution = w2utils.formatDate(c.date_parution, 'yyyy-mm-dd');
				        	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
			        			c,
			        			function(html){
			        				if(changes.length==i+1)w2alert(html);
			        			});                        
		            });
		        },
		        onDelete: function(event) {            
					console.log(event);
					if(event.force){
						var s = w2ui[event.target].getSelection();
			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/delete',
			            			{'id':s[0],'obj':'isbn'},
				            		function(js){
				            			w2alert(js.message);
				           		},"json");
					}
			    },
	    		},		    				    	    		    
	    		formISBN: { 
		        //header: 'Ajouter un ISBN',
		        name: 'form_<?php echo $idPage;?>_isbn',
		        fields: [
		            { name: 'num', type: 'text', required: true, html: { caption: 'ISBN', attr: 'size="60px"' } },
		            { name: 'id_editeur', required: true, type: 'list', options: { items: arrListes['editeur'] }
		            		, html: { caption: 'Editeur', attr: 'size="20"' } 
		            		},
				    { name: 'date_parution', type: 'date', options:{format: 'yyyy-mm-dd'}, html: {caption: 'Date de parution'} },
		            { name: 'tirage', type: 'int', html: { caption: 'Tirage', attr: 'size="20px"' } },
		            { name: 'nb_page', type: 'int', html: { caption: 'Nb. page', attr: 'size="20px"' } },
		            { name: 'type', required: true, type: 'list', options: { items: arrListes['typeISBN'] }
	            			, html: { caption: 'Type', attr: 'size="20"' } 
	            		},
		        ],
		        actions: {
		            Reset: function () {
		                this.clear();
		                w2popup.close();
		            },
		            Save: function () {
		                var errors = this.validate();
		                if (errors.length > 0) return;
		                var g = w2ui['grid_<?php echo $idPage;?>_isbn'];
		                var data = this.record;
		                data.id_livre = itemSelect["id_livre"];
		                data.id_editeur = data.id_editeur.id;
		                data.type = data.type.text;
		                data.obj = "isbn";
		                this.clear();		                
			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/insert',
							data,
			            		function(js){
			            			if(js.rs){					            			
									g.add(js.rs);
									g.selectNone();
			            			}
					            w2alert(js.message);
			           		},"json");
		            }
		        }
		    },
		    gridPrix : {
	            header: 'Prix',
	            show: {toolbar		: true,
	    				toolbarReload   : false,
	    				toolbarColumns  : false,
	                	toolbarSearch   : false,
	                	toolbarAdd      : true,
	                	toolbarDelete   : true,
	                	toolbarSave		: true,
	                	header			: true, 
	                	columnHeaders	: true},
	            name: 'grid_<?php echo $idPage;?>_prix', 
	            columns: [                
	  		            { field: 'recid', caption: 'ID', size: '5px',hidden:true, sortable: true, resizable: true },
			            { field: 'num', caption: 'ISBN', size: '140px', sortable: true, resizable: true},
			            { field: 'type_isbn', caption: 'type', size: '80px', sortable: true, resizable: true},
			            { field: 'type_prix', caption: 'Prix', size: '40%', sortable: true, resizable: true 
			            		,editable: { type: 'list', items: arrListes['prix'], showAll: true },
			                render: function (record, index, col_index) {
			                    var html = this.getCellValue(index, col_index);
			                    return html.text ? html.text : html;
			                }},
				        { field: 'prix_euro', caption: 'Montant &euro;', size: '80px', sortable: true, resizable: true
			            		,editable:{type:'float'}},
			            { field: 'prix_livre', caption: 'Montant &pound;', size: '80px', sortable: true, resizable: true
				            	,editable:{type:'float'}},
				        { field: 'prix_dollar', caption: 'Montant $', size: '80px', sortable: true, resizable: true
				        		,editable:{type:'float'}},
	            ],
	            onAdd: function(event) {
		        		openPopupAjoutPrix();
			    },
		        onSave: function(event) {
		            var changes = w2ui['grid_<?php echo $idPage;?>_prix'].getChanges();
		            changes.forEach(function(c, i){
			            c.obj = 'prix';
			            c.id_isbn = itemIsbnSelect;
			            if(c.type_prix)c.type = c.type_prix.text;
			            delete c.type_prix;
				        	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
			        			c,
			        			function(html){
			        				if(changes.length==i+1)w2alert(html);
			        			});                        
		            });
		        },
		        onDelete: function(event) {            
					console.log(event);
					if(event.force){
						var s = w2ui[event.target].getSelection();
			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/delete',
			            			{'id':s[0],'obj':'prix'},
				            		function(js){
				            			w2alert(js.message);
				           		},"json");
					}
			    },
	    		},			    
	    		formPrix: { 
			        name: 'form_<?php echo $idPage;?>_prix',
			        fields: [
			            {name: 'maj', type: 'date', options:{format: 'yyyy-mm-dd',openOnFocus: true}, required: true,  html: {caption: 'Date du prix'} },
			            {required: true,  name: 'id_isbn', type: 'list', options: { items: rsIsbnLivre}
			            		, html: { caption: 'ISBN', attr: 'size="20"' } 
			            		},
			            { name: 'prix_euro', type: 'float', html: { caption: 'Prix &euro;' } },
			            { name: 'prix_livre', type: 'float', html: { caption: 'Prix &pound;' } },
			            { name: 'prix_dollar', type: 'float', html: { caption: 'Prix $' } },
			            {required: true, name: 'type', type: 'list', options: { items: arrListes['prix'] }
			            		, html: { caption: 'type', attr: 'size="20"' } 
			            		},
			        ],
			        actions: {
			            Reset: function () {
			                this.clear();
			                w2popup.close();
			            },
			            Save: function () {
			                var errors = this.validate();
			                if (errors.length > 0) return;
			                var data = this.record;
				            if(data.id_isbn){
					            data.id_isbn=data.id_isbn.id;
				            }			            
				            if(data.type)data.type=data.type.text;			            
				            data.pdf ? data.pdf=1 : data.pdf=0;			            
				            data.obj = "prix";
				            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/insert',
								data,
				            		function(js){
				            			if(js.rs){
						                var g = w2ui['grid_<?php echo $idPage;?>_prix'];
										g.add(js.rs);
										g.selectNone();
				            			}
				            			w2alert(js.message);
				           		},"json");
			            }
			        }
			    },	
	    		gridAuteur : {
	            header: 'Auteurs',
	            show: {toolbar		: true,
	    				toolbarReload   : false,
	    				toolbarColumns  : false,
	                	toolbarSearch   : false,
	                	toolbarAdd      : true,
	                	toolbarDelete   : true,
	                	toolbarSave		: true,
	                	header			: true, 
	                	columnHeaders	: true},
	            name: 'grid_<?php echo $idPage;?>_auteur', 
	            columns: [                
	  		            { field: 'recid', caption: 'ID', size: '5px',hidden:true, sortable: true, resizable: true },
			            { field: 'id_auteur', caption: 'Auteur', size: '60%', sortable: true, resizable: true,
			            	editable: { type: 'select', items: arrListes['auteur'] }, 
			                render: function (record, index, col_index) {
			                    var html = '';
			                    for (var p in arrListes['auteur']) {
			                        if (arrListes['auteur'][p].id == this.getCellValue(index, col_index)) html = arrListes['auteur'][p].text;
			                    }
			                    return html;
			                }},	  		            
			            { field: 'role', caption: 'Role', size: '40%', sortable: true, resizable: true,
				                editable: { type: 'list', items: arrListes['roles'], showAll: true },
				                render: function (record, index, col_index) {
				                    var html = this.getCellValue(index, col_index);
				                    return html.text ? html.text : html;
				                }},
	            ],
	            onAdd: function(event) {
		        		openPopupAjoutAuteur();
			    },
		        onSave: function(event) {
		            var changes = w2ui['grid_<?php echo $idPage;?>_auteur'].getChanges();
		            changes.forEach(function(c, i){
			            c.obj = 'livrexauteur';
		                if(c.role)c.role = c.role.text;
				        	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
			        			c,
			        			function(html){
			        				if(changes.length==i+1)w2alert(html);
			        			});                        
		            });
		        },			    
		        onDelete: function(event) {            
					var p = {'obj':'livrexauteur'};
					if(event.force){
						var s = w2ui[event.target].getSelection();
						p.id = s[0];
			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/delete',
								p,
				            		function(js){
				            			w2alert(js.message);
				           		},"json");
					}
			    },
	    		},	
	    		formAuteur: { 
		        //header: 'Ajouter un auteur',
		        name: 'form_<?php echo $idPage;?>_auteur',
		        fields: [
		            { name: 'id_auteur', required: true, type: 'list', options: { items: arrListes['auteur'] }
		            		, html: { caption: 'Auteur', attr: 'size="20"' } 
		            		},
		            { name: 'role', required: true, type: 'list', options: { items: arrListes['roles'] }
		            		, html: { caption: 'Rôle', attr: 'size="20"' } 
		            		},
		        ],
		        actions: {
		            Reset: function () {
		                this.clear();
		                w2popup.close();
		            },
		            Save: function () {
		                var errors = this.validate();
		                if (errors.length > 0) return;
		                var g = w2ui['grid_<?php echo $idPage;?>_auteur'];
		                var data = this.record;
		                data.id_livre = itemSelect["id_livre"];
		                data.id_auteur = data.id_auteur.id;
		                data.role = data.role.text;
		                data.obj = "livrexauteur";
		                this.clear();		                
			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/insert',
							data,
			            		function(js){
			            			if(js.rs){					            			
									g.add(js.rs);
									g.selectNone();
			            			}
					            w2alert(js.message);
			           		},"json");
		            }
		        }
		    },
		    	    
		};
	
    // initialisation
    $('#<?php echo $idPage;?>').w2layout(config.layoutLivre);
    w2ui.layout_<?php echo $idPage;?>.content('top', $().w2grid(config.gridLivre));
    w2ui.layout_<?php echo $idPage;?>.content('main', $().w2layout(config.layoutPropo));
    w2ui.layout_<?php echo $idPage;?>.content('left', $().w2form(config.formLivre));
    w2ui.layout_<?php echo $idPage;?>.content('right', $().w2layout(config.layoutDetail));

    w2ui.layoutDetail_<?php echo $idPage;?>.content('top', $().w2grid(config.gridProcessLivre));        
    w2ui.layoutDetail_<?php echo $idPage;?>.content('bottom', $().w2layout(config.layoutThemes));    
    w2ui.layoutDetail_<?php echo $idPage;?>.content('main', $().w2grid(config.gridPrix));

    w2ui.layoutThemes_<?php echo $idPage;?>.content('right', $().w2grid(config.gridComite));
    w2ui.layoutThemes_<?php echo $idPage;?>.content('main', $().w2grid(config.gridSerie));

    w2ui.layoutPropo_<?php echo $idPage;?>.content('top', $().w2layout(config.layoutPropo1));
    w2ui.layoutPropo_<?php echo $idPage;?>.content('main', $().w2form(config.formCommentaire));

    w2ui.layoutPropo1_<?php echo $idPage;?>.content('left', $().w2form(config.formPropo));
    w2ui.layoutPropo1_<?php echo $idPage;?>.content('main', $().w2layout(config.layoutDetail1));
    w2ui.layoutPropo1_<?php echo $idPage;?>.content('bottom', $().w2grid(config.gridISBN));

    w2ui.layoutDetail1_<?php echo $idPage;?>.content('left', $().w2grid(config.gridAuteur));   
    w2ui.layoutDetail1_<?php echo $idPage;?>.content('main', $().w2grid(config.gridPage));
    
    w2ui.layout_<?php echo $idPage;?>.lock('main', "Sélectionner un livre");
    w2ui.layout_<?php echo $idPage;?>.lock('right', "Sélectionner un livre");
    
}

function openPopupAjoutISBN() {
    w2popup.open({
        title   : 'Ajouter un ISBN',
        width   : 600,
        height  : 350,
        showMax : true,
        body    : '<div id="main" style="position: absolute; left: 5px; top: 5px; right: 5px; bottom: 5px;"></div>',
        onOpen  : function (event) {
            event.onComplete = function () {
            	 	if(w2ui['form_<?php echo $idPage;?>_isbn'])w2ui['form_<?php echo $idPage;?>_isbn'].destroy();
                $('#w2ui-popup #main').w2form(config.formISBN)
                w2ui['form_<?php echo $idPage;?>_isbn'].clear();
            };
        },
        onToggle: function (event) { 
            event.onComplete = function () {
                w2ui.layout.resize();
            }
        }
    });
}

function openPopupAjoutPrix() {
    w2popup.open({
        title   : 'Ajouter un prix',
        width   : 400,
        height  : 300,
        showMax : true,
        body    : '<div id="main" style="position: absolute; left: 5px; top: 5px; right: 5px; bottom: 5px;"></div>',
        onOpen  : function (event) {
            event.onComplete = function () {
            	 	if(w2ui['form_<?php echo $idPage;?>_prix'])w2ui['form_<?php echo $idPage;?>_prix'].destroy();
    		        rsIsbnLivre = arrListes['isbn'].filter(function(p){return p.id_livre==itemSelect.recid});
    		        config.formPrix.fields[1].options.items = rsIsbnLivre;
                $('#w2ui-popup #main').w2form(config.formPrix)
                w2ui['form_<?php echo $idPage;?>_prix'].refresh();
                w2ui['form_<?php echo $idPage;?>_prix'].clear();
            };
        },
        onToggle: function (event) { 
            event.onComplete = function () {
                w2ui.layout.resize();
            }
        }
    });
}

function openPopupAjoutTache() {
    w2popup.open({
        title   : 'Ajouter une tâche',
        width   : 400,
        height  : 140,
        showMax : true,
        body    : '<div id="main" style="position: absolute; left: 5px; top: 5px; right: 5px; bottom: 5px;"></div>',
        onOpen  : function (event) {
            event.onComplete = function () {
            	 	if(w2ui['form_<?php echo $idPage;?>_tache'])w2ui['form_<?php echo $idPage;?>_tache'].destroy();
                $('#w2ui-popup #main').w2form(config.formTache)
                w2ui['form_<?php echo $idPage;?>_tache'].clear();
            };
        },
        onToggle: function (event) { 
            event.onComplete = function () {
                w2ui.layout.resize();
            }
        }
    });
}
function openPopupAjoutPage() {
    w2popup.open({
        title   : 'Ajouter un nombre de page',
        width   : 400,
        height  : 200,
        showMax : true,
        body    : '<div id="main" style="position: absolute; left: 5px; top: 5px; right: 5px; bottom: 5px;"></div>',
        onOpen  : function (event) {
            event.onComplete = function () {
            	 	if(w2ui['form_<?php echo $idPage;?>_page'])w2ui['form_<?php echo $idPage;?>_page'].destroy();
                $('#w2ui-popup #main').w2form(config.formPage)
                w2ui['form_<?php echo $idPage;?>_page'].clear();
            };
        },
        onToggle: function (event) { 
            event.onComplete = function () {
                w2ui.layout.resize();
            }
        }
    });
}

function openPopupAjoutAuteur(){
    w2popup.open({
        title   : 'Ajouter un auteur',
        width   : 400,
        height  : 200,
        showMax : true,
        body    : '<div id="main" style="position: absolute; left: 5px; top: 5px; right: 5px; bottom: 5px;"></div>',
        onOpen  : function (event) {
            event.onComplete = function () {
            	 	if(w2ui['form_<?php echo $idPage;?>_auteur'])w2ui['form_<?php echo $idPage;?>_auteur'].destroy();
                $('#w2ui-popup #main').w2form(config.formAuteur)
                w2ui['form_<?php echo $idPage;?>_auteur'].clear();
            };
        },
        onToggle: function (event) { 
            event.onComplete = function () {
                w2ui.layout.resize();
            }
        }
    });
	
}


function showDataLivre(){
    var g;
    //gestion de la proposition
	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/livredata',
		{id:itemSelect.recid, obj:'proposition'},
    		function(js){
    			//mise à jour du formulaire
            g = w2ui['form_<?php echo $idPage;?>_propo'];
            g.clear();
			g.record = js.rs[0];
			g.refresh();		            			
            g = w2ui['form_<?php echo $idPage;?>_commentaire'];
            g.clear();
			g.record = {recid:js.rs[0]['id_proposition'],commentaire:js.rs[0]['commentaire']};
			g.refresh();		            			

		},"json"); 
	/*gestion des collections
    	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/livredata',
			{id:itemSelect.recid, obj:'livrexcollection'},
        		function(js){
	            g = w2ui['grid_<?php echo $idPage;?>_collection'];
	            g.clear();
				g.add(js.rs);								
       		},"json");
    */
    //gestion des comite
    	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/livredata',
			{id:itemSelect.recid, obj:'comitexlivre'},
        		function(js){
	            g = w2ui['grid_<?php echo $idPage;?>_comite'];
	            g.clear();
				g.add(js.rs);
       		},"json");
    //gestion des série
    	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/livredata',
			{id:itemSelect.recid, obj:'livrexserie'},
        		function(js){
	            g = w2ui['grid_<?php echo $idPage;?>_serie'];
	            g.clear();
				g.add(js.rs);
       		},"json");	           		           
	//gestion des isbn
    	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/livredata',
			{id:itemSelect.recid, obj:'isbn'},
        		function(js){
	            g = w2ui['grid_<?php echo $idPage;?>_isbn'];
	            g.clear();
				g.add(js.rs);
       		},"json");	           		           
	//gestion des auteurs
    	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/livredata',
			{id:itemSelect.recid, obj:'livrexauteur'},
        		function(js){
	            g = w2ui['grid_<?php echo $idPage;?>_auteur'];
	            g.clear();
				g.add(js.rs);
				//libère les panels
			    w2ui.layout_<?php echo $idPage;?>.unlock('main');
			    w2ui.layout_<?php echo $idPage;?>.unlock('right');
				
       		},"json");
    //récupère le planning du livre
    $.get('<?php if(!$this->ajax) echo '../'; ?>processus/getprocess',
		{id:itemSelect.id_livre, process:'Production livre'},
    		function(js){
            var gPL = w2ui['grid_<?php echo $idPage;?>_process_livre'];
            gPL.clear();
    			if(js.rs.length){
        			//mise à jour de la grille processus			        
	            idPLU = js.rs[0].id_plu;
	            gPL.add(js.rs);
    			}
	},"json");		           			           		           
    //récupère les pages du livre
    $.get('<?php if(!$this->ajax) echo '../'; ?>crud/livredata',
		{id:itemSelect.id_livre, obj:'page'},
    		function(js){
            var gP = w2ui['grid_<?php echo $idPage;?>_page'];
            gP.clear();
    			if(js.rs.length){
	            gP.add(js.rs);
    			}
	},"json");		
    //récupère les prix du livre
    $.get('<?php if(!$this->ajax) echo '../'; ?>crud/livredata',
		{id:itemSelect.id_livre, obj:'prix'},
    		function(js){
            var gPr = w2ui['grid_<?php echo $idPage;?>_prix'];
            gPr.clear();
    			if(js.rs.length){
	            gPr.add(js.rs);
    			}
	},"json");		
	
}

</script>

<?php 
if(!$this->ajax){
	echo '</body>
</html>';
}else{
	echo '<script type="text/javascript">
			$(function () {initLivre(); });                       		
		</script>		
		';	
}

?>