<?php 
if(!$this->ajax){
	$inc = 0;
	echo '<!DOCTYPE html>
<html>
	<head>
		<title>ISTE - Production des livres</title>
		<link rel="stylesheet" type="text/css" href="../css/gestedit.css" />
		<link rel="stylesheet" type="text/css" href="../css/w2ui.css" />
		<link rel="stylesheet" type="text/css" href="../fonts/font-awesome/font-awesome.css" />
		<script type="text/javascript">
			var urlP = "../";
			var uti = '.$this->uti.';
			var fctInit;			
		</script>		
		<script type="text/javascript" src="../js/jquery.min.js"></script>
		<script type="text/javascript" src="../js/w2ui.js"></script>
		<script type="text/javascript" src="../js/global.js"></script>
		<script type="text/javascript" src="../js/data.js"></script>
		<script type="text/javascript" src="../js/log.js"></script>
		<script type="text/javascript" src="../js/ckeditor/ckeditor.js"></script>
		<script type="text/javascript">
			$(function () {
				initAll(initProd); 
	  			if(uti.id_uti!=0)
					utiIsConnect();
			});                       		
		</script>		
		</head>
<body>
';
}else{
	$inc = 1;
	echo '<script type="text/javascript" src="js/ckeditor/ckeditor.js"></script>';	
}
$idPage = "ProdLivre";
?>

<div id="<?php echo $idPage;?>" style="width: 100%; height: 1000px;"></div>

<script type="text/javascript">
var rs = <?php echo $this->json; ?>;

//widget configuration
var pstyle = 'border: 1px solid #dfdfdf; padding: 5px;';
var pstyleDetail = 'background-color: #F0F0C1; border: 1px solid #dfdfdf; padding: 5px;';
var config;

function initProd() {

	config = {
		    layoutProduction: {
		        name: 'layout_<?php echo $idPage;?>',
		        padding: 4,
		        panels: [
		 		    { type: 'top', size: "50%", style: pstyle},
					{ type: 'main', size: '50%', resizable: true, style: pstyleDetail},
		            { type: 'right', size: '710px', hidden:false, resizable: true, style: pstyleDetail
			    		    ,tabs: {
			    		        name: 'tabs_<?php echo $idPage;?>_prod',
			    		        active: 'tab',
			    		        tabs: [{ id: 'tab', caption: "Commentaires" },{ id: 'tab0', caption: "Description" }
			    		        		,{ id: 'tab1', caption: 'Table des matières' },{ id: 'tab2', caption: 'Biographies' }
			    		        		,{ id: 'tab3', caption: 'Fichiers joints' },{ id: 'tab4', caption: 'Web' }],
			    		        onClick: function (event) {
				    		        	for(name in CKEDITOR.instances)
				    		        	{
				    		        	    CKEDITOR.instances[name].destroy(true);
				    		        	}				    		        
			    			        if(event.target=="tab"){
			    			        		w2ui['form_<?php echo $idPage;?>_commentaire'].destroy();
			    			            w2ui.layout_<?php echo $idPage;?>.content('right', $().w2form(config.formProdCommentaire));				    			            
							        updateFormTab("commentaire");
		    			        		}else if(event.target=="tab0"){
			    			        		if(w2ui['form_<?php echo $idPage;?>_contexte'])w2ui['form_<?php echo $idPage;?>_contexte'].destroy();
			    			            w2ui.layout_<?php echo $idPage;?>.content('right', $().w2form(config.formProdContexte));				    			            
							        updateFormTab("contexte");
			    			        }else if(event.target=="tab1"){
			    			            if(w2ui['form_<?php echo $idPage;?>_tdm'])w2ui['form_<?php echo $idPage;?>_tdm'].destroy();
			    			            w2ui.layout_<?php echo $idPage;?>.content('right', $().w2form(config.formProdTdM));						        	
									updateFormTab("tdm");
			    			        }else if(event.target=="tab2"){
			    			            if(w2ui['form_<?php echo $idPage;?>_bio'])w2ui['form_<?php echo $idPage;?>_bio'].destroy();
			    			            w2ui.layout_<?php echo $idPage;?>.content('right', $().w2form(config.formProdBio));
			    			            updateFormTab("bio");
			    			        }else if(event.target=="tab4"){
			    			            if(w2ui['layout_<?php echo $idPage;?>_web']){
				    			            w2ui['layout_<?php echo $idPage;?>_web'].destroy();
				    			            w2ui['grid_<?php echo $idPage;?>_web'].destroy();
			    			            }
			    			            w2ui.layout_<?php echo $idPage;?>.content('right', $().w2layout(config.layoutProdWeb));
			    			            w2ui.layout_<?php echo $idPage;?>_web.content('left', $().w2grid(config.gridProdWeb));
			    			            w2ui.layout_<?php echo $idPage;?>_web.content('main', "<iframe id='ifWeb' src=''  width='100%'height='100%'></iframe>");
			    			            
			    			            updateFormTab("web");
			    			        }else{
			    			            if(w2ui['layout_<?php echo $idPage;?>_fic'])w2ui['layout_<?php echo $idPage;?>_fic'].destroy();
			    			            w2ui.layout_<?php echo $idPage;?>.content('right', $().w2layout(config.layoutProdFic));
			    			            w2ui.layout_<?php echo $idPage;?>_fic.load('main', urlP+'import?typeObj=livre&idObj='+itemSelect.id_livre+'&ajax=1&inc=<?php echo $inc;?>')
			    			        }
			    		        },
			    		    },		    
			    		},
		        ]
		    },
		    layoutProcessLivre : {
		        name: 'layout_<?php echo $idPage;?>_process_livre',
		        panels: [
		 			{ type: 'top', size: '110px', style: pstyleDetail, resizable: true },
		            	{ type: 'main', size: '50%', style: pstyleDetail, resizable: true },
		            	{ type: 'right', size: '50%', style: pstyleDetail, resizable: true },
		        ]
		    },
		    gridProduction: { 
		        name: 'grid_<?php echo $idPage;?>', 
				header: 'Livres en production',		
		        show: { 
					header			: true,		
		            toolbar			: true,
					toolbarReload   : true,
					toolbarColumns  : true,
		            	toolbarSearch   : true,
		            	toolbarAdd      : false,
		            	toolbarDelete   : false,
		            	toolbarSave		: false,
		            	footer: true,
		        },
		        columns: [         
		            { field: 'recid', caption: 'ID ISBN', size: '50px', hidden:false, sortable: true, resizable: true },
		            { field: 'id_livre', caption: 'ID livre', size: '50px', hidden:false, sortable: true, resizable: true },
		            { field: 'date_parution', caption: 'Parution', size: '80px', sortable: true, resizable: true},
		            { field: 'auteurs', caption: 'Auteurs', size: '10%', sortable: true, resizable: true},
		            { field: 'titre_fr', caption: 'Titre FR', size: '130px', sortable: true, resizable: true},
		            { field: 'soustitre_fr', caption: 'Sous titre FR', size: '100px', sortable: true, resizable: true},
		            { field: 'titre_en', caption: 'Titre EN', size: '130px', sortable: true, resizable: true},
		            { field: 'soustitre_en', caption: 'Sous titre EN', size: '100px', sortable: true, resizable: true},
		            { field: 'isbn', caption: 'ISBN', size: '60px', sortable: true, resizable: true},
		            { field: 'editeur', caption: 'Editeur', size: '80px', sortable: true, resizable: true},
		            { field: 'type_2', caption: 'Type', size: '60px', sortable: true, resizable: true},		            		            
		            { field: 'nb_page', caption: 'Nb. page', size: '60px', sortable: true, resizable: true},		            
		            { field: 'langue', caption: 'Langue', size: '120px', sortable: true, resizable: true},		            
		            { field: 'traduction', caption: 'Traduction', size: '120px', sortable: true, resizable: true},		            
		        ],
		        toolbar: {
		            items: [
		            ],
		            onClick: function (event) {
		                if (event.target == 'export') {
		                		open(urlP+'export?obj=production',"_blank")
		                }
		            }
		        },
		        records: rs,
		        onClick: function (event) {
					if(itemSelect && itemSelect.recid == event.recid) return;
		            itemSelect = this.get(event.recid);
			        showDataProdLivre();        		                    		           
		        }	    
		    },
		    gridProcessLivreResp: { 
		        name: 'grid_<?php echo $idPage;?>_process_livre_resp',
		        header: 'Responsable de la production',		
				show: {toolbar		: true,
	    				toolbarReload   : false,
	    				toolbarColumns  : false,
	                	toolbarSearch   : false,
	                	toolbarAdd      : false,
	                	toolbarDelete   : false,
	                	toolbarSave		: true,
	                	header			: false, 
	                	columnHeaders	: true},
		        columns: [      		  		           
		            { field: 'recid', caption: 'ID', size: '50px', hidden:true, sortable: true, resizable: true },
			        { field: 'id_uti', caption: 'Responsable de la production', size: '100%', sortable: true, resizable: true, 
		            	editable: { type: 'select', items: arrListes['uti'] }, 
		                render: function (record, index, col_index) {
		                    var html = '';
		                    for (var p in arrListes['uti']) {
		                        if (arrListes['uti'][p].id == this.getCellValue(index, col_index)) html = arrListes['uti'][p].text;
		                    }
		                    return html;
		                }},		            
		        ],
		        onSave: function(event) {
		            var changes = w2ui['grid_<?php echo $idPage;?>_process_livre_resp'].getChanges();
		            changes.forEach(function(c, i){
			            c.obj = 'processusxlivre';
			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
			        			c,
			        			function(js){
			            			finsession(js);
			        				if(changes.length==i+1)w2alert(js.message);
			        			},"json");                        
		            });
		        }
		    },		    		    
		    gridProcessLivreFR: { 
		        name: 'grid_<?php echo $idPage;?>_process_livreFR', 
				header: 'Planning production FR',		
				show: {toolbar		: true,
	    				toolbarReload   : false,
	    				toolbarColumns  : false,
	                	toolbarSearch   : false,
	                	toolbarAdd      : false,
	                	toolbarDelete   : false,
	                	toolbarSave		: true,
	                	header			: true, 
	                	columnHeaders	: true},
		        columns: [      		  		           
		            { field: 'recid', caption: 'ID', size: '50px', hidden:true, sortable: true, resizable: true },
		            { field: 'tache', caption: 'Tâche', size: '175px', sortable: true, resizable: true},
		            { field: 'debut', caption: 'Origine', editable: { type: 'date'}, size: '80px', sortable: true, resizable: true},
		            { field: 'prevision', caption: 'Prévision', editable: { type: 'date'}, size: '80px', sortable: true, resizable: true},
		            { field: 'relance', caption: 'Der. relance', editable: { type: 'date'}, size: '80px', sortable: true, resizable: true},
		            { field: 'alerte', caption: 'Date alerte', editable: { type: 'date'}, size: '80px', sortable: true, resizable: true},
		            { field: 'fin', caption: 'Fin', editable: { type: 'date'}, size: '80px', sortable: true, resizable: true},
		            { field: 'commentaire', caption: 'Commentaires', editable: { type: 'text'}, size: '200px', sortable: true, resizable: true},
		        ],
		        onClick: function (event) {
		        },
		        onSave: function(event) {
		            var changes = w2ui['grid_<?php echo $idPage;?>_process_livreFR'].getChanges();
		            changes.forEach(function(c, i){
			            c.obj = 'prevision';
			            if(c.debut) c.debut = w2utils.formatDate(c.debut, 'yyyy-mm-dd');
			            if(c.prevision) c.prevision = w2utils.formatDate(c.prevision, 'yyyy-mm-dd');
			            if(c.fin) c.fin = w2utils.formatDate(c.fin, 'yyyy-mm-dd');
			            if(c.alerte) c.alerte = w2utils.formatDate(c.alerte, 'yyyy-mm-dd');
			            if(c.relance) c.relance = w2utils.formatDate(c.relance, 'yyyy-mm-dd');
				        	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
			        			c,
			        			function(js){
			            			finsession(js);
			        				if(c.debut)
						        		w2ui['grid_<?php echo $idPage;?>_process_livreFR'].set(c.recid, js.rs);
			        				if(changes.length==i+1)w2alert(js.message);
			        			},"json");                        
		            });
		        },
		    },	
		    gridProcessLivreGB: { 
		        name: 'grid_<?php echo $idPage;?>_process_livreGB', 
				header: 'Planning production GB',		
				show: {toolbar		: true,
	    				toolbarReload   : false,
	    				toolbarColumns  : false,
	                	toolbarSearch   : false,
	                	toolbarAdd      : false,
	                	toolbarDelete   : false,
	                	toolbarSave		: true,
	                	header			: true, 
	                	columnHeaders	: true},
		        columns: [      		  		           
		            { field: 'recid', caption: 'ID', size: '50px', hidden:true, sortable: true, resizable: true },
		            { field: 'tache', caption: 'Tâche', size: '175px', sortable: true, resizable: true},
		            { field: 'debut', caption: 'Origine', editable: { type: 'date'}, size: '80px', sortable: true, resizable: true},
		            { field: 'prevision', caption: 'Prévision', editable: { type: 'date'}, size: '80px', sortable: true, resizable: true},
		            { field: 'relance', caption: 'Der. relance', editable: { type: 'date'}, size: '80px', sortable: true, resizable: true},
		            { field: 'alerte', caption: 'Date alerte', editable: { type: 'date'}, size: '80px', sortable: true, resizable: true},
		            { field: 'fin', caption: 'Fin', editable: { type: 'date'}, size: '80px', sortable: true, resizable: true},
		            { field: 'commentaire', caption: 'Commentaires', editable: { type: 'text'}, size: '200px', sortable: true, resizable: true},
		        ],
		        onClick: function (event) {
		        },
		        onSave: function(event) {
		            var changes = w2ui['grid_<?php echo $idPage;?>_process_livreGB'].getChanges();
		            changes.forEach(function(c, i){
			            c.obj = 'prevision';
			            if(c.debut) c.debut = w2utils.formatDate(c.debut, 'yyyy-mm-dd');
			            if(c.prevision) c.prevision = w2utils.formatDate(c.prevision, 'yyyy-mm-dd');
			            if(c.fin) c.fin = w2utils.formatDate(c.fin, 'yyyy-mm-dd');
			            if(c.alerte) c.alerte = w2utils.formatDate(c.alerte, 'yyyy-mm-dd');
			            if(c.relance) c.relance = w2utils.formatDate(c.relance, 'yyyy-mm-dd');
				        	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
			        			c,
			        			function(js){
			            			finsession(js);
			        				if(c.debut)
						        		w2ui['grid_<?php echo $idPage;?>_process_livreGB'].set(c.recid, js.rs);
			        				if(changes.length==i+1)w2alert(js.message);
			        			},"json");                        
		            });
		        },
		    },		    	    	    		    		    	    		    
		    formProdCommentaire: { 
		        name: 'form_<?php echo $idPage;?>_commentaire',
		        fields: [
				    { name: 'recid', type:'int', required:true, hidden:true },
		            { name: 'commentaire', type: 'textarea', required: false, html: { caption: 'Commentaires', attr: 'style="margin-left:0px;width: 100%; height: 360px; resize: none"'} },
		        ],
		        actions: {
		            Save: function () {
		                var errors = this.validate();
		                if (errors.length > 0) return;
		                var data = this.record;
		                data.obj = "livre";
			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
							data,
			            		function(js){
			            			finsession(js);
			            			//met à jour les données de base
			            			itemSelect['commentaire']=data.commentaire;
			            			//affiche le résultat
					            w2alert(js.message);
			           		},"json");
		            }
		        }
		    },
		    formProdContexte: { 
		        name: 'form_<?php echo $idPage;?>_contexte',
		        fields: [
				    { name: 'recid', type:'int', required:true, hidden:true },
		            { name: 'contexte_fr', type: 'textarea', required: false, html: { caption: 'Description français', attr: 'rows="10" cols="80" style="width: 100%; height: 180px; resize: none"'} },
		            { name: 'contexte_en', type: 'textarea', required: false, html: { caption: 'Description anglais', attr: 'rows="10" cols="80" style="width: 100%; height: 180px; resize: none"'} },		 		        
		        ],
		        actions: {
		            Save: function () {
		                var errors = this.validate();
		                if (errors.length > 0) return;
		                var data = this.record;
		                data.contexte_fr = CKEDITOR.instances["contexte_fr"].getData();		                
		                data.contexte_en = CKEDITOR.instances["contexte_en"].getData();		                
		                data.obj = "livre";
			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
							data,
			            		function(js){
			            			finsession(js);
			            			//met à jour les données de base
			            			itemSelect['contexte_fr']=data.contexte_fr;
			            			itemSelect['contexte_en']=data.contexte_en;
			            			//affiche le résultat
					            w2alert(js.message);
			           		},"json");
		            }
		        }
		    },
	    		formProdTdM: { 
		        name: 'form_<?php echo $idPage;?>_tdm',
		        fields: [
				    { name: 'recid', type:'int', required:true, hidden:true },
		            { name: 'tdm_fr', type: 'textarea', required: false, html: { caption: 'TdM français', attr: 'style="width: 100%; height: 180px; resize: none"'} },
		            { name: 'tdm_en', type: 'textarea', required: false, html: { caption: 'TdM anglais', attr: 'style="width: 100%; height: 180px; resize: none"'} },		 		        
		        ],
		        actions: {
		            Save: function () {
		                var errors = this.validate();
		                if (errors.length > 0) return;
		                var data = this.record;
		                data.tdm_fr = CKEDITOR.instances["tdm_fr"].getData();		                
		                data.tdm_en = CKEDITOR.instances["tdm_en"].getData();		                
		                data.obj = "livre";
			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
							data,
			            		function(js){
			            			finsession(js);
			            			//met à jour les données de base
			            			itemSelect['tdm_fr']=data.tdm_fr;
			            			itemSelect['tdm_en']=data.tdm_en;
			            			//affiche le résultat
					            w2alert(js.message);
			           		},"json");
		            }
		        }
		    },
		    formProdBio: { 
		        name: 'form_<?php echo $idPage;?>_bio',
		        fields: [
				    { name: 'recid', type:'int', required:true, hidden:true },
		            { name: 'bio_fr', type: 'textarea', required: false, html: { caption: 'Biographies français', attr: 'style="width: 100%; height: 180px; resize: none"'} },
		            { name: 'bio_en', type: 'textarea', required: false, html: { caption: 'Biographies anglais', attr: 'style="width: 100%; height: 180px; resize: none"'} },		 		        
		        ],
		        actions: {
		            Save: function () {
		                var errors = this.validate();
		                if (errors.length > 0) return;
		                var data = this.record;
		                data.obj = "livre";
		                data.bio_fr = CKEDITOR.instances["bio_fr"].getData();		                
		                data.bio_en = CKEDITOR.instances["bio_en"].getData();		                		                
			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
							data,
			            		function(js){
			            			finsession(js);
			            			//met à jour les données de base
			            			itemSelect['bio_fr']=data.bio_fr;
			            			itemSelect['bio_en']=data.bio_en;
			            			//affiche le résultat
					            w2alert(js.message);
			           		},"json");
		            }
		        },
		    },
		    layoutProdFic: {
		        name: 'layout_<?php echo $idPage;?>_fic',
		        padding: 4,
		        panels: [
				    { type: 'left', size: "200px", hidden:true, resizable: true, style: pstyleDetail},
					{ type: 'main', size: "100%", resizable: true, style: pstyleDetail},
		        ],
		    },		        
		    sbProdFic: {
		        name: 'sb_<?php echo $idPage;?>_fic',
		        nodes: [ 
		            { id: 'general', text: 'Liste des fichiers', group: true, expanded: true, nodes: [
		                { id: 'grid1', text: ' Couverture française', img: 'icon-cover', selected: true },
		                { id: 'grid2', text: 'Couverture anglaise', img: 'icon-cover' },
		                { id: 'html', text: 'Some HTML', img: 'icon-page' }
		            ]}
		        ],
		        onClick: function (event) {
		            switch (event.target) {
		                case 'grid1':
		                    w2ui.layout.content('main', w2ui.grid1);
		                    break;
		                case 'grid2':
		                    w2ui.layout.content('main', w2ui.grid2);
		                    break;
		                case 'html':
		                    w2ui.layout.content('main', '<div style="padding: 10px">Some HTML</div>');
		                    $(w2ui.layout.el('main'))
		                        .removeClass('w2ui-grid')
		                        .css({ 
		                            'border-left': '1px solid silver'
		                        });
		                    break;
		            }
		        }
		    },
		    formProdFic: { 
		        name: 'form_<?php echo $idPage;?>_fic',
		        fields: [
				    { name: 'recid', type:'int', required:true, hidden:true },
		            { name: 'file', type: 'file', required: false, html: { caption: 'Fichier', attr: 'style="width: 100%;"'} },
		        ],
		        actions: {
		            Save: function () {
		                var errors = this.validate();
		                if (errors.length > 0) return;
		                var data = this.record;
		                data.obj = "livre";
		                this.clear();		                
			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
							data,
			            		function(js){
			            			finsession(js);
			            			//met à jour les données de base
			            			itemSelect['bio_fr']=data.bio_fr;
			            			itemSelect['bio_en']=data.bio_en;
			            			//affiche le résultat
					            w2alert(js.message);
			           		},"json");
		            }
		        }
		    },	
		    layoutProdWeb: {
		        name: 'layout_<?php echo $idPage;?>_web',
		        padding: 2,
		        panels: [
				    { type: 'left', size: "400px", resizable: true, style: pstyleDetail},
					{ type: 'main', size: "100%", resizable: true, style: pstyleDetail},
		        ],
		    },		        		    
		    gridProdWeb: { 
		        name: 'grid_<?php echo $idPage;?>_web', 
				header: 'Pages Web liées au livre',		
				show: {toolbar		: true,
	    				toolbarReload   : false,
	    				toolbarColumns  : true,
	                	toolbarSearch   : false,
	                	toolbarAdd      : true,
	                	toolbarDelete   : true,
	                	toolbarSave		: true,
	                	header			: true, 
	                	columnHeaders	: true},
		        columns: [      		  		           
		            { field: 'recid', caption: 'ID', size: '50px', hidden:true, sortable: true, resizable: true },
		            { field: 'id_livre', caption: 'id_livre', size: '50px', hidden:true, sortable: true, resizable: true },
		            { field: 'type', caption: 'Type de lien', size: '120px', sortable: true, resizable: true, 
		            		editable: { type: 'list', items: arrListes['typeLien'], showAll: true },
			                render: function (record, index, col_index) {
			                    var html = this.getCellValue(index, col_index);
			                    return html.text ? html.text : html;
			                }},
		            { field: 'url', caption: 'Url', editable: { type: 'url'}, size: '20%', sortable: true, resizable: true},
		        ],
		        onClick: function (event) {
		            var iWeb = this.get(event.recid);
		            if(w2ui['layout_<?php echo $idPage;?>_web']){
			            document.getElementById('ifWeb').setAttribute('src',iWeb.url);
		            }
		        },	    		        
		        toolbar: {
		            items: [
		                { id: 'setLiens', type: 'button', caption: 'Calculer les liens', icon: 'fa-link' },
		            ],
		            onClick: function (event) {
		                if (event.target == 'setLiens') {
			                
		                }		                
		            }
		        },		        
		        onSave: function(event) {
		            var changes = w2ui['grid_<?php echo $idPage;?>_web'].getChanges();
		            changes.forEach(function(c, i){
			            c.obj = 'web';
			            if(c.type) c.type = c.type.text;
				        	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
			        			c,
			        			function(js){
			            			finsession(js);
			        				if(changes.length==i+1)w2alert(js.message);
			        			},"json");                        
		            });
		        },
    	            onAdd: function(event) {
			        var data = {'obj':"web",'id_livre':itemSelect["id_livre"],"type":'aucun',"url":'changer'};
		            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/insert',
						data,
		            		function(js){
		            			finsession(js);
		            			if(js.rs){
				                var g = w2ui['grid_<?php echo $idPage;?>_web'];
								g.add(js.rs);
								g.selectNone();
		            			}
		            			w2alert(js.message);
		           		},"json");
			    },
		        onDelete: function(event) {            
					var p = {'obj':'web'};
					if(event.force){
						var s = w2ui[event.target].getSelection();
						p.id = s[0];
			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/delete',
								p,
				            		function(js){
				            			finsession(js);
				            			w2alert(js.message);
				           		},"json");
					}
			    },	    		        
		    },
		    	    
	};
	
    // initialisation
    $('#<?php echo $idPage;?>').w2layout(config.layoutProduction);
    w2ui.layout_<?php echo $idPage;?>.content('top', $().w2grid(config.gridProduction));
    w2ui.layout_<?php echo $idPage;?>.content('main', $().w2layout(config.layoutProcessLivre)); 
    w2ui.layout_<?php echo $idPage;?>.content('right', $().w2form(config.formProdCommentaire));
       
    w2ui.layout_<?php echo $idPage;?>_process_livre.content('top', $().w2grid(config.gridProcessLivreResp));
    w2ui.layout_<?php echo $idPage;?>_process_livre.content('main', $().w2grid(config.gridProcessLivreFR));
    w2ui.layout_<?php echo $idPage;?>_process_livre.content('right', $().w2grid(config.gridProcessLivreGB));
    
    w2ui.layout_<?php echo $idPage;?>.lock('main', "Sélectionner un livre", true);
    w2ui.layout_<?php echo $idPage;?>.lock('right', "Sélectionner un livre", true);
    
}
function updateFormTab(a){
    var g = w2ui['form_<?php echo $idPage;?>_'+a];
	if(a=="commentaire"){
		g.record[a]=itemSelect[a];
		g.refresh();
	}
	if(a=="web"){
		$.get('<?php if(!$this->ajax) echo '../'; ?>crud/livredata',
				{id:itemSelect.id_livre, obj:'web'},
		    		function(js){
        				finsession(js);
		            document.getElementById('ifWeb').setAttribute('src',"");		    		
		            g = w2ui['grid_<?php echo $idPage;?>_web'];
		            g.clear();
					g.add(js.rs);
		   		},"json");	           		           
		return;		
	}	
	if(CKEDITOR.instances[a+"_fr"])CKEDITOR.instances[a+"_fr"].setData(itemSelect[a+"_fr"]+"");
	if(CKEDITOR.instances[a+"_en"])CKEDITOR.instances[a+"_en"].setData(itemSelect[a+"_en"]+"");
	g.on('render', function(event) {
		event.onComplete = function () {
			if(a!="commentaire"){
				g.record.recid=itemSelect['id_livre'];
				CKEDITOR.replace(a+"_fr");
				CKEDITOR.replace(a+"_en");
				CKEDITOR.instances[a+"_fr"].setData(itemSelect[a+"_fr"]+"");
				CKEDITOR.instances[a+"_en"].setData(itemSelect[a+"_en"]+"");
			}				
	    }		
	});
}

function showDataProdLivre(){
	//récupère le processus de traduction des livres
	w2ui.layout_<?php echo $idPage;?>.unlock('main');
    w2ui.layout_<?php echo $idPage;?>.unlock('right');
    $.get('<?php if(!$this->ajax) echo '../'; ?>processus/getprocess',
		{id:itemSelect.id_livre, process:'Production FR'},
    		function(js){
			finsession(js);
            var g = w2ui['grid_<?php echo $idPage;?>_process_livreFR'];
            g.clear();
          	//mise à jour de la grille responsable			        
            var g1 = w2ui['grid_<?php echo $idPage;?>_process_livre_resp'];
            g1.clear();
    			if(js.rs.length){
        			//mise à jour de la grille processus			        
	            g.add(js.rs);
	            g1.add([{recid:js.rs[0].id_plu, id_uti:js.rs[0].id_uti}]);

	            var a = w2ui['layout_<?php echo $idPage;?>_right_tabs'].active;
	            if(a=="tab") updateFormTab("commentaire");
	            if(a=="tab0") updateFormTab("contexte");
	            if(a=="tab1") updateFormTab("tdm");
	            if(a=="tab2") updateFormTab("bio");
	            if(a=="tab4") updateFormTab("web");
	            if(a=="tab3"){
			            if(w2ui['layout_<?php echo $idPage;?>_fic'])w2ui['layout_<?php echo $idPage;?>_fic'].destroy();
			            w2ui.layout_<?php echo $idPage;?>.content('right', $().w2layout(config.layoutProdFic));
			            w2ui.layout_<?php echo $idPage;?>_fic.load('main', urlP+'import?typeObj=livre&idObj='+itemSelect.id_livre+'&ajax=1&inc=<?php echo $inc;?>')
	            }
            							            
    			}
    },"json");   
    $.get('<?php if(!$this->ajax) echo '../'; ?>processus/getprocess',
    		{id:itemSelect.id_livre, process:'Production GB'},
        	function(js){
	    			finsession(js);
                var g = w2ui['grid_<?php echo $idPage;?>_process_livreGB'];
                g.clear();
        			if(js.rs.length){
            			//mise à jour de la grille processus			        
	    	            g.add(js.rs);
        			}
        },"json");   
    
}

</script>

<?php 
if(!$this->ajax){
	echo '</body>
</html>';
}else{
	echo '<script type="text/javascript">
			$(function () {initProd(); });                       		
		</script>		
		';	
}

?>