<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <script type="text/javascript">
        function printDocument(documentId) {
            var doc = document.getElementById(documentId);

            //Wait until PDF is ready to print    
            if (typeof doc.print === 'undefined') {    
                setTimeout(function(){printDocument(documentId);}, 1000);
            } else {
                doc.print();
            }
        }
        </script>
    </head>
    <body onload="printDocument('pdfDocument')">
		<embed
		    type="application/pdf"
		    src="../test.pdf"
		    id="pdfDocument"
		    width="100%"
		    height="100%">
		</embed>
    </body>
</html>