<div style="float:left;width:176px;">
	<img src="img/logo-iste.png" alt="ISTE Editions - ouvrages scientifiques et techniques en langue française">
</div>
<div id="toolbar" style="padding: 4px; border: 1px solid silver; border-radius: 3px"></div>
<script type="text/javascript">
$(function () {
    $('#toolbar').w2toolbar({
    	    name: 'toolbar',
        items: [
            { type: 'button',  id: 'tbAuteurs', caption: 'Auteurs', icon:'fa-group'},
            { type: 'break',  id: 'break0' },
            { type: 'menu',   id: 'item2', caption: 'Menu', icon: 'fa-table', count: 17, items: [
                { text: 'Item 1', icon: 'fa-camera', count: 5 }, 
                { text: 'Item 2', icon: 'fa-picture', disabled: true }, 
                { text: 'Item 3', icon: 'fa-glass', count: 12 }
            ]},
            { type: 'break', id: 'break1' },
            { type: 'radio',  id: 'item3',  group: '1', caption: 'Radio 1', icon: 'fa-star', checked: true },
            { type: 'radio',  id: 'item4',  group: '1', caption: 'Radio 2', icon: 'fa-heart' },
            { type: 'break', id: 'break2' },
            { type: 'drop',  id: 'item5', caption: 'Drop Down', icon: 'fa-plus', html: '<div style="padding: 10px">Drop down</div>' },
            { type: 'break', id: 'break3' },
            { type: 'html',  id: 'item6',
                html: '<div style="padding: 3px 10px;">'+
                      ' Input:'+
                      '    <input size="10" style="padding: 3px; border-radius: 2px; border: 1px solid silver"/>'+
                      '</div>' 
            },
            { type: 'spacer' },
            { type: 'button',  id: 'item7',  caption: 'Item 5', icon: 'fa-flag' }
        ]
    });
    
    w2ui.toolbar.on('*', function (event) { 
        console.log('EVENT: '+ event.type + ' TARGET: '+ event.target, event);
        if(event.target=="tbAuteurs"){
	        	w2ui['layout'].load('main', 'auteur?ajax=1');
        }
    });
});
</script>