<?php 
if(!$this->ajax){
	echo '<!DOCTYPE html>
<html>
	<head>
		<title>ISTE - Traduction</title>
		<link rel="stylesheet" type="text/css" href="../css/gestedit.css" />
		<link rel="stylesheet" type="text/css" href="../css/w2ui.css" />
		<link rel="stylesheet" type="text/css" href="../fonts/font-awesome/font-awesome.css" />
		<script type="text/javascript">
			var urlP = "../";
			var uti = '.$this->uti.';
			var fctInit;			
		</script>		
		<script type="text/javascript" src="../js/jquery.min.js"></script>
		<script type="text/javascript" src="../js/w2ui.js"></script>
		<script type="text/javascript" src="../js/global.js"></script>
		<script type="text/javascript" src="../js/data.js"></script>
		<script type="text/javascript" src="../js/log.js"></script>
		<script type="text/javascript">
			$(function () {
				initAll(initTraduction); 
	  			if(uti)
					utiIsConnect();
	  			else
		    	  		diagLogin.showModal();				
			});                       		
		</script>		
		</head>
<body>
';
}
$idPage = "Traduction";
?>
<div id="<?php echo $idPage;?>" style="width: 100%; height: 1000px;"></div>

<script type="text/javascript">
var rs = <?php echo $this->json; ?>;
var rsTrad = <?php echo $this->rsTrad; ?>;

//widget configuration
var pstyle = 'border: 1px solid #dfdfdf; padding: 5px;';
var pstyleDetail = 'background-color: #F0F0C1; border: 1px solid #dfdfdf; padding: 5px;';
var config;
var idPLU, idPCU;
function initTraduction() {

	config = {
		    layoutTraduction: {
		        name: 'layout_<?php echo $idPage;?>',
		        padding: 4,
		        panels: [
		 		    { type: 'top', size: "550px", style: pstyle},
					{ type: 'main', size: '50%', resizable: true, style: pstyleDetail},
		            { type: 'left', size: '50%', resizable: true, style: pstyleDetail},
		            { type: 'right', size: '50%', hidden:true, resizable: true, style: pstyleDetail},
		        ]
		    },
		    layoutTradTop: {
		        name: 'layout_<?php echo $idPage;?>_Top',
		        padding: 2,
		        panels: [
					{ type: 'main', size: '70%', resizable: true, style: pstyleDetail},
		            { type: 'right', size: '430px', resizable: true, style: pstyleDetail},
		        ]
		    },
		    layoutTraducteur: {
		        name: 'layout_Traducteur',
		        padding: 2,
		        panels: [
		            { type: 'top', size: '55%', resizable: true, style: pstyleDetail},
					{ type: 'main', size: '45%', resizable: true, style: pstyleDetail},
		        ]
		    },
		    layoutTradLivre : {
		        name: 'layout_<?php echo $idPage;?>_trad_livre',
		        panels: [
		 			{ type: 'top', size: '110px', style: pstyleDetail, resizable: true },
		            	{ type: 'main', size: '200px', style: pstyleDetail, resizable: true },
		        ]
		    },
		    gridTraduction: { 
		        name: 'grid_<?php echo $idPage;?>', 
				header: 'Livres à traduire',		
		        show: { 
					header			: true,		
		            toolbar			: true,
					toolbarReload   : true,
					toolbarColumns  : true,
		            	toolbarSearch   : true,
		            	toolbarAdd      : false,
		            	toolbarDelete   : false,
		            	toolbarSave		: false,
		            	footer: true,
		        },
		        columns: [         
		            { field: 'recid', caption: 'ID', size: '50px', hidden:true, sortable: true, resizable: true },
		            { field: 'date_parution', caption: 'Parution', size: '80px', sortable: true, resizable: true},
		            { field: 'auteurs', caption: 'Auteurs', size: '10%', sortable: true, resizable: true},
		            { field: 'titre_en', caption: 'Titre', size: '130px', sortable: true, resizable: true},
		            { field: 'soustitre_en', caption: 'Sous titre', size: '100px', sortable: true, resizable: true},
		            { field: 'isbn', caption: 'ISBN', size: '60px', sortable: true, resizable: true},
		            { field: 'editeur', caption: 'Editeur', size: '80px', sortable: true, resizable: true},
		            { field: 'type_2', caption: 'Type', size: '60px', sortable: true, resizable: true},		            		            
		            { field: 'nb_page', caption: 'Nb. page', size: '60px', sortable: true, resizable: true},		            
		            { field: 'traduction', caption: 'Traduction', size: '120px', sortable: true, resizable: true},		            
		        ],
		        toolbar: {
		            items: [
		                { id: 'export', type: 'button', caption: 'Exporter', icon: 'fa-file' }
		            ],
		            onClick: function (event) {
		                if (event.target == 'export') {
		                		open(urlP+'export?obj=traduction',"_blank")
		                }
		            }
		        },
		        records: rs,
		        onClick: function (event) {
		            itemSelect = this.get(event.recid);
		            showDataTraduction();
		        }	    
		    },
		    gridTradLivreResp: { 
		        name: 'grid_<?php echo $idPage;?>_trad_livre_resp',
		        header: 'Responsable de la traduction',		
				show: {toolbar		: true,
	    				toolbarReload   : false,
	    				toolbarColumns  : false,
	                	toolbarSearch   : false,
	                	toolbarAdd      : false,
	                	toolbarDelete   : false,
	                	toolbarSave		: true,
	                	header			: false, 
	                	columnHeaders	: true},
		        columns: [      		  		           
		            { field: 'recid', caption: 'ID', size: '50px', hidden:true, sortable: true, resizable: true },
		            { field: 'id_uti', caption: 'Responsable de la traduction', size: '100%', sortable: true, resizable: true,
			            	editable: { type: 'select', items: arrListes['uti'] }, 
		                render: function (record, index, col_index) {
		                    var html = '';
		                    for (var p in arrListes['uti']) {
		                        if (arrListes['uti'][p].id == this.getCellValue(index, col_index)) html = arrListes['uti'][p].text;
		                    }
		                    return html;
		                }}
		        ],
		        onSave: function(event) {
		            var changes = w2ui['grid_<?php echo $idPage;?>_trad_livre_resp'].getChanges();
		            changes.forEach(function(c, i){
			            c.obj = 'processusxlivre';
				        	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
			        			c,
			        			function(html){
			        				if(changes.length==i+1)w2alert(html);
			        			});                        
		            });
		        }
		    },		    		    
		    gridTradLivre: { 
		        name: 'grid_<?php echo $idPage;?>_trad_livre', 
				header: 'Traduction du livre',		
				show: {toolbar		: true,
	    				toolbarReload   : false,
	    				toolbarColumns  : false,
	                	toolbarSearch   : false,
	                	toolbarAdd      : false,
	                	toolbarDelete   : false,
	                	toolbarSave		: true,
	                	header			: true, 
	                	columnHeaders	: true},
		        columns: [      		  		           
		            { field: 'recid', caption: 'ID', size: '50px', hidden:true, sortable: true, resizable: true },
		            { field: 'tache', caption: 'Tâche', size: '118px', sortable: true, resizable: true},
		            { field: 'debut', caption: 'Origine', editable: { type: 'date'}, size: '80px', sortable: true, resizable: true},
		            { field: 'prevision', caption: 'Prévision', editable: { type: 'date'}, size: '80px', sortable: true, resizable: true},
		            { field: 'fin', caption: 'Fin', editable: { type: 'date'}, size: '80px', sortable: true, resizable: true},
		            { field: 'commentaire', caption: 'Commentaires', editable: { type: 'text'}, size: '200px', sortable: true, resizable: true},
		            { field: 'alerte', caption: 'Date alerte', editable: { type: 'date'}, size: '80px', sortable: true, resizable: true}
		        ],
		        onSave: function(event) {
		            var changes = w2ui['grid_<?php echo $idPage;?>_trad_livre'].getChanges();
		            changes.forEach(function(c, i){
			            c.obj = 'prevision';
			            if(c.debut) c.debut = w2utils.formatDate(c.debut, 'yyyy-mm-dd');
			            if(c.prevision) c.prevision = w2utils.formatDate(c.prevision, 'yyyy-mm-dd');
			            if(c.fin) c.fin = w2utils.formatDate(c.fin, 'yyyy-mm-dd');
			            if(c.alerte) c.alerte = w2utils.formatDate(c.alerte, 'yyyy-mm-dd');
				        	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
			        			c,
			        			function(html){
			        				if(changes.length==i+1)w2alert(html);
			        			});                        
		            });
		        }
		    },		    	    		    
		    gridTradChapitre: { 
		        name: 'grid_<?php echo $idPage;?>_trad_chapitre', 
				header: 'Traduction des chapitres',		
				show: {toolbar		: true,
	    				toolbarReload   : false,
	    				toolbarColumns  : false,
	                	toolbarSearch   : false,
	                	toolbarAdd      : true,
	                	toolbarDelete   : false,
	                	toolbarSave		: true,
	                	header			: true, 
	                	columnHeaders	: true},
		        columns: [      		  		           
		            { field: 'recid', caption: 'ID', size: '50px', hidden:true, sortable: true, resizable: true },
		            { field: 'content', caption: 'Content', size: '118px', sortable: true, resizable: true},
		            { field: 'tache1', caption: 'MS received', editable: { type: 'date'}, size: '80px', sortable: true, resizable: true},
		            { field: 'tache2', caption: 'proofs sent to author', editable: { type: 'date'}, size: '80px', sortable: true, resizable: true},
		            { field: 'tache3', caption: 'acknowledged receipt ?', editable: { type: 'date'}, size: '80px', sortable: true, resizable: true},
		            { field: 'tache4', caption: 'proofs returned from author', editable: { type: 'date'}, size: '80px', sortable: true, resizable: true},
		            { field: 'tache5', caption: 'deadline', editable: { type: 'date'}, size: '80px', sortable: true, resizable: true},
		            { field: 'id1', caption: 'id1', hidden:true, size: '80px', sortable: true, resizable: true},
		            { field: 'id2', caption: 'id2', hidden:true, size: '80px', sortable: true, resizable: true},
		            { field: 'id3', caption: 'id3', hidden:true, size: '80px', sortable: true, resizable: true},
		            { field: 'id4', caption: 'id4', hidden:true, size: '80px', sortable: true, resizable: true},
		            { field: 'id5', caption: 'id5', hidden:true, size: '80px', sortable: true, resizable: true},
		            { field: 'commentaire', caption: 'commentaire', editable: { type: 'text'}, size: '120px', sortable: true, resizable: true},
		        ],
		        onSave: function(event) {
					var data={obj:'prevision'};
		            var changes = w2ui['grid_<?php echo $idPage;?>_trad_chapitre'].getChanges();
		            changes.forEach(function(c, i){
		            		var i = w2ui['grid_<?php echo $idPage;?>_trad_chapitre'].get(c.recid);
			            if(c.tache1){
				             data.fin = w2utils.formatDate(c.tache1, 'yyyy-mm-dd');
				             data.recid = i.id1;
			            }
			            if(c.tache2){
				             data.fin = w2utils.formatDate(c.tache2, 'yyyy-mm-dd');
				             data.recid = i.id2;
			            }
			            if(c.tache3){
				             data.fin = w2utils.formatDate(c.tache3, 'yyyy-mm-dd');
				             data.recid = i.id3;
			            }
			            if(c.tache4){
				             data.fin = w2utils.formatDate(c.tache4, 'yyyy-mm-dd');
				             data.recid = i.id4;
			            }
			            if(c.tache5){
				             data.fin = w2utils.formatDate(c.tache5, 'yyyy-mm-dd');
				             data.recid = i.id5;
			            }
				        	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
			        			data,
			        			function(html){
			        				if(changes.length==i+1)w2alert(html);
			        			});                        
		            });
		        },
	            onAdd: function(event) {
		            w2ui['layout_<?php echo $idPage;?>'].hide('main', true);
		            w2ui['layout_<?php echo $idPage;?>'].toggle('right', true);		            
			    },
		    },		    	    		    
	    		formTradChapitre: { 
		        header: 'Ajouter un chapitre à traduire',
		        name: 'form_<?php echo $idPage;?>_trad_chapitre',
		        fields: [
		 		    { name: 'num', type: 'text', required: true, html: { caption: 'N°', attr: 'size="10"' } },
		            { name: 'titre_fr', type: 'text', required: false, html: { caption: 'Titre français', attr: 'style="width: 100%"' } },
		            { name: 'titre_en', type: 'text', required: false, html: { caption: 'Titre anglais', attr: 'style="width: 100%"' } },		 		        
		            { name: 'id_traducteur', required: false, type: 'list', options: { items: arrListes['traducteur'] }
		            		, html: { caption: 'Traducteur', attr: 'size="20"' } 
		            		},
		            { name: 'resume_fr', type: 'textarea', required: false, html: { caption: 'Résumé français', attr: 'style="width: 100%; height: 80px; resize: none"'} },
		            { name: 'resume_en', type: 'textarea', required: false, html: { caption: 'Résumé anglais', attr: 'style="width: 100%; height: 80px; resize: none"'} },		 		        
		        ],
		        actions: {
		            Reset: function () {
			            w2ui['layout_<?php echo $idPage;?>'].toggle('main', true);
			            w2ui['layout_<?php echo $idPage;?>'].hide('right', true);		            
		                this.clear();
		            },
		            Save: function () {
		                var errors = this.validate();
		                if (errors.length > 0) return;
		                var data = this.record;
		                data.id_livre = itemSelect["id_livre"];
		                data.id_uti = uti.id_uti;
		                if(data.id_traducteur) data.id_traducteur = data.id_traducteur.id;
		                data.obj = "processusxchapitre";
		                this.clear();		                
			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/insert',
							data,
			            		function(js){
				                var g = w2ui['grid_<?php echo $idPage;?>_trad_chapitre'];
			            			if(js.rs){					            			
									g.add(js.rs);
									g.selectNone();
			            			}
					            w2ui['layout_<?php echo $idPage;?>'].toggle('main', true);
					            w2ui['layout_<?php echo $idPage;?>'].hide('right', true);		            
					            w2alert(js.message);
			           		},"json");
		            }
		        }
		    },
		    gridTraducteur: { 
		        name: 'grid_<?php echo $idPage;?>_traducteur', 
				header: 'Traducteur',		
				show: {toolbar		: true,
	    				toolbarReload   : false,
	    				toolbarColumns  : false,
	                	toolbarSearch   : false,
	                	toolbarAdd      : true,
	                	toolbarDelete   : false,
	                	toolbarSave		: true,
	                	header			: true, 
	                	columnHeaders	: true},
				records: rsTrad,
	    		    columns: [      		  		           
			            { field: 'recid', caption: 'ID', size: '50px', hidden:true, sortable: true, resizable: true },
			            { field: 'civilite', caption: 'Civilité', size: '80px', sortable: true, resizable: true},
			            { field: 'nom', caption: 'Nom', size: '40%', sortable: true, resizable: true},
			            { field: 'prenom', caption: 'Prenom', size: '40%', sortable: true, resizable: true},
		            ],
	            onAdd: function(event) {
		            w2ui['layout_Traducteur'].hide('top', true);
		            w2ui['form_<?php echo $idPage;?>_traducteur'].header = "Ajout d'un traducteur";
		            
			    },
			    onClick: function (event) {
		            var tradSelect = this.get(event.recid);
			        //gestion des détails
		            var g = w2ui['form_<?php echo $idPage;?>_traducteur'];
		            g.clear();
					g.record = tradSelect;
					g.refresh();
			    }		            			
		    },		    	    		    
	    		formTraducteur: { 
		        header: "Détails traducteur",
		        name: 'form_<?php echo $idPage;?>_traducteur',
		        fields: [
				        { name: 'recid', type: 'int', required: false, hidden:true},
			            { name: 'civilite', type: 'list'
		            			, options: { items: arrListes['civilites'] }
		        				, html: { caption: 'Civilité', attr: 'size="10"' }
		           		},
			            { name: 'prenom', type: 'text', required: false, html: { caption: 'Prénom', attr: 'size="40" maxlength="40"' } },
			            { name: 'nom', type: 'text', required: false, html: { caption: 'Nom', attr: 'size="40"' } },
			            { name: 'telephone', type: 'text', html: { caption: 'Téléphone', attr: 'size="30"' } },
			            { name: 'mail', type: 'email', html: { caption: 'E-mail', attr: 'size="30"' } },
			            { name: 'adresse', type: 'text', html: { caption: 'Adresse', attr: 'size="40"' } },
			            { name: 'code_postal', type: 'text', html: { caption: 'Code Postal', attr: 'size="10"' } },
			            { name: 'ville', type: 'text', html: { caption: 'Ville', attr: 'size="40"' } },
			            { name: 'pays', type: 'text', html: { caption: 'Pays', attr: 'size="30"' } },
			            { name: 'background', type: 'textarea', html: { caption: 'background', attr: 'style="width: 100%; height: 100px; resize: none"' } },
			            { name: 'nationalite', type: 'text', html: { caption: 'nationalité', attr: 'size="30"' } },
			            { name: 'word', type: 'checkbox', html: { caption: 'Word'} },
			            { name: 'latex', type: 'checkbox', html: { caption: 'Latex'} },
			            { name: 'mac', type: 'checkbox', html: { caption: 'Mac' } },
			            { name: 'traduction', type: 'text', html: { caption: 'Traduction', attr: 'size="40"' } },
		        ],
		        actions: {
		            Reset: function () {
		                this.clear();
		                if(this.header=="Ajout d'un traducteur"){
		    		            w2ui['layout_Traducteur'].toggle('top', true);		            
		    		            w2ui['form_<?php echo $idPage;?>_traducteur'].header = "Détails traducteur";
		                }
		            },
		            Save: function () {
		                var errors = this.validate();
		                if (errors.length > 0) return;
		                var data = this.record;
		                data.obj = "traducteur";
		                if(data.civilite.id)data.civilite=data.civilite.id;			                
		                var g = w2ui['grid_<?php echo $idPage;?>_traducteur'];
		                
		                if(this.header=="Détails traducteur"){
			                	if(!data.recid){
					            w2alert("Aucun traducteur sélectionné.");
					            return;
			                	}
			                	delete data.expanded;
			                	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
								data,
				            		function(mess){
				                		g.set(data.recid, data);
						            w2alert(mess);
				           		});
		                }else{
			                	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/insert',
								data,
				            		function(js){
				            			if(js.rs){					            			
										g.add(js.rs);
							        		selectRowInGrid(js.rs[0]["recid"],'grid_<?php echo $idPage;?>_traducteur');
				            			}
				    		            w2ui['layout_Traducteur'].toggle('top', true);		            
				    		            w2ui['form_<?php echo $idPage;?>_traducteur'].header = "Détails traducteur";
						            w2alert(js.message);
				           		},"json");
		                }
		            }
		        }
		    },
		    
		};
	
    // initialisation
    $('#<?php echo $idPage;?>').w2layout(config.layoutTraduction);
    w2ui.layout_<?php echo $idPage;?>.content('top', $().w2layout(config.layoutTradTop));
    w2ui.layout_<?php echo $idPage;?>.content('left', $().w2layout(config.layoutTradLivre)); 
    w2ui.layout_<?php echo $idPage;?>.content('main', $().w2grid(config.gridTradChapitre)); 
    w2ui.layout_<?php echo $idPage;?>.content('right', $().w2form(config.formTradChapitre));

    w2ui.layout_<?php echo $idPage;?>_Top.content('main', $().w2grid(config.gridTraduction));
    w2ui.layout_<?php echo $idPage;?>_Top.content('right', $().w2layout(config.layoutTraducteur));
    w2ui.layout_Traducteur.content('top', $().w2grid(config.gridTraducteur));
    w2ui.layout_Traducteur.content('main', $().w2form(config.formTraducteur));
        
    w2ui.layout_<?php echo $idPage;?>_trad_livre.content('top', $().w2grid(config.gridTradLivreResp));
    w2ui.layout_<?php echo $idPage;?>_trad_livre.content('main', $().w2grid(config.gridTradLivre));

    w2ui.layout_<?php echo $idPage;?>.lock('left', "Sélectionner un livre", true);
    w2ui.layout_<?php echo $idPage;?>.lock('main', "Sélectionner un livre", true);
    
}

function showDataTraduction(){
    //récupère le processus de traduction des livres
    $.get('<?php if(!$this->ajax) echo '../'; ?>processus/getprocess',
		{id:itemSelect.id_livre, process:'Traduction livre'},
    		function(js){
            var g = w2ui['grid_<?php echo $idPage;?>_trad_livre'];
            g.clear();
          	//mise à jour de la grille responsable			        
            var g1 = w2ui['grid_<?php echo $idPage;?>_trad_livre_resp'];
            g1.clear();
    			if(js.rs.length){
        			//mise à jour de la grille processus			        
	            idPLU = js.rs[0].id_plu;
	            g.add(js.rs);
	            g1.add([{recid:js.rs[0].id_plu, id_uti:js.rs[0].id_uti}]);
    			}
    },"json");           		           
    //récupère le processus de traduction des chapitre
	$.get('<?php if(!$this->ajax) echo '../'; ?>processus/getprocess',
		{id:itemSelect.id_livre, process:'Traduction chapitre'},
    		function(js){
            g = w2ui['grid_<?php echo $idPage;?>_trad_chapitre'];
            g.clear();		            		
    			if(js.rs.length){
        			//mise à jour de la grille processus			        
	            g.add(js.rs);
    			}
            w2ui.layout_<?php echo $idPage;?>.unlock('left');
            w2ui.layout_<?php echo $idPage;?>.unlock('main');
    },"json");           		           
	
}
</script>

<?php 
if(!$this->ajax){
	echo '</body>
</html>';
}else{
	echo '<script type="text/javascript">
			$(function () {initTraduction(); });                       		
		</script>		
		';	
}

?>