<?php 
if(!$this->ajax){
	echo '<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>ISTE - Ventes</title>
		<link rel="stylesheet" type="text/css" href="../css/gestedit.css" />
		<link rel="stylesheet" type="text/css" href="../css/w2ui.css" />
		<link rel="stylesheet" type="text/css" href="../fonts/font-awesome/font-awesome.css" />
		<script type="text/javascript">
			var urlP = "../";
			var uti = '.$this->uti.';
			var fctInit;			
		</script>		
		<script type="text/javascript" src="../js/jquery.min.js"></script>
		<script type="text/javascript" src="../js/w2ui.js"></script>
		<script type="text/javascript" src="../js/global.js"></script>
		<script type="text/javascript" src="../js/data.js"></script>
		<script type="text/javascript" src="../js/log.js"></script>
		<script type="text/javascript">
			$(function () {
				initAll(initVente); 
	  			if(uti)
					utiIsConnect();
	  			else
		    	  		diagLogin.showModal();				
			});                       		
		</script>		
		</head>
<body>
';
}
$idPage = "Vente";
?>
<div id="<?php echo $idPage;?>" style="width: 100%; height: 1000px;"></div>

<script type="text/javascript">
var rsVente = <?php echo $this->json; ?>;
var rsMod = <?php echo $this->rsMod; ?>;

//widget configuration
var pstyle = 'border: 1px solid #dfdfdf; padding: 5px;';
var pstyleDetail = 'background-color: #F0F0C1; border: 1px solid #dfdfdf; padding: 5px;';
var config;
var idPLU, idPCU, itemSelectLivre, itemSelectVente, rsIsbnLivre, rsIsbnPrix;
function initVente() {

	config = {
		    layoutVente: {
		        name: 'layout_<?php echo $idPage;?>',
		        padding: 4,
		        panels: [
		 		    { type: 'top', size: 400, style: pstyle},
					{ type: 'main',  
					    style: 'background-color: white; border: 1px solid silver; border-top: 0px; padding: 10px;',
					    tabs: {
					        active: 'tab0',
					        tabs: [{ id: 'tab0', caption: "Détails des ventes pour le livre" },{ id: 'tab1', caption: 'Royalties pour le livre' }
					        		,{ id: 'tab2', caption: 'Prix pour le livre' },{ id: 'tab3', caption: 'Paiements pour le livre' }],
					        onClick: function (event) {
						        if(event.target=="tab0"){
						            w2ui['grid_<?php echo $idPage;?>_detail'].destroy();
						            w2ui.layout_<?php echo $idPage;?>.content('main', $().w2grid(config.gridVenteDetail));
						        }else if(event.target=="tab1"){
						            if(w2ui['grid_<?php echo $idPage;?>_royalties'])w2ui['grid_<?php echo $idPage;?>_royalties'].destroy();
						            w2ui.layout_<?php echo $idPage;?>.content('main', $().w2grid(config.gridVenteRoyalties));						        	
						        }else if(event.target=="tab2"){
						            if(w2ui['grid_<?php echo $idPage;?>_prix'])w2ui['grid_<?php echo $idPage;?>_prix'].destroy();
						            w2ui.layout_<?php echo $idPage;?>.content('main', $().w2grid(config.gridVentePrix));						        	
						        }else if(event.target=="tab3"){
						            if(w2ui['grid_<?php echo $idPage;?>_rapport'])w2ui['grid_<?php echo $idPage;?>_rapport'].destroy();
						            w2ui.layout_<?php echo $idPage;?>.content('main', $().w2grid(config.gridVenteRapport));						        	
						        }
						        getVenteData();						        
					        },
					        onClose: function (event) {
					            this.click('tab0');
					        }
					    }
					},		 		        

					
		            { type: 'left', size: '100%', hidden:true, resizable: true, style: pstyleDetail},
		            { type: 'right', size: '50%', hidden:true, resizable: true, style: pstyleDetail},
		        ]
		    },
		    gridVente: { 
		        name: 'grid_<?php echo $idPage;?>', 
				header: 'Ventes de livres',		
		        show: { 
					header			: true,		
		            toolbar			: true,
					toolbarReload   	: true,
					toolbarColumns  	: true,
		            	toolbarSearch   	: true,
		            	toolbarAdd      	: true,
		            	toolbarDelete   	: false,
		            	toolbarSave		: false,
		            selectColumn		: true,
		            	footer			: true,
		        },
		        multiSearch: true,
		        searches: [
				    { field: 'titre', caption: 'Titre', type: 'text' },
				    { field: 'nom', caption: 'Nom auteur', type: 'text' },
		            { field: 'id_boutique', caption: 'Boutique', type: 'combo', options: { items: arrListes['boutique']} },
		            { field: 'num', caption: 'ISBN', type: 'text' },
		            { field: 'date_vente', caption: 'Date de vente', type: 'date' },
		            { field: 'montant_euro', caption: 'Montant &euro;', type: 'float'},
		            { field: 'montant_livre', caption: 'Montant &pound;', type: 'float'},
		            { field: 'montant_dollar', caption: 'Montant $', type: 'float'},
		            { field: 'sum_mt_e_r', caption: 'Mt. roy. &euro;', type: 'float'},
		        ],
		        columns: [         
		            { field: 'recid', caption: 'ID', size: '50px', hidden:true, sortable: true, resizable: true },
		            { field: 'boutiques', caption: 'Boutiques', size: '130px', sortable: true, resizable: true},
		            { field: 'auteurs', caption: 'Auteurs', size: '200px', sortable: true, resizable: true},
		            { field: 'titre', caption: 'Titre', size: '180px', sortable: true, resizable: true},
		            { field: 'nb_vente', caption: 'Nb de vente', size: '80px', render: 'int', sortable: true, resizable: true},
		            { field: 'isbns', caption: 'ISBNs', size: '100px', sortable: true, resizable: true},
		            { field: 'date_first', caption: 'Première vente', size: '80px', sortable: true, resizable: true},
		            { field: 'date_last', caption: 'Dernière vente', size: '80px', sortable: true, resizable: true},
		            { field: 'mt_e', caption: 'Montant &euro;', size: '80px', sortable: true, resizable: true},
		            { field: 'mt_l', caption: 'Montant &pound;', size: '80px', sortable: true, resizable: true},
		            { field: 'mt_d', caption: 'Montant $', size: '80px', sortable: true, resizable: true},
		            { field: 'mt_e_r', caption: 'Mt. roy. &euro;', size: '80px', sortable: true, resizable: true},
		        ],
		        toolbar: {
		            items: [
		                { id: 'export', type: 'button', caption: 'Exporter', icon: 'fa-file' }
		                ,{ id: 'import', type: 'button', caption: 'Importer fichier de vente', icon: 'fa-cloud-upload' }
		                ,{ id: 'calcPrix', type: 'button', caption: 'Calculer les prix manquants', icon: 'fa-calculator' }
		                ,{ id: 'calcRoy', type: 'button', caption: 'Calculer les royalties', icon: 'fa-calculator' }
		                ,{ id: 'payRoy', type: 'button', caption: 'Calculer les paiements', icon: 'fa-money' }		                
		            ],
		            onClick: function (event) {
		                if (event.target == 'export') {
		                		open(urlP+'export?obj=vente',"_blank")
		                }
		                if (event.target == 'import') {
			                	openPopupImportVente();
		                }
		                if (event.target == 'calcPrix') {
			                calculerPrixVente();
		                }
		                if (event.target == 'calcRoy') {
			                calculerRoyalties();
		                }
		                if (event.target == 'payRoy') {
			                calculerPaiements();
		                }
		            }
		        },
		        records: rsVente,
		        onClick: function (event) {
		        		itemSelectLivre = this.get(event.recid);
		            getVenteData();
		        },	    
		        onAdd: function(event) {
			        	openPopupAjoutVente();            
			    },
		        onSearch: function(event) {
		        		var grid = this;
		        		if(event.searchField=="multi"){
		            		event.onComplete = function () {
			            		$.get('<?php if(!$this->ajax) echo '../'; ?>cherche/vente',
							{"searchData":event.searchData, "bLivre":1},
			            		function(js){
			            			var ids = [];
			            			js.rs.forEach(function(d){
			            				rsVente.forEach(function(l, i){
				            				if(l.recid==d)ids.push(i);
			            				});
				            		});
		                        grid.last.searchIds = ids;
		                        grid.total      = grid.last.searchIds.length; 
		                        grid.buffered   = grid.total; 
		                        grid.refresh();
		                        w2alert(js.message);
			           		},"json");
		                }
		            }else{
			            	grid.localSearch();		            
		            }
		        },				    
		    },
		    formVente: { 
		        name: 'form_<?php echo $idPage;?>',
		        fields: [
		            {name: 'date_vente', type: 'date', options:{format: 'yyyy-mm-dd',openOnFocus: true}, required: true,  html: {caption: 'Date de vente'} },
		            {required: true,  name: 'id_isbn', type: 'list', options: { items: arrListes['isbn'] }
		            		, html: { caption: 'ISBN', attr: 'size="20"' } 
		            		},
					{required: true, name: 'id_boutique', type: 'list', options: { items: arrListes['boutique'] }
		            		, html: { caption: 'Boutique', attr: 'size="20"' } 
		            		},
		            	{required: false,  name: 'prix_euro',  type: 'float', html: { caption: 'Prix &euro;' }},
		            	{required: false,  name: 'prix_livre',  type: 'float', html: { caption: 'Prix &pound;' }},
		            	{required: false,  name: 'prix_dollar',  type: 'float', html: { caption: 'Prix $' }},
		            {required: false,  name: 'id_licence', type: 'list', options: { items: arrListes['licence'] }
		            		, html: { caption: 'Licence', attr: 'size="30"' } 
		            		},
		            {required: false,  name: 'nombre', type: 'int', html: { caption: 'Nombre' } },
		            { name: 'montant_euro', type: 'float', html: { caption: 'Montant &euro;' } },
		            { name: 'montant_livre', type: 'float', html: { caption: 'Montant &pound;' } },
		            { name: 'montant_dollar', type: 'float', html: { caption: 'Montant $' } },
		            { name: 'avec_droit', type: 'checkbox', html: { caption: 'Avec Droit' } },
		            { name: 'prealable', type: 'checkbox', html: { caption: 'Préalable' } },
		            { name: 'acheteur', type: 'text', html: { caption: 'Acheteur' } },
		        ],
		        onChange: function (event) {
		           var r = this.record;
		           event.onComplete = function () {
			           /*calcul du prix
			           if(r.id_licence && r.id_licence.licence_unitaire && r.nombre){
			        	   		w2ui['form_<?php echo $idPage;?>'].record['montant_euro'] = r.id_licence.licence_unitaire * r.nombre; 
			        	   		w2ui['form_<?php echo $idPage;?>'].refresh();
			           }
			           */
			           if(r.prix_euro && r.nombre){
				        	   w2ui['form_<?php echo $idPage;?>'].record['montant_euro'] = r.prix_euro * r.nombre; 
				        	   w2ui['form_<?php echo $idPage;?>'].refresh();
			           }
			           if(r.prix_livre && r.nombre && !r.montant_livre){
			        	   		w2ui['form_<?php echo $idPage;?>'].record['montant_livre'] = r.prix_livre * r.nombre; 
			        	   		w2ui['form_<?php echo $idPage;?>'].refresh();
			           }
			           if(r.prix_dollar && r.nombre && !r.montant_dollar){
			        	   		w2ui['form_<?php echo $idPage;?>'].record['montant_dollar'] = r.prix_dollar * r.nombre; 
				           	w2ui['form_<?php echo $idPage;?>'].refresh();
			           }
		           }		           
		        },
		        actions: {
		            Reset: function () {
		                this.clear();
		                w2popup.close();
		            },
		            Save: function () {
		                var errors = this.validate();
		                if (errors.length > 0) return;
		                var data = this.record;
			            data.id_livre=data.id_isbn.id_livre;
			            data.id_isbn=data.id_isbn.id;
			            if(data.id_licence)data.id_licence=data.id_licence.id;			            
			            if(data.id_boutique)data.id_boutique=data.id_boutique.id;			            
		                data.obj = "vente";
			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/insert',
							data,
			            		function(js){
				                var g = w2ui['grid_<?php echo $idPage;?>'];
								g.add(js.rs);
								g.selectNone();
			            			w2alert(js.message);
			           		},"json");
		            }
		        }
		    },		    
		    gridVenteDetail: { 
		        name: 'grid_<?php echo $idPage;?>_detail',
		        header: 'Détails des ventes pour le livre',		
				show: {toolbar		: true,
	    				toolbarReload   : false,
	    				toolbarColumns  : false,
	                	toolbarSearch   : false,
	                	toolbarAdd      : true,
	                	toolbarDelete   : true,
	                	toolbarSave		: true,
	                	header			: false, 
	                	columnHeaders	: true},
		        columns: [      		  		           
		            { field: 'recid', caption: 'ID', size: '50px', hidden:true, sortable: true, resizable: true },
		            { field: 'devise', caption: 'Devise', size: '150px', sortable: true, resizable: true },
		            { field: 'licence', caption: 'Licence', size: '10%', sortable: true, resizable: true 
		            		,editable: { type: 'list', items: arrListes['licence'], showAll: true },
		                render: function (record, index, col_index) {
		                    var html = this.getCellValue(index, col_index);
		                    return html.text ? html.text : html;
		                }},
		            { field: 'date_vente', caption: 'Date de vente', size: '100px', sortable: true, resizable: true 
		            		,editable: { type: 'date'}},
		            { field: 'id_boutique', caption: 'Boutique', size: '80px', sortable: true, resizable: true 
	            			,editable: { type: 'select', items: arrListes['boutique'] }, 
			                render: function (record, index, col_index) {
			                    var html = '';
			                    for (var p in arrListes['boutique']) {
			                        if (arrListes['boutique'][p].id == this.getCellValue(index, col_index)) html = arrListes['boutique'][p].text;
			                    }
			                    return html;
			                }},
		            { field: 'prix_euro', caption: 'Prix &euro;', size: '80px', sortable: true, resizable: true 
				    		,editable:{type:'float'}},
				    	{ field: 'prix_livre', caption: 'Prix &pound;', size: '80px', sortable: true, resizable: true 
					    		,editable:{type:'float'}},
				    	{ field: 'prix_dollar', caption: 'Prix $', size: '80px', sortable: true, resizable: true 
				    		,editable:{type:'float'}},
		            { field: 'nombre', caption: 'Nombre', size: '80px', sortable: true, resizable: true 
				    		,editable:{type:'int'}},
		            { field: 'montant_euro', caption: 'Montant &euro;', size: '80px', sortable: true, resizable: true
		            		,editable:{type:'float'}},
		            { field: 'montant_livre', caption: 'Montant &pound;', size: '80px', sortable: true, resizable: true
			            	,editable:{type:'float'}},
			        { field: 'montant_dollar', caption: 'Montant $', size: '80px', sortable: true, resizable: true
			        		,editable:{type:'float'}},
		            { field: 'avec_droit', caption: 'Droit', size: '60px', sortable: true, resizable: true
		            		,editable:{type:'checkbox'}},
		            { field: 'prealable', caption: 'Préalable', size: '80px', sortable: true, resizable: true
		            		,editable:{type:'checkbox'}},
		            { field: 'acheteur', caption: 'Acheteur', size: '80px', sortable: true, resizable: true
		    		        ,editable:{type:'text'}},
		        ],
		        onSave: function(event) {
		            var changes = w2ui['grid_<?php echo $idPage;?>_detail'].getChanges();		            
		            changes.forEach(function(c, i){
			            c.obj = 'vente';
				        	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
			        			c,
			        			function(html){
			        				if(changes.length==i+1)w2alert(html);
			        			});                        
		            });
		        },
		        onDelete: function(event) {            
					var p = {id:itemSelectVente.recid, obj:'vente'};
					if(event.force){
			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/delete',
							p,
			            		function(js){
					            getVenteData();
			            			w2alert(js.message);
			           		},"json");
					}
			    },
		        onClick: function (event) {
		            itemSelectVente = this.get(event.recid);
		        }	    
		    },		    		    
		    gridVenteRoyalties: { 
		        name: 'grid_<?php echo $idPage;?>_royalties', 
				header: 'Royalties pour le livre',		
				show: {toolbar		: true,
	    				toolbarReload   : false,
	    				toolbarColumns  : false,
	                	toolbarSearch   : false,
	                	toolbarAdd      : false,
	                	toolbarDelete   : true,
	                	toolbarSave		: true,
	                	header			: false, 
	                	columnHeaders	: true},
		        columns: [      		  		           
		            { field: 'recid', caption: 'ID', size: '50px', hidden:true, sortable: true, resizable: true },
		            { field: 'id_vente', caption: 'id_vente', size: '50px', hidden:true, sortable: true, resizable: true},
		            { field: 'auteur', caption: 'Auteur', size: '100px', sortable: true, resizable: true},
		            { field: 'type_contrat', caption: 'Type de contrat', size: '100px', sortable: true, resizable: true},
		            { field: 'date_vente', caption: 'Date de vente', size: '200px', sortable: true, resizable: true },
		            { field: 'montant_euro', editable:{type:'float'}, caption: 'Montant &euro;', size: '80px', sortable: true, resizable: true},
		            { field: 'montant_livre', editable:{type:'float'}, caption: 'Montant &pound;', size: '80px', sortable: true, resizable: true},
		            { field: 'montant_dollar', editable:{type:'float'}, caption: 'Montant $', size: '80px', sortable: true, resizable: true},
		            { field: 'taxe_taux', editable:{type:'float'}, caption: 'Taxe taux', size: '80px', sortable: true, resizable: true},
		            { field: 'taxe_deduction', editable:{type:'float'}, caption: 'Taxe déduction', size: '100px', sortable: true, resizable: true},
		            { field: 'pourcentage', editable:{type:'float'}, caption: '%', size: '200px', sortable: true, resizable: true},
		            { field: 'date_edition', caption: 'Edition', editable: { type: 'date'}, size: '100px', sortable: true, resizable: true},
		            { field: 'date_paiement', caption: 'Paiement', editable: { type: 'date'}, size: '100px', sortable: true, resizable: true},
		            { field: 'date_encaissement', caption: 'Encaissement', editable: { type: 'date'}, size: '100px', sortable: true, resizable: true},
		        ],
		        onSave: function(event) {
		            var changes = w2ui['grid_<?php echo $idPage;?>_royalties'].getChanges();		            
		            changes.forEach(function(c, i){
			            c.obj = 'royalty';
			            if(c.date_paiement) c.date_paiement = w2utils.formatDate(c.date_paiement, 'yyyy-mm-dd');
			            if(c.date_encaissement) c.date_encaissement = w2utils.formatDate(c.date_encaissement, 'yyyy-mm-dd');			            
				        	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
			        			c,
			        			function(html){
			        				if(changes.length==i+1)w2alert(html);
			        			});                        
		            });
		        },
		        onDelete: function(event) {            
					var p = {obj:'royalty'};
					if(event.force){
						var s = w2ui[event.target].getSelection();
						p.id = s[0];
						$.get('<?php if(!$this->ajax) echo '../'; ?>crud/delete',
							p,
			            		function(js){
			            			w2alert(js.message);
			           		},"json");
					}
			    },		    
		        onAdd: function(event) {
			        //	openPopupAjoutRoyalty();            
			    },
		    },	
		    gridVentePrix: { 
		        name: 'grid_<?php echo $idPage;?>_prix', 
				header: 'Prix pour le livre',		
				show: {toolbar		: true,
	    				toolbarReload   : false,
	    				toolbarColumns  : false,
	                	toolbarSearch   : false,
	                	toolbarAdd      : true,
	                	toolbarDelete   : true,
	                	toolbarSave		: true,
	                	header			: false, 
	                	columnHeaders	: true},
		        columns: [		  		           
		            { field: 'recid', caption: 'ID', size: '50px', hidden:true, sortable: true, resizable: true },
		            { field: 'id_isbn', caption: 'id_isbn', size: '50px', hidden:true, sortable: true, resizable: true},
		            { field: 'num', caption: 'ISBN', size: '120px', sortable: true, resizable: true},
		            { field: 'type_isbn', caption: "Type d'ISBN", size: '10%', sortable: true, resizable: true},
		            { field: 'type_prix', caption: 'Type de prix', size: '10%', sortable: true, resizable: true,editable: { type: 'list', items: arrListes['prix'], showAll: true },
		                render: function (record, index, col_index) {
		                    var html = this.getCellValue(index, col_index);
		                    return html.text ? html.text : html;
		                }},
		            { field: 'prix_euro', caption: 'Prix &euro;', size: '80px', sortable: true, resizable: true,editable:{type:'float'}},
		            { field: 'prix_livre', caption: 'Prix &pound;', size: '80px', sortable: true, resizable: true,editable:{type:'float'}},
		            { field: 'prix_dollar', caption: 'Prix $', size: '80px', sortable: true, resizable: true,editable:{type:'float'}},
		            { field: 'maj', caption: 'Date', size: '200px', sortable: true, resizable: true, editable: { type: 'date'}},
		        ],
		        onSave: function(event) {
		            var changes = w2ui['grid_<?php echo $idPage;?>_prix'].getChanges();		            
		            changes.forEach(function(c, i){
			            c.obj = 'prix';
				        	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/update',
			        			c,
			        			function(html){
			        				if(changes.length==i+1)w2alert(html);
			        			});                        
		            });
		        },
		        onDelete: function(event) {            
					var p = {obj:'prix'};
					if(event.force){
						var s = w2ui[event.target].getSelection();
						p.id = s[0];

						$.get('<?php if(!$this->ajax) echo '../'; ?>crud/delete',
							p,
			            		function(js){
					            getVenteData();
			            			w2alert(js.message);
			           		},"json");
					}
			    },		    
		        onAdd: function(event) {
			        	openPopupAjoutPrix();            
			    },
			},	
		    formPrix: { 
		        name: 'form_<?php echo $idPage;?>_prix',
		        fields: [
		            {name: 'maj', type: 'date', options:{format: 'yyyy-mm-dd',openOnFocus: true}, required: true,  html: {caption: 'Date du prix'} },
		            {required: true,  name: 'id_isbn', type: 'list', options: { items: rsIsbnLivre}
		            		, html: { caption: 'ISBN', attr: 'size="20"' } 
		            		},
		            { name: 'prix_euro', type: 'float', html: { caption: 'Prix &euro;' } },
		            { name: 'prix_livre', type: 'float', html: { caption: 'Prix &pound;' } },
		            { name: 'prix_dollar', type: 'float', html: { caption: 'Prix $' } },
		            {required: true, name: 'type', type: 'list', options: { items: arrListes['prix'] }
		            		, html: { caption: 'type', attr: 'size="20"' } 
		            		},
		        ],
		        actions: {
		            Reset: function () {
		                this.clear();
		                w2popup.close();
		            },
		            Save: function () {
		                var errors = this.validate();
		                if (errors.length > 0) return;
		                var data = this.record;
			            if(data.id_isbn){
				            data.id_isbn=data.id_isbn.id;
			            }			            
			            if(data.type)data.type=data.type.text;			            
			            data.pdf ? data.pdf=1 : data.pdf=0;			            
			            data.obj = "prix";
			            	$.get('<?php if(!$this->ajax) echo '../'; ?>crud/insert',
							data,
			            		function(js){
			            			if(js.rs){
					                var g = w2ui['grid_<?php echo $idPage;?>_prix'];
									g.add(js.rs);
									g.selectNone();
			            			}
			            			w2alert(js.message);
			           		},"json");
		            }
		        }
		    },		    		    	    	    		    

		    gridVenteRapport: { 
		        name: 'grid_<?php echo $idPage;?>_rapport', 
				header: 'Rapport pour le livre',		
				show: {toolbar		: true,
	    				toolbarReload   : false,
	    				toolbarColumns  : false,
	                	toolbarSearch   : false,
	                	toolbarAdd      : false,
	                	toolbarDelete   : true,
	                	toolbarSave		: false,
	                	header			: false, 
	                	columnHeaders	: true},
		        columns: [		  		           
		            { field: 'recid', caption: 'ID', size: '50px', hidden:true, sortable: true, resizable: true },
		            { field: 'maj', caption: 'Date édition', size: '200px', sortable: true, resizable: true},
		            { field: 'url', caption: 'URL', size: '30%', sortable: true, resizable: true},
		            { field: 'prenom', caption: "Prénom", size: '120px', sortable: true, resizable: true},
		            { field: 'nom', caption: 'Nom', size: '120px', sortable: true, resizable: true},
		        ],
		        onDelete: function(event) {            
					var p = {obj:'rapport'};
					if(event.force){
						var s = w2ui[event.target].getSelection();
						p.id = s[0];
						$.get('<?php if(!$this->ajax) echo '../'; ?>crud/delete',
							p,
			            		function(js){
					            getVenteData();
			            			w2alert(js.message);
			           		},"json");
					}
			    },		
		        toolbar: {
		            items: [
		                { id: 'voirRapport', type: 'button', caption: "Voir le(s) édition(s)", icon: 'fa-file' }
		            ],
		            onClick: function (event) {
		                if (event.target == 'voirRapport') {
			                	var s = w2ui['grid_<?php echo $idPage;?>_rapport'].getSelection();
			                	if(s){
				                	s.forEach(function(r){
				                		var item = w2ui['grid_<?php echo $idPage;?>_rapport'].get(r);
				                		open(item["url"],"_blank");
				                	})
			                	}
		                }
		            }
		        },
			        
			},			    
		};
	
    // initialisation
    $('#<?php echo $idPage;?>').w2layout(config.layoutVente);
    w2ui.layout_<?php echo $idPage;?>.content('top', $().w2grid(config.gridVente));
    w2ui.layout_<?php echo $idPage;?>.content('main', $().w2grid(config.gridVenteDetail)); 
     	
}

function getVenteData(){
    if(!itemSelectLivre) return;   
    //récupère le infos liées
    if(w2ui['grid_<?php echo $idPage;?>_detail']){
		$.get('<?php if(!$this->ajax) echo '../'; ?>crud/ventedata',
			{id:itemSelectLivre.recid, obj:'vente'},
	    		function(js){
	            var g = w2ui['grid_<?php echo $idPage;?>_detail'];
	            g.clear();		            		
	    			if(js.rs.length){
	        			//mise à jour de la grille 			        
		            g.add(js.rs);
	    			}
	    },"json");
    }
    if(w2ui['grid_<?php echo $idPage;?>_royalties']){
		$.get('<?php if(!$this->ajax) echo '../'; ?>crud/ventedata',
			{id:itemSelectLivre.recid, obj:'royalty'},
	    		function(js){
	            g = w2ui['grid_<?php echo $idPage;?>_royalties'];
	            g.clear();		            		
	    			if(js.rs.length){
	        			//mise à jour de la grille 			        
		            g.add(js.rs);
	    			}
	    },"json");           		           
    }
    if(w2ui['grid_<?php echo $idPage;?>_prix']){
		$.get('<?php if(!$this->ajax) echo '../'; ?>crud/livredata',
			{id:itemSelectLivre.recid, obj:'prix'},
	    		function(js){
	            g = w2ui['grid_<?php echo $idPage;?>_prix'];
	            g.clear();		            		
	    			if(js.rs.length){
	        			//mise à jour de la grille 			        
		            g.add(js.rs);
	    			}
	    },"json");           		           
    }    
    if(w2ui['grid_<?php echo $idPage;?>_rapport']){
		$.get('<?php if(!$this->ajax) echo '../'; ?>crud/rapportdata',
			{idLivre:itemSelectLivre.recid, idMod:rsMod.id_importfic},
	    		function(js){
	            g = w2ui['grid_<?php echo $idPage;?>_rapport'];
	            g.clear();		            		
	    			if(js.rs.length){
	        			//mise à jour de la grille 			        
		            g.add(js.rs);
	    			}
	    },"json");           		           
    }    

}

function calculerPrixVente(){
	$.get('<?php if(!$this->ajax) echo '../'; ?>calculer/prixvente',
			{},
	    		function(js){
	            var g = w2ui['grid_<?php echo $idPage;?>'];
	            g.records = js.rs;
	            g.refresh();
				w2alert(js.message);	    		
	    },"json");           		           	
}

function calculerRoyalties(){
	$.get('<?php if(!$this->ajax) echo '../'; ?>calculer/royalties',
			{},
	    		function(js){
	            g = w2ui['grid_<?php echo $idPage;?>'];
	            g.records = js.rs;
	            g.refresh();	            		
				w2alert(js.message);	    		
	    },"json");           		           	
}

function calculerPaiements(){
    var g = w2ui['grid_<?php echo $idPage;?>'];
    var s = g.getSelection();
	if(s.length){
		$.get('<?php if(!$this->ajax) echo '../'; ?>calculer/paiement',
				{"type":"livre","idLivre":itemSelectLivre.recid,"ids":s,"idMod":rsMod.id_importfic},
		    		function(js){
					w2alert(js.message);	    		
		    },"json");           		           	
	}else
		w2alert("Veuillez sélectionner des lignes dans le tableau.");	    			
}


function openPopupImportVente () {

    w2popup.open({
        title: 'Importation des fichiers de vente',
        body: '<iframe height="100%" width="100%" scrolling="no" src="<?php if(!$this->ajax) echo '../'; ?>import/vente?obj=import&id=0"></iframe>',
        width     : 1080,
        height    : 740,
        overflow  : 'hidden',
        color     : '#333',
        speed     : '0.3',
        opacity   : '0.8',
        modal     : true,
        showClose : true,
        showMax   : false,
    });
}

function openPopupAjoutVente() {
    w2popup.open({
        title   : 'Ajouter une vente',
        width   : 400,
        height  : 550,
        showMax : true,
        body    : '<div id="main" style="position: absolute; left: 5px; top: 5px; right: 5px; bottom: 5px;"></div>',
        onOpen  : function (event) {
            event.onComplete = function () {
            	 	if(w2ui['form_<?php echo $idPage;?>'])w2ui['form_<?php echo $idPage;?>'].destroy();
                $('#w2ui-popup #main').w2form(config.formVente)
                w2ui['form_<?php echo $idPage;?>'].clear();
            };
        },
        onToggle: function (event) { 
            event.onComplete = function () {
                w2ui.layout.resize();
            }
        }
    });
}
function openPopupAjoutPrix() {
    w2popup.open({
        title   : 'Ajouter un prix',
        width   : 400,
        height  : 500,
        showMax : true,
        body    : '<div id="main" style="position: absolute; left: 5px; top: 5px; right: 5px; bottom: 5px;"></div>',
        onOpen  : function (event) {
            event.onComplete = function () {
            	 	if(w2ui['form_<?php echo $idPage;?>_prix'])w2ui['form_<?php echo $idPage;?>_prix'].destroy();
    		        rsIsbnLivre = arrListes['isbn'].filter(function(p){return p.id_livre==itemSelectLivre.recid});
    		        config.formPrix.fields[1].options.items = rsIsbnLivre;
                $('#w2ui-popup #main').w2form(config.formPrix)
                w2ui['form_<?php echo $idPage;?>_prix'].refresh();
                w2ui['form_<?php echo $idPage;?>_prix'].clear();
            };
        },
        onToggle: function (event) { 
            event.onComplete = function () {
                w2ui.layout.resize();
            }
        }
    });
}
</script>

<?php 
if(!$this->ajax){
	echo '</body>
</html>';
}else{
	echo '<script type="text/javascript">
			$(function () {initVente(); });                       		
		</script>		
		';	
}

?>