<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Gestion des prospects ISTE</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <script type="text/javascript" src="http://rawgit.com/vitmalina/w2ui/master/dist/w2ui.min.js"></script>
    <link rel="stylesheet" type="text/css" href="http://rawgit.com/vitmalina/w2ui/master/dist/w2ui.min.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
        integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
</head>

<body>
    <style>
        .tab {
            width: 100%;
            height: 100%;
            border: 1px solid silver;
            border-top: 0px;
            display: none;
            padding: 10px;
            overflow: auto;
        }
    </style>

    <div id="tab-example" style="width: 100%; height: 600px;" >
        <div id="tabs" style="width: 100%; height: 29px;"></div>
        <div id="tab1" class="tab"></div>
        <div id="tab2" class="tab"></div>
        <div id="tab3" class="tab"></div>
        <div id="tab4" class="tab"></div>
    </div>

    <script type="text/javascript">
        //redimensionnement du tab principal
        document.getElementById('tab-example').setAttribute('style','width: 100%; height: '+(window.innerHeight-30)+'px;');

        // Variable avec les données de la base à afficher
        var jsNomen = <?php echo $this->jsNomen; ?>;
        var jsProsp = <?php echo $this->jsProsp; ?>;
        var jsEtab = <?php echo $this->jsEtab; ?>;
        var jsImpfic = <?php echo $this->jsImpfic; ?>;
        var config;
        // Variable pour exporter les fichiers
        var urlP = "../";

        // Création des listes de recherches pour chaque onglet
        var filters = {
                'aff1': [],
                'aff2': [],
                'aff3': [],
                'Nom': [],
                'NomP': [],
                'Cod': [],
                'Prosp': [],
                'Email': [],
                'Email2': []
            },
            doublons = [];
        jsEtab.forEach(function (d) {
            if (d.affiliation1) doublons[d.affiliation1] = 'aff1';
            if (d.affiliation2) doublons[d.affiliation2] = 'aff2';
            if (d.affiliation3) doublons[d.affiliation3] = 'aff3';
        })
        jsNomen.forEach(function (d) {
            if (d.label) doublons[d.label] = 'Nom';
            if (d.label_parent) doublons[d.label_parent] = 'NomP';
            if (d.code) doublons[d.code] = 'Cod';
        })
        jsProsp.forEach(function (d) {
            if (d.nom_prenom) doublons[d.nom_prenom] = "Prosp";
            if (d.email) doublons[d.email] = "Email";
            if (d.email2) doublons[d.email2] = "Email2";
        })
        for (var k in doublons) {
            filters[doublons[k]].push(k);
        }

        // Fonction pour exporter un fichier
        function exportSave(ids, obj) {
            $.post('mailing/export',
                {'ids':ids,'obj':obj},
                function (js) {
                    if (changes.length == i + 1) w2alert(js.message);
                }, "json");

        }

        // Fonction pour exporter un fichier
        function exportByPost(ids, obj) {
            var form = document.getElementById("exportPostForm");
            if (form) {
                form.ids.value = ids;
                form.obj.value = obj;
            } else {
                var form = document.createElement("form");
                form.setAttribute("id", "exportPostForm");
                form.setAttribute("method", "post");
                form.setAttribute("action", "export");
                form.setAttribute("target", "view");
                var hiddenField = document.createElement("input");
                hiddenField.setAttribute("type", "hidden");
                hiddenField.setAttribute("name", "ids");
                hiddenField.setAttribute("value", ids);
                form.appendChild(hiddenField);
                hiddenField = document.createElement("input");
                hiddenField.setAttribute("type", "hidden");
                hiddenField.setAttribute("name", "obj");
                hiddenField.setAttribute("value", obj);
                form.appendChild(hiddenField);
                document.body.appendChild(form);
            }
            window.open('', 'view');
            form.submit();
        }

        // Création des tabs
        config = {
            tabs: {
                name: 'tabs',
                active: 'tab1',
                tabs: [{
                        id: 'tab1',
                        caption: 'Prospects'
                    },
                    {
                        id: 'tab2',
                        caption: 'Affiliations'
                    },
                    {
                        id: 'tab3',
                        caption: 'Nomenclatures'
                    },
                    {
                        id: 'tab4',
                        caption: 'Imports'
                    }
                ],
                onClick: function (event) {
                    $('#tab-example .tab').hide();
                    $('#tab-example #' + event.target).show();
                    
                    if(event.target=="tab1"){
                        w2ui['layout'].refresh();
                    }else if(event.target=="tab2"){
                        w2ui['layout2'].refresh();
                    }else if(event.target=="tab3"){
                        w2ui['layout3'].refresh();				
                    }else if(event.target=="tab4"){
                        w2ui['layout4'].refresh();			
                    }
                }
            }
        }
        $(function () {
            $('#tabs').w2tabs(config.tabs);
            $('#tab1').show();

            // Création du layout 1er onglet (Prospects)
            var pstyle = 'background-color: #F0F0C1; border: 1px solid #dfdfdf; padding: 5px;';
            $('#tab1').w2layout({
                name: 'layout',
                panels: [{
                        type: 'left',
                        size: '60%',
                        resizable: true,
                        hidden: false,
                        style: pstyle,
                        content: ''
                    },
                    {
                        type: 'main',
                        size: '70%',
                        resizable: true,
                        hidden: false,
                        style: pstyle,
                        content: ''
                    },
                    {
                        type: 'right',
                        size: '30%',
                        resizable: true,
                        hidden: true,
                        style: pstyle
                    },
                    {
                        type: 'bottom',
                        size: '30%',
                        resizable: true,
                        hidden: false,
                        style: pstyle
                    }
                ]
            })
            // Création de la grille prospects
            w2ui['layout'].content('left',
                $().w2grid({
                    name: 'grid',
                    header: 'Prospects',
                    show: {
                        header: true,
                        toolbar: true,
                        footer: true,
                        selectColumn: true,
                        toolbarAdd: true,
                        toolbarDelete: true,
                        toolbarSave: true
                    },
                    multiSearch: true,
                    searches: [{
                            field: 'nom_prenom',
                            caption: 'Nom_Prénom',
                            type: 'enum',
                            options: {
                                items: filters['Prosp']
                            }
                        },
                        {
                            field: 'email',
                            caption: 'Email',
                            type: 'enum',
                            options: {
                                items: filters['Email']
                            }
                        },
                        {
                            field: 'email2',
                            caption: 'Email 2',
                            type: 'enum',
                            options: {
                                items: filters['Email2']
                            }
                        },
                        {
                            field: 'membreEdito',
                            caption: 'Membre editorial',
                            type: 'enum',
                            options: {
                                items: ['0', '1']
                            }
                        },
                        {
                            field: 'clientIste',
                            caption: 'Client ISTE',
                            type: 'enum',
                            options: {
                                items: ['0', '1']
                            }
                        },
                        {
                            field: 'unsub',
                            caption: 'Unsubscribe',
                            type: 'enum',
                            options: {
                                items: ['0', '1']
                            }
                        }
                    ],
                    columns: [{
                            field: 'recid',
                            caption: 'ID',
                            size: '50px',
                            sortable: true,
                            resizable: true
                        },
                        {
                            field: 'nom_prenom',
                            caption: 'Nom Prénom',
                            size: '40%',
                            editable: {
                                type: 'text'
                            }
                        },
                        {
                            field: 'email',
                            caption: 'Email',
                            size: '20%',
                            editable: {
                                type: 'email'
                            }
                        },
                        {
                            field: 'email2',
                            caption: 'Email2',
                            size: '20%',
                            editable: {
                                type: 'email'
                            }
                        },
                        {
                            field: 'origine',
                            caption: 'Origine',
                            size: '20%',
                            editable: {
                                type: 'text'
                            }
                        },
                        {
                            field: 'clientIste',
                            caption: 'Client Iste',
                            size: '30%',
                            editable: {
                                type: 'text'
                            }

                        },
                        {
                            field: 'membreEdito',
                            caption: 'Membre editorial',
                            size: '30%',
                            editable: {
                                type: 'text'
                            }
                        },
                        {
                            field: 'unsub',
                            caption: 'Unsubscribe',
                            size: '30%',
                            editable: {
                                type: 'text'
                            }
                        },
                        {
                            field: 'maj',
                            caption: 'Date MAJ',
                            size: '30%',
                            type: 'date'
                        }
                    ],
                    toolbar: {
                        items: [{
                            id: 'export',
                            type: 'button',
                            text: 'Exporter',
                            icon: 'fas fa-file-export'
                        }],
                        onClick: function (event) {
                            if (event.target == 'export') {
                                var ids = w2ui.grid.getSelection();
                                exportByPost(ids, "prospect");
                                //open(urlP + 'export?obj=prospect&ids=' + ids, "_blank");
                            }
                        }
                    },
                    records: jsProsp,
                    onSave: function (event) {
                        var changes = w2ui['grid'].getChanges();
                        changes.forEach(function (c, i) {
                            c.obj = 'prospect';
                            $.get('mailing/update',
                                c,
                                function (js) {
                                    //finsession(js);		
                                    js.rs.text = js.rs.nom + " " + js.rs.prenom;
                                    setListe(js.rs, 'prospect');
                                    if (changes.length == i + 1) w2alert(js.message);
                                }, "json");
                        });
                    },
                    onSelect: function (event) {
                        //if (record && record.recid == event.recid) return;
                        event.onComplete = function () {
                            var record = this.get(event.recid);
                            var ids = w2ui.grid.getSelection();
                            // Grille secondaire Prospect -> Affiliations
                            w2ui['grid10'].clear();
                            $.get('mailing/prospectaff',
                                {id_prospect:record.recid, 'ids':ids},
                                function(js){
                                    //finsession(js);
                                    w2ui['grid10'].add(js.rs);
                                },"json");
                            // Grille secondaire Prospect -> Nomenclatures
                            w2ui['grid11'].clear();  
                            $.get('mailing/prospectnom',
                                {id_prospect:record.recid, 'ids':ids},
                                function(js){
                                    //finsession(js);
                                    w2ui['grid11'].add(js.rs);		
                                },"json");      
                        }
                    },
                    onAdd: function (event) {
                        openPopupP();
                    },
                    onDelete: function (event) {
                        var itemsSelect = w2ui.grid.getSelection();
                        var p = {
                            id: itemsSelect,
                            obj: 'prospect'
                        };
                        if (event.force) {
                            $.get('mailing/delete',
                                p,
                                function (js) {
                                    // finsession(js);
                                    w2alert(js.message);
                                }, "json");
                        }
                    },
                    onSearch: function (event) {
                        var grid = this;
                        if (event.searchField == "multi") {
                            event.onComplete = function () {
                                $.get('cherche/mailing', {
                                        "searchData": event.searchData
                                    },
                                    function (js) {
                                        //finsession(js);
                                        var ids = [];
                                        js.rs.forEach(function (d) {
                                            jsProsp.forEach(function (l, i) {
                                                if (l.id_prospect == d) ids
                                                    .push(i);
                                            });
                                        });
                                        grid.last.searchIds = ids;
                                        grid.total = grid.last.searchIds.length;
                                        grid.buffered = grid.total;
                                        grid.refresh();
                                        w2alert(js.message);
                                    }, "json");
                            }
                        } else {
                            grid.localSearch();
                            event.onComplete = function () {
                                grid.last.searchIds = grid.last.searchIds;
                                grid.total = grid.last.searchIds.length;
                                grid.buffered = grid.total;
                                grid.refresh();
                            }
                        }
                    },
                }))
            // Création formulaire ajout de prospect
            function openPopupP() {
                if (!w2ui.foo) {
                    $().w2form({
                        name: 'foo',
                        style: 'border: 0px; background-color: transparent;',
                        formHTML: '<div class="w2ui-page page-0">' +
                            '    <div class="w2ui-field">' +
                            '        <label>Nom Prénom:</label>' +
                            '        <div>' +
                            '           <input name="nom_prenom" type="text" maxlength="100" style="width: 250px"/>' +
                            '        </div>' +
                            '    </div>' +
                            '    <div class="w2ui-field">' +
                            '        <label>Email:</label>' +
                            '        <div>' +
                            '           <input name="email" type="text" maxlength="100" style="width: 250px"/>' +
                            '        </div>' +
                            '    </div>' +
                            '    <div class="w2ui-field">' +
                            '        <label>Email 2:</label>' +
                            '        <div>' +
                            '            <input name="email2" type="text" maxlength="150" style="width: 250px"/>' +
                            '        </div>' +
                            '    </div>' +
                            '    <div class="w2ui-field">' +
                            '        <label>Origine :</label>' +
                            '        <div>' +
                            '            <input name="origine" type="text" style="width: 250px"/>' +
                            '        </div>' +
                            '    </div>' +
                            '    <div class="w2ui-field">' +
                            '        <label>Client ISTE:</label>' +
                            '        <div>' +
                            '            <input name="clientIste" type="checkbox" style="width: 250px"/>' +
                            '        </div>' +
                            '    </div>' +
                            '    <div class="w2ui-field">' +
                            '        <label>Membre Edito:</label>' +
                            '        <div>' +
                            '            <input name="membreEdito" type="checkbox" style="width: 250px"/>' +
                            '        </div>' +
                            '    </div>' +
                            '    <div class="w2ui-field">' +
                            '        <label>Unsubscribe:</label>' +
                            '        <div>' +
                            '            <input name="unsub" type="checkbox" style="width: 250px"/>' +
                            '        </div>' +
                            '    </div>' +
                            '</div>' +
                            '<div class="w2ui-buttons">' +
                            '    <button class="w2ui-btn" name="reset">Reset</button>' +
                            '    <button class="w2ui-btn" name="save">Save</button>' +
                            '</div>',
                        fields: [{
                                field: 'nom_prenom',
                                type: 'text',
                                required: true
                            },
                            {
                                field: 'email',
                                type: 'email',
                                required: true
                            },
                            {
                                field: 'email2',
                                type: 'email'
                            },
                            {
                                field: 'origine',
                                type: 'text'
                            },
                            {
                                field: 'clientIste',
                                type: 'checkbox'
                            },
                            {
                                field: 'membreEdito',
                                type: 'checkbox'
                            },
                            {
                                field: 'unsub',
                                type: 'checkbox'
                            }
                        ],
                        actions: {
                            "save": function () {
                                var errors = this.validate();
                                if (errors.length > 0) return;
                                var data = this.record;
                                data.obj = "prospect";
                                $.get('mailing/insert',
                                    data,
                                    function (js) {
                                        //finsession(js);
                                        w2ui['grid'].add(js.rs);
                                    }, "json");
                                w2popup.close();
                            },
                            "reset": function () {
                                this.clear();
                            }
                        }
                    });
                }
                $().w2popup('open', {
                    title: 'Formulaire Prospects',
                    body: '<div id="form" style="width: 100%; height: 100%;"></div>',
                    style: 'padding: 15px 0px 0px 0px',
                    width: 500,
                    height: 600,
                    showMax: true,
                    onToggle: function (event) {
                        $(w2ui.foo.box).hide();
                        event.onComplete = function () {
                            $(w2ui.foo.box).show();
                            w2ui.foo.resize();
                        }
                    },
                    onOpen: function (event) {
                        event.onComplete = function () {
                            // specifying an onOpen handler instead is equivalent to specifying an onBeforeOpen handler, which would make this code execute too early and hence not deliver.
                            $('#w2ui-popup #form').w2render('foo');
                        }
                    }
                });
            }
            // Création grille historique des envois mails prospects
            w2ui['layout'].content('main',
                $().w2grid({
                    name: 'grid2',
                    header: 'Historique des envois',
                    show: {
                        header: true,
                        toolbar: true,
                    },
                    multiSearch: true,
                    searches: [{
                        field: 'date_envoi',
                        caption: 'Date dernier mail',
                        type: 'date'
                    }, ],
                    columns: [{
                            field: 'recid',
                            caption: 'ID',
                            size: '50px',
                            sortable: true,
                            resizable: true
                        },
                        {
                            field: 'date_envoi',
                            caption: 'Date dernier mail',
                            type: 'date',
                            size: '20%'
                        },
                        {
                            field: 'nombre_mail',
                            caption: 'Nombre de mails envoyé',
                            type: 'text',
                            size: '20%'
                        },
                        {
                            field: 'date_creation',
                            caption: 'Date de création prospect',
                            type: 'date',
                            size: '20%'
                        },
                        {
                            field: 'date_unsub',
                            caption: 'Date de désinscription',
                            type: 'date',
                            size: '20%'
                        }
                    ],
                    records: [{
                        recid: 1,
                        fname: 'John',
                        lname: 'Doe',
                        email: 'jdoe@gmail.com',
                        sdate: '4/3/2012'
                    }]
                }))

            // Création du layout esclave (Prospects)
            var pstyle = 'background-color: #F0F0C1; border: 1px solid #dfdfdf; padding: 5px;';
            w2ui['layout'].content('bottom',
            $().w2layout({
                name: 'layout5',
                panels: [{
                        type: 'left',
                        size: '50%',
                        resizable: true,
                        hidden: false,
                        style: pstyle,
                        content: ''
                    },
                    {
                        type: 'main',
                        resizable: true,
                        hidden: false,
                        style: pstyle,
                        content: ''
                    }
                ]
            }))
            // Création de la grille esclaves affiliation
            w2ui['layout5'].content('left',
                $().w2grid({
                    name: 'grid10',
                    header: 'Affiliations du prospect',
                    show: {
                        header: true,
                        toolbar: true,
                        footer: true,
                        selectColumn: true,
                        toolbarAdd: true,
                        toolbarDelete: true
                    },
                    columns: [{
                            field: 'recid',
                            caption: 'ID',
                            size: '50px',
                            sortable: true,
                            hidden: true,
                            resizable: true
                        },
                        /*
                        {
                            field: 'id_prospect',
                            caption: 'ID Prospect',
                            size: '50px',
                            sortable: true,
                            hidden: true,
                            resizable: true
                        },
                        */
                        {
                            field: 'affiliation1',
                            caption: 'Affiliation 1',
                            size: '30%',
                            type: 'text'
                        },
                        {
                            field: 'affiliation2',
                            caption: 'Affiliation 2',
                            size: '30%',
                            type: 'text'
                        },
                        {
                            field: 'affiliation3',
                            caption: 'Affiliation 3',
                            size: '30%',
                            type: 'text'
                        }
                    ],
                    onAdd: function (event) {
                       // openPopupP();
                    },
                    onDelete: function (event) {
                        var itemsSelect = w2ui.grid.getSelection();
                        var p = {
                            'idsProspect': itemsSelect,
                            obj: 'prospectxetab'
                        };
                        if (event.force) {
                            var s = w2ui[event.target].getSelection();
						    p.idsEtab = s;
                            $.get('mailing/delete',
                                p,
                                function (js) {
                                    // finsession(js);
                                    w2alert(js.message);
                                }, "json");
                        }
                    },
                }))
            // Création de la grille esclaves nomenclature
            w2ui['layout5'].content('main',
                $().w2grid({
                    name: 'grid11',
                    header: 'Nomenclatures du prospect',
                    show: {
                        header: true,
                        toolbar: true,
                        footer: true,
                        selectColumn: true,
                        toolbarAdd: true,
                        toolbarDelete: true
                    },
                    columns: [{
                            field: 'recid',
                            caption: 'ID',
                            size: '50px',
                            hidden: true,
                            sortable: true,
                            resizable: true
                        },
                        /*
                        {
                            field: 'id_prospect',
                            caption: 'ID Prospect',
                            size: '50px',
                            hidden: true,
                            sortable: true,
                            resizable: true
                        },
                        */
                        {
                            field: 'label',
                            caption: 'Label',
                            size: '40%',
                            type: 'text'
                        },
                        {
                            field: 'code',
                            caption: 'Code',
                            size: '20%',
                            type: 'text'
                        }
                    ],
                    onAdd: function (event) {
                       // openPopupP();
                    },
                    onDelete: function (event) {
                        var itemsSelect = w2ui.grid.getSelection();
                        var p = {
                            'idsProspect': itemsSelect,
                            obj: 'prospectxnomenclature'
                        };
                        if (event.force) {
                            var s = w2ui[event.target].getSelection();
						    p.idsNomenclature = s;
                            $.get('mailing/delete',
                                p,
                                function (js) {
                                    // finsession(js);
                                    w2alert(js.message);
                                }, "json");
                        }
                    },
                }))
            // Création du layout 2e onglet (Etablissements)
            var pstyle = 'background-color: #F0F0C1; border: 1px solid #dfdfdf; padding: 5px;';
            $('#tab2').w2layout({
                name: 'layout2',
                panels: [{
                        type: 'top',
                        size: 600,
                        resizable: true,
                        hidden: true,
                        style: pstyle,
                        content: ''
                    },
                    {
                        type: 'left',
                        size: '70%',
                        resizable: true,
                        hidden: false,
                        style: pstyle,
                        content: ''
                    },
                    {
                        type: 'main',
                        size: '70%',
                        resizable: true,
                        hidden: false,
                        style: pstyle,
                        content: ''
                    },
                    {
                        type: 'bottom',
                        size: '30%',
                        resizable: true,
                        hidden: false,
                        style: pstyle
                    }
                ]
            })
            // Création de la grille Etablissements
            w2ui['layout2'].content('left',
                $().w2grid({
                    name: 'grid3',
                    header: 'Etablissements',
                    show: {
                        header: true,
                        toolbar: true,
                        footer: true,
                        selectColumn: true,
                        toolbarAdd: true,
                        toolbarDelete: true,
                        toolbarSave: true
                    },
                    multiSearch: true,
                    searches: [{
                            field: 'affiliation1',
                            caption: 'Affiliation 1',
                            type: 'enum',
                            options: {
                                items: filters['aff1']
                            }
                        },
                        {
                            field: 'affiliation2',
                            caption: 'Affiliation 2',
                            type: 'enum',
                            options: {
                                items: filters['aff2']
                            }
                        },
                        {
                            field: 'affiliation3',
                            caption: 'Affiliation 3',
                            type: 'enum',
                            options: {
                                items: filters['aff3']
                            }
                        }
                    ],
                    columns: [{
                            field: 'recid',
                            caption: 'ID',
                            size: '50px',
                            sortable: true,
                            resizable: true
                        },
                        {
                            field: 'affiliation1',
                            caption: 'Affiliation 1',
                            size: '30%',
                            editable: {
                                type: 'text'
                            }
                        },
                        {
                            field: 'affiliation2',
                            caption: 'Affiliation 2',
                            size: '30%',
                            editable: {
                                type: 'text'
                            }
                        },
                        {
                            field: 'affiliation3',
                            caption: 'Affiliation 3',
                            size: '30%',
                            editable: {
                                type: 'text'
                            }
                        },
                        {
                            field: 'url_labo',
                            caption: 'URL du Labo',
                            size: '40%',
                            editable: {
                                type: 'text'
                            }
                        },
                        {
                            field: 'adresse',
                            caption: 'Adresse',
                            size: '120px',
                            editable: {
                                type: 'text'
                            }
                        },
                        {
                            field: 'ville_cp',
                            caption: 'Ville + CP',
                            size: '120px',
                            editable: {
                                type: 'text'
                            }
                        },
                        {
                            field: 'pays',
                            caption: 'Pays',
                            size: '30%',
                            editable: {
                                type: 'text'
                            }
                        },
                        {
                            field: 'responsable',
                            caption: 'Responsable du Labo',
                            size: '30%',
                            editable: {
                                type: 'text'
                            }
                        },
                    ],
                    /*toolbar: {
                        items: [{
                            id: 'import',
                            type: 'button',
                            caption: 'Importer',
                            icon: 'fas fa-file-import'
                        }],
                        onClick: function (event) {
                            if (event.target == 'import') {
                                openPopupImportData();
                            }
                        }
                    },*/
                    records: jsEtab,
                    onSelect: function (event) {
                      //  if (record && record.recid == event.recid) return;
                        event.onComplete = function (){
                            var record = this.get(event.recid);
                            var ids = w2ui.grid3.getSelection();
                            // Grille secondaire Affiliation -> Prospects
                            w2ui['grid12'].clear();
                            $.get('mailing/affprospect',
                            {id_etab:record.recid, 'ids':ids},
                            function(js){
                                //finsession(js);
                                w2ui['grid12'].add(js.rs);
                            },"json");
                            // Grille secondaire Affiliation -> Nomenclatures
                            w2ui['grid13'].clear();
                            $.get('mailing/affnomen',
                            {id_etab:record.recid, 'ids':ids},
                            function(js){
                                //finsession(js);
                                w2ui['grid13'].add(js.rs);
                            },"json");
                        }
                    },
                    onSave: function (event) {
                        var changes = w2ui['grid3'].getChanges();
                        changes.forEach(function (c, i) {
                            c.obj = 'etab';
                            $.get('mailing/update',
                                c,
                                function (js) {
                                    //finsession(js);		
                                    js.rs.text = js.rs.nom + " " + js.rs.prenom;
                                    setListe(js.rs, 'etab');
                                    if (changes.length == i + 1) w2alert(js.message);
                                }, "json");
                        });
                    },
                    onAdd: function (event) {
                        openPopupE();
                    },
                    onDelete: function (event) {
                        var itemsSelect = w2ui.grid3.getSelection();
                        var p = {
                            id: itemsSelect,
                            obj: 'etab'
                        };
                        if (event.force) {
                            $.get('mailing/delete',
                                p,
                                function (js) {
                                    // finsession(js);
                                    w2alert(js.message);
                                }, "json");
                        }
                    },
                    onSearch: function (event) {
                        var grid = this;
                        if (event.searchField == "multi") {
                            event.onComplete = function () {
                                $.get('cherche/mailing', {
                                        "searchData": event.searchData
                                    },
                                    function (js) {
                                        //finsession(js);
                                        var ids = [];
                                        js.rs.forEach(function (d) {
                                            jsEtab.forEach(function (l, i) {
                                                if (l.id_etab == d) ids
                                                    .push(i);
                                            });
                                        });
                                        grid.last.searchIds = ids;
                                        grid.total = grid.last.searchIds.length;
                                        grid.buffered = grid.total;
                                        grid.refresh();
                                        w2alert(js.message);
                                    }, "json");
                            }
                        } else {
                            grid.localSearch();
                            event.onComplete = function () {
                                grid.last.searchIds = grid.last.searchIds;
                                grid.total = grid.last.searchIds.length;
                                grid.buffered = grid.total;
                                grid.refresh();
                            }
                        }
                    },
                }))
            // Création du formulaire d'ajout d'établissement
            function openPopupE() {
                if (!w2ui.foo2) {
                    $().w2form({
                        name: 'foo2',
                        style: 'border: 0px; background-color: transparent;',
                        formHTML: '<div class="w2ui-page page-0">' +
                            '    <div class="w2ui-field">' +
                            '        <label>Affiliation 1 :</label>' +
                            '        <div>' +
                            '           <input name="affiliation1" type="text" maxlength="100" style="width: 250px"/>' +
                            '        </div>' +
                            '    </div>' +
                            '    <div class="w2ui-field">' +
                            '        <label>Affiliation 2 :</label>' +
                            '        <div>' +
                            '           <input name="affiliation2" type="text" maxlength="100" style="width: 250px"/>' +
                            '        </div>' +
                            '    </div>' +
                            '    <div class="w2ui-field">' +
                            '        <label>Affiliation 3 :</label>' +
                            '        <div>' +
                            '           <input name="affiliation3" type="text" maxlength="100" style="width: 250px"/>' +
                            '        </div>' +
                            '    </div>' +
                            '    <div class="w2ui-field">' +
                            '        <label>URL Labo:</label>' +
                            '        <div>' +
                            '            <input name="url_labo" type="text" maxlength="150" style="width: 250px"/>' +
                            '        </div>' +
                            '    </div>' +
                            '    <div class="w2ui-field">' +
                            '        <label>Adresse:</label>' +
                            '        <div>' +
                            '            <input name="adresse" type="text" style="width: 250px"/>' +
                            '        </div>' +
                            '    </div>' +
                            '    <div class="w2ui-field">' +
                            '        <label>Ville + CP:</label>' +
                            '        <div>' +
                            '            <input name="ville_cp" type="text" style="width: 250px"/>' +
                            '        </div>' +
                            '    </div>' +
                            '    <div class="w2ui-field">' +
                            '        <label>Pays:</label>' +
                            '        <div>' +
                            '            <input name="pays" type="text" style="width: 250px"/>' +
                            '        </div>' +
                            '    </div>' +
                            '    <div class="w2ui-field">' +
                            '        <label>Responsable Labo:</label>' +
                            '        <div>' +
                            '            <input name="responsable" type="text" style="width: 250px"/>' +
                            '        </div>' +
                            '    </div>' +
                            '</div>' +
                            '<div class="w2ui-buttons">' +
                            '    <button class="w2ui-btn" name="reset">Reset</button>' +
                            '    <button class="w2ui-btn" name="save">Save</button>' +
                            '</div>',
                        fields: [{
                                field: 'affiliation1',
                                type: 'text',
                                required: true
                            },
                            {
                                field: 'affiliation2',
                                type: 'text'
                            },
                            {
                                field: 'affiliation3',
                                type: 'text'
                            },
                            {
                                field: 'url_labo',
                                type: 'text'
                            },
                            {
                                field: 'adresse',
                                type: 'text'
                            },
                            {
                                field: 'ville_cp',
                                type: 'text'
                            },
                            {
                                field: 'pays',
                                type: 'text'
                            },
                            {
                                field: 'responsable',
                                type: 'text'
                            }
                        ],
                        actions: {
                            "save": function () {
                                var errors = this.validate();
                                if (errors.length > 0) return;
                                var data = this.record;
                                data.obj = "etab";
                                $.get('mailing/insert',
                                    data,
                                    function (js) {
                                        //finsession(js);
                                        w2ui['grid3'].add(js.rs);
                                    }, "json");
                                w2popup.close();
                            },
                            "reset": function () {
                                this.clear();
                            }
                        }
                    });
                }
                $().w2popup('open', {
                    title: 'Formulaire Affiliation',
                    body: '<div id="form" style="width: 100%; height: 100%;"></div>',
                    style: 'padding: 15px 0px 0px 0px',
                    width: 500,
                    height: 600,
                    showMax: true,
                    onToggle: function (event) {
                        $(w2ui.foo.box).hide();
                        event.onComplete = function () {
                            $(w2ui.foo.box).show();
                            w2ui.foo.resize();
                        }
                    },
                    onOpen: function (event) {
                        event.onComplete = function () {
                            // specifying an onOpen handler instead is equivalent to specifying an onBeforeOpen handler, which would make this code execute too early and hence not deliver.
                            $('#w2ui-popup #form').w2render('foo2');
                        }
                    }
                });
            }
            // Création de la grille historique des envois / établissement
            w2ui['layout2'].content('main',
                $().w2grid({
                    name: 'grid5',
                    header: 'Historique des envois',
                    show: {
                        header: true,
                        toolbar: true,
                    },
                    multiSearch: true,
                    searches: [{
                        field: 'date_envoi',
                        caption: 'Date dernier mail',
                        type: 'date'
                    }, ],
                    columns: [{
                            field: 'recid',
                            caption: 'ID',
                            size: '50px',
                            sortable: true,
                            resizable: true
                        },
                        {
                            field: 'date_envoi',
                            caption: 'Date dernier mail',
                            type: 'date',
                            size: '20%'
                        },
                        {
                            field: 'date_creation',
                            caption: 'Date de création Etablissement',
                            type: 'date',
                            size: '20%'
                        },
                        {
                            field: 'nombre_mail',
                            caption: 'Nombre de mails envoyé',
                            type: 'text',
                            size: '20%'
                        }
                    ],
                    records: [{
                        recid: 1,
                        fname: 'John',
                        lname: 'Doe',
                        email: 'jdoe@gmail.com',
                        sdate: '4/3/2012'
                    }]
                }))
                // Création du layout esclave (Affiliations)
                var pstyle = 'background-color: #F0F0C1; border: 1px solid #dfdfdf; padding: 5px;';
                w2ui['layout2'].content('bottom',
                $().w2layout({
                    name: 'layout6',
                    panels: [{
                        type: 'left',
                        size: '50%',
                        resizable: true,
                        hidden: false,
                        style: pstyle,
                        content: ''
                    },
                    {
                        type: 'main',
                        resizable: true,
                        hidden: false,
                        style: pstyle,
                        content: ''
                    }
                ]
            }))
            // Création de la grille esclaves affiliation
            w2ui['layout6'].content('left',
                $().w2grid({
                    name: 'grid12',
                    header: 'Prospects liés aux affiliations',
                    show: {
                        header: true,
                        toolbar: true,
                        footer: true,
                        toolbarAdd: true,
                        selectColumn: true,
                        toolbarDelete: true
                    },
                    toolbar: {
                        items: [{
                            id: 'export',
                            type: 'button',
                            text: 'Exporter',
                            icon: 'fas fa-file-export'
                        }],
                        onClick: function (event) {
                            if (event.target == 'export') {
                                var ids = w2ui.grid12.getSelection();
                                exportByPost(ids, "prospect");
                                //open(urlP + 'export?obj=prospect&ids=' + ids, "_blank");
                            }
                        }
                    },
                    columns: [{
                            field: 'recid',
                            caption: 'ID',
                            size: '50px',
                            sortable: true,
                            hidden: true,
                            resizable: true
                        },
                        {
                            field: 'nom_prenom',
                            caption: 'Nom Prénom',
                            size: '40%',
                            type: 'text'
                        },
                        {
                            field: 'email',
                            caption: 'Email',
                            size: '20%',
                            type: 'text'
                        },
                        {
                            field: 'unsub',
                            caption: 'Unsubscribe',
                            size: '30%',
                            type: 'text'
                        }
                    ],
                    onAdd: function (event) {
                        //openPopupP();
                    },
                    onDelete: function (event) {
                        var itemsSelect = w2ui.grid3.getSelection();
                        var p = {
                            'idsEtab': itemsSelect,
                            obj: 'prospectxetab'
                        };
                        if (event.force) {
                            var s = w2ui[event.target].getSelection();
                            p.idsProspect = s;
                            $.get('mailing/delete',
                                p,
                                function (js) {
                                    // finsession(js);
                                    w2alert(js.message);
                                }, "json");
                        }
                    },
                }))
            // Création de la grille esclaves nomenclature
            w2ui['layout6'].content('main',
                $().w2grid({
                    name: 'grid13',
                    header: 'Nomenclatures liés aux affiliations',
                    show: {
                        header: true,
                        toolbar: false,
                        footer: true,
                        selectColumn: true,
                        toolbarAdd: false,
                        toolbarDelete: false
                    },
                    columns: [{
                            field: 'recid',
                            caption: 'ID',
                            size: '50px',
                            sortable: true,
                            hidden: true,
                            resizable: true
                        },
                        {
                            field: 'code',
                            caption: 'Code',
                            size: '20%',
                            type: 'text'
                        },
                        {
                            field: 'label',
                            caption: 'Label',
                            size: '40%',
                            type: 'text'
                        }
                    ],
                    /*
                    onAdd: function (event) {
                        //openPopupP();
                    },
                    onDelete: function (event) {
                        var itemsSelect = w2ui.grid.getSelection();
                        var p = {
                            id: itemsSelect,
                            obj: 'prospect'
                        };
                        if (event.force) {
                            $.get('mailing/delete',
                                p,
                                function (js) {
                                    // finsession(js);
                                    w2alert(js.message);
                                }, "json");
                        }
                    },
                    */
                }))
            // Création du layout 3e onglet (Nomenclatures)
            var pstyle = 'background-color: #F0F0C1; border: 1px solid #dfdfdf; padding: 5px;';
            $('#tab3').w2layout({
                name: 'layout3',
                panels: [{
                        type: 'top',
                        size: 600,
                        resizable: true,
                        hidden: true,
                        style: pstyle,
                        content: ''
                    },
                    {
                        type: 'left',
                        size: '70%',
                        resizable: true,
                        hidden: false,
                        style: pstyle,
                        content: ''
                    },
                    {
                        type: 'main',
                        size: '70%',
                        resizable: true,
                        hidden: false,
                        style: pstyle,
                        content: ''
                    },
                    {
                        type: 'bottom',
                        size: '30%',
                        resizable: true,
                        hidden: false,
                        style: pstyle
                    }
                ]
            })
            // Création de la grille nomenclature
            w2ui['layout3'].content('left',
                $().w2grid({
                    name: 'grid4',
                    header: 'Nomenclatures',
                    show: {
                        header: true,
                        toolbar: true,
                        toolbarReload: true,
                        toolbarColumns: true,
                        toolbarSearch: true,
                        toolbarAdd: true,
                        toolbarDelete: true,
                        toolbarSave: true,
                        selectColumn: true,
                        footer: true
                    },
                    multiSearch: true,
                    searches: [{
                            field: 'label_parent',
                            caption: 'Catégorie Parent',
                            type: 'enum',
                            options: {
                                items: filters['NomP']
                            }
                        },
                        {
                            field: 'label',
                            caption: 'label',
                            type: 'enum',
                            options: {
                                items: filters['Nom']
                            }
                        },
                        {
                            field: 'code',
                            caption: 'code',
                            type: 'enum',
                            options: {
                                items: filters['Cod']
                            }
                        }
                    ],
                    columns: [{
                            field: 'recid',
                            caption: 'ID',
                            size: '50px',
                            sortable: true,
                            resizable: true
                        },
                        {
                            field: 'code',
                            caption: 'Code',
                            size: '20%',
                            editable: {
                                type: 'text'
                            }
                        },
                        {
                            field: 'label',
                            caption: 'Label',
                            size: '40%',
                            editable: {
                                type: 'text'
                            }
                        },
                        {
                            field: 'id_parent',
                            caption: 'ID Parent',
                            size: '10%',
                            editable: {
                                type: 'text'
                            }
                        },
                        {
                            field: 'label_parent',
                            caption: 'Catégorie Parent',
                            size: '40%',
                            editable: {
                                type: 'text'
                            }
                        }
                    ],
                    records: jsNomen,
                    onSelect: function (event) {
                      //  if (record && record.recid == event.recid) return;
                        event.onComplete = function (){
                            var record = this.get(event.recid);
                            var ids = w2ui.grid4.getSelection();
                            // Grille secondaire Nomenclature -> Prospects
                            w2ui['grid14'].clear();
                            $.get('mailing/nomenprospect',
                            {id_nomenclature:record.recid, 'ids': ids},
                            function(js){
                                //finsession(js);
                                w2ui['grid14'].add(js.rs);
                            },"json");
                            w2ui['grid15'].clear();
                            $.get('mailing/nomenaff',
                            {id_nomenclature:record.recid, 'ids': ids},
                            function(js){
                                //finsession(js);
                                w2ui['grid15'].add(js.rs);
                            },"json");
                        }
                    },
                    onSave: function (event) {
                        var changes = w2ui['grid4'].getChanges();
                        changes.forEach(function (c, i) {
                            c.obj = 'nomenclature';
                            $.get('mailing/update',
                                c,
                                function (js) {
                                    //finsession(js);		
                                    js.rs.text = js.rs.nom + " " + js.rs.prenom;
                                    setListe(js.rs, 'nomenclature');
                                    if (changes.length == i + 1) w2alert(js.message);
                                }, "json");
                        });
                    },
                    onAdd: function (event) {
                        openPopupN();
                    },
                    onDelete: function (event) {
                        var itemsSelect = w2ui.grid4.getSelection();
                        var p = {
                            id: itemsSelect,
                            obj: 'nomenclature'
                        };
                        if (event.force) {
                            $.get('mailing/delete',
                                p,
                                function (js) {
                                    // finsession(js);
                                    w2alert(js.message);
                                }, "json");
                        }
                    },
                    onSearch: function (event) {
                        var grid = this;
                        if (event.searchField == "multi") {
                            event.onComplete = function () {
                                $.get('cherche/nomenclature', {
                                        "searchData": event.searchData
                                    },
                                    function (js) {
                                        //finsession(js);
                                        var ids = [];
                                        js.rs.forEach(function (d) {
                                            jsNomen.forEach(function (l, i) {
                                                if (l.id_nomenclature == d)
                                                    ids.push(i);
                                            });
                                        });
                                        grid.last.searchIds = ids;
                                        grid.total = grid.last.searchIds.length;
                                        grid.buffered = grid.total;
                                        grid.refresh();
                                        w2alert(js.message);
                                    }, "json");
                            }
                        } else {
                            grid.localSearch();
                            event.onComplete = function () {
                                grid.last.searchIds = grid.last.searchIds;
                                grid.total = grid.last.searchIds.length;
                                grid.buffered = grid.total;
                                grid.refresh();
                            }
                        }
                    },
                }))
            // Création du formulaire d'ajout de nomenclature
            function openPopupN() {
                if (!w2ui.foo3) {
                    $().w2form({
                        name: 'foo3',
                        style: 'border: 0px; background-color: transparent;',
                        formHTML: '<div class="w2ui-page page-0">' +
                            '    <div class="w2ui-field">' +
                            '        <label>Code:</label>' +
                            '        <div>' +
                            '           <input name="code" type="text" maxlength="100" style="width: 250px"/>' +
                            '        </div>' +
                            '    </div>' +
                            '    <div class="w2ui-field">' +
                            '        <label>Label:</label>' +
                            '        <div>' +
                            '            <input name="label" type="text" maxlength="100" style="width: 250px"/>' +
                            '        </div>' +
                            '    </div>' +
                            '    <div class="w2ui-field">' +
                            '        <label>ID Parent:</label>' +
                            '        <div>' +
                            '            <input name="id_parent" type="text" style="width: 250px"/>' +
                            '        </div>' +
                            '    </div>' +
                            '    <div class="w2ui-field">' +
                            '        <label>Catégorie Parent:</label>' +
                            '        <div>' +
                            '            <input name="label_parent" type="text" style="width: 250px"/>' +
                            '        </div>' +
                            '    </div>' +
                            '</div>' +
                            '<div class="w2ui-buttons">' +
                            '    <button class="w2ui-btn" name="reset">Reset</button>' +
                            '    <button class="w2ui-btn" name="save">Save</button>' +
                            '</div>',
                        fields: [{
                                field: 'code',
                                type: 'text',
                                required: true
                            },
                            {
                                field: 'label',
                                type: 'text',
                                required: true
                            },
                            {
                                field: 'id_parent',
                                type: 'text',
                                required: true
                            },
                            {
                                field: 'label_parent',
                                type: 'text',
                                required: true
                            }
                        ],
                        actions: {
                            "save": function () {
                                var errors = this.validate();
                                if (errors.length > 0) return;
                                var data = this.record;
                                data.obj = "nomenclature";
                                $.get('mailing/insert',
                                    data,
                                    function (js) {
                                        //finsession(js);
                                        w2ui['grid4'].add(js.rs);
                                    }, "json");
                                w2popup.close();
                            },
                            "reset": function () {
                                this.clear();
                            }
                        }
                    });
                }
                $().w2popup('open', {
                    title: 'Formulaire Nomenclature',
                    body: '<div id="form" style="width: 100%; height: 100%;"></div>',
                    style: 'padding: 15px 0px 0px 0px',
                    width: 500,
                    height: 300,
                    showMax: true,
                    onToggle: function (event) {
                        $(w2ui.foo.box).hide();
                        event.onComplete = function () {
                            $(w2ui.foo.box).show();
                            w2ui.foo.resize();
                        }
                    },
                    onOpen: function (event) {
                        event.onComplete = function () {
                            // specifying an onOpen handler instead is equivalent to specifying an onBeforeOpen handler, which would make this code execute too early and hence not deliver.
                            $('#w2ui-popup #form').w2render('foo3');
                        }
                    }
                });
            }
            // Création de la grille historique des envois / nomenclature
            w2ui['layout3'].content('main',
                $().w2grid({
                    name: 'grid6',
                    header: 'Historique des envois',
                    show: {
                        header: true,
                        toolbar: true,
                    },
                    multiSearch: true,
                    searches: [{
                        field: 'date_envoi',
                        caption: 'Date dernier mail',
                        type: 'date'
                    }, ],
                    columns: [{
                            field: 'recid',
                            caption: 'ID',
                            size: '50px',
                            sortable: true,
                            resizable: true
                        },
                        {
                            field: 'date_envoi',
                            caption: 'Date dernier mail',
                            type: 'date',
                            size: '20%'
                        },
                        {
                            field: 'nombre_mail',
                            caption: 'Nombre de mails envoyé',
                            type: 'text',
                            size: '20%'
                        }
                    ],
                    records: [{
                        recid: 1,
                        fname: 'John',
                        lname: 'Doe',
                        email: 'jdoe@gmail.com',
                        sdate: '4/3/2012'
                    }]
                }))
            // Création du layout esclave (Affiliations)
            var pstyle = 'background-color: #F0F0C1; border: 1px solid #dfdfdf; padding: 5px;';
                w2ui['layout3'].content('bottom',
                $().w2layout({
                    name: 'layout7',
                    panels: [{
                        type: 'left',
                        size: '50%',
                        resizable: true,
                        hidden: false,
                        style: pstyle,
                        content: ''
                    },
                    {
                        type: 'main',
                        resizable: true,
                        hidden: false,
                        style: pstyle,
                        content: ''
                    }
                ]
            }))
            // Création de la grille esclaves affiliation
            w2ui['layout7'].content('left',
                $().w2grid({
                    name: 'grid14',
                    header: 'Prospects liés aux nomenclatures',
                    show: {
                        header: true,
                        toolbar: true,
                        footer: true,
                        selectColumn: true,
                        toolbarAdd: true,
                        toolbarDelete: true
                    },
                    toolbar: {
                        items: [{
                            id: 'export',
                            type: 'button',
                            text: 'Exporter',
                            icon: 'fas fa-file-export'
                        }],
                        onClick: function (event) {
                            if (event.target == 'export') {
                                var ids = w2ui.grid14.getSelection();
                                exportByPost(ids, "prospect");
                                //open(urlP + 'export?obj=prospect&ids=' + ids, "_blank");
                            }
                        }
                    },
                    columns: [{
                            field: 'recid',
                            caption: 'ID',
                            size: '50px',
                            hidden: true,
                            sortable: true,
                            resizable: true
                        },
                        {
                            field: 'nom_prenom',
                            caption: 'Nom Prénom',
                            size: '40%',
                            type: 'text'
                        },
                        {
                            field: 'email',
                            caption: 'Email',
                            size: '20%',
                            type: 'text'
                        },
                        {
                            field: 'unsub',
                            caption: 'Unsubscribe',
                            size: '30%',
                            type: 'text'
                        }
                    ],
                    onAdd: function (event) {
                        //openPopupP();
                    },
                    onDelete: function (event) {
                        var itemsSelect = w2ui.grid4.getSelection();
                        var p = {
                            idsNomenclature: itemsSelect,
                            obj: 'prospectxnomenclature'
                        };
                        if (event.force) {
                            var s = w2ui[event.target].getSelection();
                            p.idsProspect = s;
                            $.get('mailing/delete',
                                p,
                                function (js) {
                                    // finsession(js);
                                    w2alert(js.message);
                                }, "json");
                        }
                    },
                    
                }))
            // Création de la grille esclaves nomenclature
            w2ui['layout7'].content('main',
                $().w2grid({
                    name: 'grid15',
                    header: 'Affiliations liées aux nomenclatures',
                    show: {
                        header: true,
                        toolbar: false,
                        footer: true,
                        toolbarAdd: false,
                        toolbarDelete: false,
                        selectColumn: true
                    },
                    columns: [{
                            field: 'recid',
                            caption: 'ID',
                            size: '50px',
                            hidden: true,
                            sortable: true,
                            resizable: true
                        },
                        {
                            field: 'affiliation1',
                            caption: 'Affiliation 1',
                            size: '30%',
                            type: 'text'
                        },
                        {
                            field: 'affiliation2',
                            caption: 'Affiliation 2',
                            size: '30%',
                            type: 'text'
                        },
                        {
                            field: 'affiliation3',
                            caption: 'Affiliation 3',
                            size: '30%',
                            type: 'text'
                            
                        },
                    ],
                    /*
                    onAdd: function (event) {
                        //openPopupP();
                    },
                    onDelete: function (event) {
                        var itemsSelect = w2ui.grid.getSelection();
                        var p = {
                            id: itemsSelect,
                            obj: 'prospect'
                        };
                        if (event.force) {
                            $.get('mailing/delete',
                                p,
                                function (js) {
                                    // finsession(js);
                                    w2alert(js.message);
                                }, "json");
                        }
                    },
                    */
                }))

            // Création du layout 4e onglet (Import)
            var pstyle = 'background-color: #F0F0C1; border: 1px solid #dfdfdf; padding: 5px;';
            $('#tab4').w2layout({
                name: 'layout4',
                panels: [{
                    type: 'left',
                    size: '20%',
                    resizable: true,
                    hidden: false,
                    style: pstyle,
                    content: ''
                },
                {
                    type: 'main',
                    size: '80%',
                    resizable: true,
                    hidden: false,
                    style: pstyle,
                    content: ''
                }
                ]
            })
            // Création du sidebar , Choix fichier import
            w2ui['layout4'].content('left',
                $().w2grid({
                    name: 'grid20',
                    header: 'Historique des imports',
                    show: {
                        header: true,
                        toolbar: true,
                        footer: true,
                        selectColumn: true
                    },
                    columns: [{
                            field: 'recid',
                            caption: 'ID',
                            size: '10%',
                            sortable: true,
                            resizable: true
                        },
                        {
                            field: 'nom',
                            caption: 'Nom du Fichier',
                            size: '50%',
                            sortable: true,
                            resizable: true
                        },
                        {
                            field: 'reception',
                            caption: 'Date Import',
                            size: '30%',
                            sortable: true,
                            resizable: true
                        }
                    ],
                    records: jsImpfic,
                    toolbar: {
                        items: [{
                            id: 'import',
                            type: 'button',
                            text: 'Importer',
                            icon: 'fas fa-file-import'
                        }],
                        onClick: function (event) {
                            if (event.target == 'import') {
                                openPopupImportData();
                            }
                        }
                    },
                    onSelect: function (event) {
                        if (record && record.recid == event.recid) return;
                        var record = this.get(event.recid);
                        // Grille secondaire Prospect -> Affiliations
                        w2ui['grid7'].clear();
                        $.get('mailing/datafic',
						{id_importfic:record.recid},
			            function(js){
                            //finsession(js);
                            w2ui['grid7'].add(js.rs);
                            voirCouleur(js.rs);
                            w2ui['grid7'].refresh();
                        },"json");
                    }
                }))
            // Création de la grille import
            w2ui['layout4'].content('main',
                $().w2grid({
                    name: 'grid7',
                    header: 'Détails imports',
                    show: {
                        header: true,
                        toolbar: true,
                        footer: true,
                        selectColumn: true
                    },
                    columns: [{
                            field: 'recid',
                            caption: 'ID',
                            size: '50px',
                            hidden: true,
                            sortable: true,
                            resizable: true
                        },
                        {
                            field: 'col1',
                            caption: 'URL Labo',
                            size: '40%',
                            type: 'text'
                        },
                        {
                            field: 'col2',
                            caption: 'Nom Prénom',
                            size: '20%',
                            type: 'text'
                        },
                        {
                            field: 'col3',
                            caption: 'Affiliation 1',
                            size: '20%',
                            type: 'text'
                        },
                        {
                            field: 'col4',
                            caption: 'Affiliation 2',
                            size: '20%',
                            type: 'text'
                        },
                        {
                            field: 'col5',
                            caption: 'Affiliation 3',
                            size: '30%',
                            type: 'text'

                        },
                        {
                            field: 'col6',
                            caption: 'Adresse',
                            size: '30%',
                            type: 'text'
                        },
                        {
                            field: 'col7',
                            caption: 'Ville CP',
                            size: '30%',
                            type: 'text'
                        },
                        {
                            field: 'col8',
                            caption: 'Pays',
                            size: '30%',
                            type: 'text'
                        },
                        {
                            field: 'col9',
                            caption: 'Code 1',
                            size: '30%',
                            type: 'text'
                        },
                        {
                            field: 'col10',
                            caption: 'Code 2',
                            size: '30%',
                            type: 'text'
                        },
                        {
                            field: 'col11',
                            caption: 'Code 3',
                            size: '30%',
                            type: 'text'
                        },
                        {
                            field: 'creation',
                            caption: 'Date Import',
                            size: '30%',
                            type: 'text'
                        },
                        {
                            field: 'col14',
                            caption: 'Origine',
                            size: '30%',
                            type: 'text'
                        },
                        {
                            field: 'col15',
                            caption: 'Email',
                            size: '30%',
                            type: 'text'
                        },
                        {
                            field: 'col16',
                            caption: 'Unsubscribe',
                            size: '30%',
                            type: 'text'
                        },
                        {
                            field: 'commentaire',
                            caption: 'Commentaire',
                            size: '30%',
                            type: 'text'
                        }
                    ],
                }))
        });

        // Fonction pour ouvrir la popup : importer les fichiers
        function openPopupImportData() {
            w2popup.open({
                title: 'Importation des fichiers prospects',
                body: '<iframe height="100%" width="100%" scrolling="no" src="mailing/import"></iframe>',
                width: 1080,
                height: 740,
                overflow: 'hidden',
                color: '#333',
                speed: '0.3',
                opacity: '0.8',
                modal: true,
                showClose: true,
                showMax: false,
            });
        };
        //Fonction de modification de couleur du background import
        function voirCouleur(e) {
            e.forEach(function(d){
                if (d.commentaire !== null) {
                    d.w2ui = {'style':'background-color:#FF011B'};
                } 
                else 
                {
                    d.w2ui = {'style':'background-color:#C2F5B4'};
                }
            })   
        }; 
    </script>

</body>

</html>