<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>app_mailing</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <script type="text/javascript" src="http://rawgit.com/vitmalina/w2ui/master/dist/w2ui.min.js"></script>
    <link rel="stylesheet" type="text/css" href="http://rawgit.com/vitmalina/w2ui/master/dist/w2ui.min.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
        integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
</head>

<body>
    <div id="tab-example">
        <div id="tabs" style="width: 100%; height: 29px;"></div>
        <div id="tab1" class="tab">
            <div id="layout" style="width: 100%; height: 800px;"></div>
        </div>
        <div id="tab2" class="tab">
            <div id="layout2" style="width: 100%; height: 800px;"></div>
        </div>
    </div>

    <script type="text/javascript">
        var jsNomen = <?php echo $this->jsNomen; ?>;
        var jsProsp = <?php echo $this->jsProsp; ?>;
        var jsEtab = <?php echo $this->jsEtab; ?>;
        var urlP = "../";

        function exportByPost(ids, obj) {
            var form = document.getElementById("exportPostForm");
            if (form) {
                form.ids.value = ids;
                form.obj.value = obj;
            } else {
                var form = document.createElement("form");
                form.setAttribute("id", "exportPostForm");
                form.setAttribute("method", "post");
                form.setAttribute("action", "export");

                form.setAttribute("target", "view");

                var hiddenField = document.createElement("input");
                hiddenField.setAttribute("type", "hidden");
                hiddenField.setAttribute("name", "ids");
                hiddenField.setAttribute("value", ids);
                form.appendChild(hiddenField);
                hiddenField = document.createElement("input");
                hiddenField.setAttribute("type", "hidden");
                hiddenField.setAttribute("name", "obj");
                hiddenField.setAttribute("value", obj);
                form.appendChild(hiddenField);
                document.body.appendChild(form);
            }
            window.open('', 'view');
            form.submit();

        }

        //var arrListes = [];

        // Création des tabs
        var config = {
            tabs: {
                name: 'tabs',
                active: 'tab1',
                tabs: [{
                        id: 'tab1',
                        caption: 'Prospects'
                    },
                    {
                        id: 'tab2',
                        caption: 'Paramètres'
                    },
                ],
                onClick: function (event) {
                    $('#tab-example .tab').hide();
                    $('#tab-example #' + event.target).show();
                }
            }
        }

        $(function () {
            $('#tabs').w2tabs(config.tabs);
            $('#tab1').show();


            // Création du layout 1er onglet (Prospects)
            var pstyle = 'background-color: #F0F0C1; border: 1px solid #dfdfdf; padding: 5px;';
            $('#layout').w2layout({
                name: 'layout',
                panels: [{
                        type: 'left',
                        size: '60%',
                        resizable: true,
                        hidden: false,
                        style: pstyle,
                        content: ''
                    },
                    {
                        type: 'main',
                        resizable: true,
                        hidden: false,
                        style: pstyle,
                        content: ''
                    },
                    {
                        type: 'right',
                        size: 600,
                        resizable: true,
                        hidden: true,
                        style: pstyle
                    }
                ]
            })

            w2ui['layout'].content('left',
                    $('#grid').w2grid({
                        name: 'grid',
                        header: 'Grille Prospects',
                        show: {
                            header: true,
                            toolbar: true,
                            footer: true,
                            selectColumn: true,
                            toolbarAdd: true,
                            toolbarDelete: true,
                            toolbarSave: true
                        },
                        multiSearch: true,
                        searches: [{
                                field: 'nom_prenom',
                                caption: 'Nom_Prénom',
                                type: 'text'
                            },
                            {
                                field: 'email',
                                caption: 'Email',
                                type: 'text'
                            },
                            {
                                field: 'url_labo_etab',
                                caption: 'URL Labo',
                                type: 'text'
                            },
                            {
                                field: 'clientIste_prospect',
                                caption: 'Client Iste',
                                type: 'combo',
                                options: {
                                    items: ['oui', 'non']
                                }
                            },
                            {
                                field: 'membreEdito_prospect',
                                caption: 'Membre editorial',
                                type: 'combo',
                                options: {
                                    items: ['oui', 'non']
                                }
                            },
                            {
                                field: 'unsub',
                                caption: 'Unsubscribe',
                                type: 'combo',
                                options: {
                                    items: ['oui', 'non']
                                }
                            }
                        ],
                        columns: [{
                                field: 'recid',
                                caption: 'ID',
                                size: '50px',
                                sortable: true,
                                resizable: true
                            },
                            {
                                field: 'nom_prenom',
                                caption: 'Nom_Prénom',
                                size: '40%',
                                editable: {
                                    type: 'text'
                                }
                            },
                            {
                                field: 'email_prospect',
                                caption: 'Email',
                                size: '40%',
                                editable: {
                                    type: 'text'
                                }
                            },
                            {
                                field: 'email2_prospect',
                                caption: 'Email2',
                                size: '120px',
                                editable: {
                                    type: 'text'
                                }
                            },
                            {
                                field: 'code_nomen1',
                                caption: 'Code Nomenclature 1',
                                size: '120px',
                                editable: {
                                    type: 'text'
                                }
                            },
                            {
                                field: 'code_nomen2',
                                caption: 'Code Nomenclature 2',
                                size: '120px',
                                editable: {
                                    type: 'text'
                                }
                            },
                            {
                                field: 'code_nomen3',
                                caption: 'Code Nomenclature 3',
                                size: '120px',
                                editable: {
                                    type: 'text'
                                }
                            },
                            {
                                field: 'url_labo_etab',
                                caption: 'URL Labo',
                                size: '40%',
                                editable: {
                                    type: 'text'
                                }
                            },
                            {
                                field: 'langue_prospect',
                                caption: 'Langue',
                                size: '30%',
                                editable: {
                                    type: 'text'
                                }
                            },
                            {
                                field: 'clientIste_prospect',
                                caption: 'Client Iste',
                                size: '30%',
                                editable: {
                                    type: 'text'
                                }
                            },
                            {
                                field: 'membreEdito_prospect',
                                caption: 'Membre editorial',
                                size: '30%',
                                editable: {
                                    type: 'text'
                                }
                            },
                            {
                                field: 'unsub',
                                caption: 'Unsubscribe',
                                size: '30%',
                                editable: {
                                    type: 'text'
                                }
                            }
                        ],
                        toolbar: {
                            items: [{
                                    id: 'export',
                                    type: 'button',
                                    caption: 'Exporter',
                                    icon: 'fas fa-file-export'
                                },
                                {
                                    id: 'import',
                                    type: 'button',
                                    caption: 'Importer',
                                    icon: 'fas fa-file-import'
                                }
                            ],
                            onClick: function (event) {
                                if (event.target == 'export') {
                                    var ids = w2ui.grid.getSelection();
                                    exportByPost(ids, "prospect");
                                    open(urlP + 'export?obj=email_prospect&ids=' + ids, "_blank");
                                }
                                if (event.target == 'import') {
		                	        openPopupImportData();
		                        }
                            }
                        },
                        records: jsProsp,
                        onSave: function (event) {
                            var changes = w2ui['grid'].getChanges();
                            changes.forEach(function (c, i) {
                                c.obj = 'prospect';
                                $.get('mailing/update',
                                    c,
                                    function (js) {
                                        //finsession(js);		
                                        js.rs.text = js.rs.nom + " " + js.rs.prenom;
                                        setListe(js.rs, 'prospect');
                                        if (changes.length == i + 1) w2alert(js.message);
                                    }, "json");
                            });
                        },
                        onAdd: function (event) {
                            w2ui['layout'].hide('left', true);
                            w2ui['layout'].hide('main', true);
                            w2ui['layout'].toggle('right', true);
                        },
                        onDelete: function (event) {
                            var itemsSelect = w2ui.grid.getSelection();
                            var p = {
                                id: itemsSelect,
                                obj: 'prospect'
                            };
                            if (event.force) {
                                $.get('mailing/delete',
                                    p,
                                    function (js) {
                                        // finsession(js);
                                        w2alert(js.message);
                                    }, "json");
                            }
                        },
                        onSearch: function (event) {
                            var grid = this;
                            if (event.searchField == "multi") {
                                event.onComplete = function () {
                                    $.get('cherche/mailing', {
                                            "searchData": event.searchData
                                        },
                                        function (js) {
                                            //finsession(js);
                                            var ids = [];
                                            js.rs.forEach(function (d) {
                                                jsProsp.forEach(function (l, i) {
                                                    if (l.id_prospect == d) ids
                                                        .push(i);
                                                });
                                            });
                                            grid.last.searchIds = ids;
                                            grid.total = grid.last.searchIds.length;
                                            grid.buffered = grid.total;
                                            grid.refresh();
                                            w2alert(js.message);
                                        }, "json");
                                }
                            } else {
                                grid.localSearch();
                                event.onComplete = function () {
                                    grid.last.searchIds = grid.last.searchIds;
                                    grid.total = grid.last.searchIds.length;
                                    grid.buffered = grid.total;
                                    grid.refresh();
                                }
                            }
                        },
                    })),
                w2ui['layout'].content('right',
                    $('#form').w2form({
                        name: 'form_prospect',
                        focus: -1,
                        fields: [{
                                name: 'nom_prenom',
                                type: 'text',
                                required: true,
                                html: {
                                    caption: 'Nom_Prénom',
                                    attr: 'size="80" maxlength="80"'
                                }
                            },
                            {
                                name: 'langue_prospect',
                                type: 'text',
                                required: false,
                                html: {
                                    caption: 'Langue',
                                    attr: 'size="20"'
                                }
                            },
                            {
                                name: 'url_labo_etab',
                                type: 'text',
                                required: false,
                                html: {
                                    caption: 'URL Labo',
                                    attr: 'size="20"'
                                }
                            },
                            {
                                name: 'email_prospect',
                                type: 'text',
                                required: true,
                                html: {
                                    caption: 'Email',
                                    attr: 'size="70"'
                                }
                            },
                            {
                                name: 'email2_prospect',
                                type: 'text',
                                required: false,
                                html: {
                                    caption: 'Email 2',
                                    attr: 'size="70"'
                                }
                            },
                            {
                                name: 'code_nomen1',
                                type: 'text',
                                required: false,
                                html: {
                                    caption: 'Code Nomenclature 1',
                                    attr: 'size="4"'
                                }
                            },
                            {
                                name: 'code_nomen2',
                                type: 'text',
                                required: false,
                                html: {
                                    caption: 'Code Nomenclature 2',
                                    attr: 'size="4"'
                                }
                            },
                            {
                                name: 'code_nomen3',
                                type: 'text',
                                required: false,
                                html: {
                                    caption: 'Code Nomenclature 3',
                                    attr: 'size="4"'
                                }
                            },
                            {
                                name: 'clientIste_prospect',
                                type: 'text',
                                required: false,
                                html: {
                                    caption: 'Client Iste oui/non',
                                    attr: 'size="03"'
                                }
                            },
                            {
                                name: 'membreEdito_prospect',
                                type: 'text',
                                required: false,
                                html: {
                                    caption: 'membre Edito oui/non',
                                    attr: 'size="03"'
                                }
                            },
                            {
                                name: 'unsub',
                                type: 'check',
                                required: false,
                                html: {
                                    caption: 'Unsubscribe'
                                }
                            }
                        ],
                        actions: {
                            Save: function () {
                                var errors = this.validate();
                                if (errors.length > 0) return;
                                var data = this.record;
                                data.obj = "prospect";
                                $.get('mailing/insert',
                                    data,
                                    function (js) {
                                        //finsession(js);
                                        w2alert(js.message);
                                    }, "json");
                            }
                        }
                    }))


            w2ui['layout'].content('main',
                $('#grid2').w2grid({
                    name: 'grid2',
                    header: 'Historique des envois',
                    show: {
                        header: true,
                        toolbar: true,
                    },
                    multiSearch: true,
                    searches: [{
                        field: 'date_envoi',
                        caption: 'Date dernier mail',
                        type: 'date'
                    }, ],
                    columns: [{
                            field: 'date_envoi',
                            caption: 'Date dernier mail',
                            type: 'date',
                            size: '20%'
                        },
                        {
                            field: 'nombre_mail',
                            caption: 'Nombre de mails envoyé',
                            type: 'text',
                            size: '20%'
                        },
                        {
                            field: 'date_creation',
                            caption: 'Date de création prospect',
                            type: 'date',
                            size: '20%'
                        },
                        {
                            field: 'date_unsub',
                            caption: 'Date de désinscription',
                            type: 'date',
                            size: '20%'
                        }
                    ],
                    records: [{
                        recid: 1,
                        fname: 'John',
                        lname: 'Doe',
                        email: 'jdoe@gmail.com',
                        sdate: '4/3/2012'
                    }]
                }))

            // Création du layout 2e onglet (Paramètres)
            var pstyle = 'background-color: #F0F0C1; border: 1px solid #dfdfdf; padding: 5px;';
            $('#layout2').w2layout({
                name: 'layout2',
                panels: [{
                        type: 'top',
                        size: 600,
                        resizable: true,
                        hidden: true,
                        style: pstyle,
                        content: ''
                    },
                    {
                        type: 'left',
                        size: '70%',
                        resizable: true,
                        hidden: false,
                        style: pstyle,
                        content: ''
                    },
                    {
                        type: 'main',
                        resizable: true,
                        hidden: false,
                        style: pstyle,
                        content: ''
                    },
                    {
                        type: 'right',
                        size: 600,
                        resizable: true,
                        hidden: true,
                        style: pstyle
                    }
                ]
            })

            w2ui['layout2'].content('left',
                    $('#grid3').w2grid({
                        name: 'grid3',
                        header: 'Etablissement',
                        show: {
                            header: true,
                            toolbar: true,
                            footer: true,
                            selectColumn: true,
                            toolbarAdd: true,
                            toolbarDelete: true,
                            toolbarSave: true
                        },
                        multiSearch: true,
                        searches: [{
                                field: 'affiliation1_etab',
                                caption: 'Affiliation 1',
                                type: 'text'
                            },
                            {
                                field: 'affiliation2_etab',
                                caption: 'Affiliation 2',
                                type: 'text'
                            },
                            {
                                field: 'affiliation3_etab',
                                caption: 'Affiliation 3',
                                type: 'text'
                            },
                            {
                                field: 'responsableLabo_etab',
                                caption: 'Responsable Labo',
                                type: 'text'
                            }
                        ],
                        columns: [{
                                field: 'url_labo_etab',
                                caption: 'URL du Labo',
                                size: '40%',
                                editable: {
                                    type: 'text'
                                }
                            },
                            {
                                field: 'adresse_etab',
                                caption: 'Adresse',
                                size: '40%',
                                editable: {
                                    type: 'text'
                                }
                            },
                            {
                                field: 'ville_etab',
                                caption: 'Ville',
                                size: '120px',
                                editable: {
                                    type: 'text'
                                }
                            },
                            {
                                field: 'cp_etab',
                                caption: 'Code Postal',
                                size: '30%',
                                editable: {
                                    type: 'int'
                                }
                            },
                            {
                                field: 'pays_etab',
                                caption: 'Pays',
                                size: '30%',
                                editable: {
                                    type: 'text'
                                }
                            },
                            {
                                field: 'responsableLabo_etab',
                                caption: 'Responsable du Labo',
                                size: '30%',
                                editable: {
                                    type: 'text'
                                }
                            },
                            {
                                field: 'affiliation1_etab',
                                caption: 'Affiliation 1',
                                size: '30%',
                                editable: {
                                    type: 'text'
                                }
                            },
                            {
                                field: 'affiliation2_etab',
                                caption: 'Affiliation 2',
                                size: '30%',
                                editable: {
                                    type: 'text'
                                }
                            },
                            {
                                field: 'affiliation3_etab',
                                caption: 'Affiliation 3',
                                size: '30%',
                                editable: {
                                    type: 'text'
                                }
                            },
                            {
                                field: 'origine_etab',
                                caption: 'Origine Etablissement',
                                size: '30%',
                                editable: {
                                    type: 'text'
                                }
                            },
                        ],
                        toolbar: {
                            items: [{
                                id: 'import',
                                type: 'button',
                                caption: 'Importer',
                                icon: 'fas fa-file-import'
                            }],
                            onClick: function (event) {
                                if (event.target == 'import') {
                                    openPopupImportData();
                                }
                            }
                        },
                        records: jsEtab,
                        onSave: function (event) {
                            var changes = w2ui['grid3'].getChanges();
                            changes.forEach(function (c, i) {
                                c.obj = 'etab';
                                $.get('mailing/update',
                                    c,
                                    function (js) {
                                        //finsession(js);		
                                        js.rs.text = js.rs.nom + " " + js.rs.prenom;
                                        setListe(js.rs, 'etab');
                                        if (changes.length == i + 1) w2alert(js.message);
                                    }, "json");
                            });
                        },
                        onAdd: function (event) {
                            w2ui['layout2'].toggle('top', true);
                            w2ui['layout2'].hide('left', true);
                            w2ui['layout2'].hide('main', true);
                            w2ui['layout2'].hide('right', true);
                        },
                        onDelete: function (event) {
                            var itemsSelect = w2ui.grid3.getSelection();
                            var p = {
                                id: itemsSelect,
                                obj: 'etab'
                            };
                            if (event.force) {
                                $.get('mailing/delete',
                                    p,
                                    function (js) {
                                        // finsession(js);
                                        w2alert(js.message);
                                    }, "json");
                            }
                        },
                        onSearch: function (event) {
                            var grid = this;
                            if (event.searchField == "multi") {
                                event.onComplete = function () {
                                    $.get('cherche/mailing', {
                                            "searchData": event.searchData
                                        },
                                        function (js) {
                                            //finsession(js);
                                            var ids = [];
                                            js.rs.forEach(function (d) {
                                                jsEtab.forEach(function (l, i) {
                                                    if (l.id_etab == d) ids
                                                        .push(i);
                                                });
                                            });
                                            grid.last.searchIds = ids;
                                            grid.total = grid.last.searchIds.length;
                                            grid.buffered = grid.total;
                                            grid.refresh();
                                            w2alert(js.message);
                                        }, "json");
                                }
                            } else {
                                grid.localSearch();
                                event.onComplete = function () {
                                    grid.last.searchIds = grid.last.searchIds;
                                    grid.total = grid.last.searchIds.length;
                                    grid.buffered = grid.total;
                                    grid.refresh();
                                }
                            }
                        },
                    })),
                w2ui['layout2'].content('top',
                    $('#form3').w2form({
                        name: 'form_etab',
                        focus: -1,
                        fields: [{
                                name: 'url_labo_etab',
                                type: 'text',
                                required: true,
                                html: {
                                    caption: 'URL Labo',
                                    attr: 'size="80" maxlength="80"'
                                }
                            },
                            {
                                name: 'adresse_etab',
                                type: 'text',
                                required: false,
                                html: {
                                    caption: 'Adresse',
                                    attr: 'size="20"'
                                }
                            },
                            {
                                name: 'ville_etab',
                                type: 'text',
                                required: false,
                                html: {
                                    caption: 'Ville',
                                    attr: 'size="20"'
                                }
                            },
                            {
                                name: 'cp_etab',
                                type: 'text',
                                required: true,
                                html: {
                                    caption: 'Code Postal',
                                    attr: 'size="10"'
                                }
                            },
                            {
                                name: 'pays_etab',
                                type: 'text',
                                required: false,
                                html: {
                                    caption: 'Pays',
                                    attr: 'size="70"'
                                }
                            },
                            {
                                name: 'responsableLabo_etab',
                                type: 'text',
                                required: false,
                                html: {
                                    caption: 'Responsable du Labo',
                                    attr: 'size="45"'
                                }
                            },
                            {
                                name: 'affiliation1_etab',
                                type: 'text',
                                required: true,
                                html: {
                                    caption: 'Affiliation 1',
                                    attr: 'size="45"'
                                }
                            },
                            {
                                name: 'affiliation2_etab',
                                type: 'text',
                                required: false,
                                html: {
                                    caption: 'Affiliation 2',
                                    attr: 'size="45"'
                                }
                            },
                            {
                                name: 'affiliation3_etab',
                                type: 'text',
                                required: false,
                                html: {
                                    caption: 'Affiliation 3',
                                    attr: 'size="45"'
                                }
                            },
                            {
                                name: 'origine_etab',
                                type: 'text',
                                required: false,
                                html: {
                                    caption: 'Origine',
                                    attr: 'size="45"'
                                }
                            }
                        ],
                        actions: {
                            Save: function () {
                                var errors = this.validate();
                                if (errors.length > 0) return;
                                var data = this.record;
                                data.obj = "etab";
                                $.get('mailing/insert',
                                    data,
                                    function (js) {
                                        //finsession(js);
                                        w2alert(js.message);
                                    }, "json");
                            }
                        }
                    }))


            w2ui['layout2'].content('main',
                $('#grid4').w2grid({
                    name: 'grid4',
                    header: 'Nomenclature',
                    show: {
                        header: true,
                        toolbar: true,
                        toolbarReload: true,
                        toolbarColumns: true,
                        toolbarSearch: true,
                        toolbarAdd: true,
                        toolbarDelete: true,
                        toolbarSave: true,
                        selectColumn: true,
                        footer: true
                    },
                    multiSearch: true,
                    searches: [{
                            field: 'label_parent',
                            caption: 'Catégorie Parent',
                            type: 'text'
                        },
                        {
                            field: 'label',
                            caption: 'label',
                            type: 'text'
                        },
                        {
                            field: 'code',
                            caption: 'code',
                            type: 'text'
                        }
                    ],
                    columns: [{
                            field: 'recid',
                            caption: 'ID',
                            size: '50px',
                            sortable: true,
                            resizable: true
                        },
                        {
                            field: 'code',
                            caption: 'Code',
                            size: '20%',
                            editable: {
                                type: 'text'
                            }
                        },
                        {
                            field: 'label',
                            caption: 'Label',
                            size: '40%',
                            editable: {
                                type: 'text'
                            }
                        }
                    ],
                    records: jsNomen,
                    onSave: function (event) {
                        var changes = w2ui['grid4'].getChanges();
                        changes.forEach(function (c, i) {
                            c.obj = 'nomenclature';
                            $.get('mailing/update',
                                c,
                                function (js) {
                                    //finsession(js);		
                                    js.rs.text = js.rs.nom + " " + js.rs.prenom;
                                    setListe(js.rs, 'nomenclature');
                                    if (changes.length == i + 1) w2alert(js.message);
                                }, "json");
                        });
                    },
                    onAdd: function (event) {
                        w2ui['layout2'].hide('top', true)
                        w2ui['layout2'].hide('left', true);
                        w2ui['layout2'].hide('main', true);
                        w2ui['layout2'].toggle('right', true);
                    },
                    onDelete: function (event) {
                        var itemsSelect = w2ui.grid4.getSelection();
                        var p = {
                            id: itemsSelect,
                            obj: 'nomenclature'
                        };
                        if (event.force) {
                            $.get('mailing/delete',
                                p,
                                function (js) {
                                    // finsession(js);
                                    w2alert(js.message);
                                }, "json");
                        }
                    },
                    onSearch: function (event) {
                        var grid = this;
                        if (event.searchField == "multi") {
                            event.onComplete = function () {
                                $.get('cherche/nomenclature', {
                                        "searchData": event.searchData
                                    },
                                    function (js) {
                                        //finsession(js);
                                        var ids = [];
                                        js.rs.forEach(function (d) {
                                            jsNomen.forEach(function (l, i) {
                                                if (l.id_nomenclature == d)
                                                    ids.push(i);
                                            });
                                        });
                                        grid.last.searchIds = ids;
                                        grid.total = grid.last.searchIds.length;
                                        grid.buffered = grid.total;
                                        grid.refresh();
                                        w2alert(js.message);
                                    }, "json");
                            }
                        } else {
                            grid.localSearch();
                            event.onComplete = function () {
                                grid.last.searchIds = grid.last.searchIds;
                                grid.total = grid.last.searchIds.length;
                                grid.buffered = grid.total;
                                grid.refresh();
                            }
                        }
                    },
                }))
            w2ui['layout2'].content('right',
                $('#form2').w2form({
                    name: 'form_nomenclature',
                    focus: -1,
                    fields: [{
                            name: 'code',
                            type: 'text',
                            required: true,
                            html: {
                                caption: 'Code',
                                attr: 'size="40" maxlength="40"'
                            }
                        },
                        {
                            name: 'label',
                            type: 'text',
                            required: true,
                            html: {
                                caption: 'Label',
                                attr: 'size="40"'
                            }
                        },
                    ],
                    actions: {
                        Save: function () {
                            var errors = this.validate();
                            if (errors.length > 0) return;
                            var data = this.record;
                            data.obj = "nomenclature";
                            $.get('mailing/insert',
                                data,
                                function (js) {
                                    //finsession(js);
                                    w2alert(js.message);
                                }, "json");
                        }
                    }
                }))
        });
        function openPopupImportData () {

w2popup.open({
    title: 'Importation des fichiers prospects',
    body: '<iframe height="100%" width="100%" scrolling="no" src="mailing/import"></iframe>',
    width     : 1080,
    height    : 740,
    overflow  : 'hidden',
    color     : '#333',
    speed     : '0.3',
    opacity   : '0.8',
    modal     : true,
    showClose : true,
    showMax   : false,
});
}
    </script>

</body>

</html>