<?php
	if($this->ajax){
		echo json_encode(array("uti"=>$this->rs,"erreur"=>$this->erreur));
	}else{
		echo '<!DOCTYPE html>
		<html>
		<head>
			<meta charset="utf-8" />
			<title>ISTE : login</title>
		    <link rel="stylesheet" type="text/css" href="../css/w2ui.min.css" />
    			<script src="../js/jquery.min.js"></script>
    			<script type="text/javascript" src="../js/w2ui.js"></script>
		</head>
		<body>
			<h4>'.$this->erreur.'</h4>
			<div id="formLogin" style="width: 750px;"></div>
		
			<script type="text/javascript">
			$(function () {
			    $("#formLogin").w2form({ 
			        name     : "formLog",
			        url      : "login",
			        header   : "ISTE login",
			        fields: [
			            { field: "login", type: "text", required: true },
			            { field: "mdp", type: "password", required: true }
			        ],
			        actions: {
			            save: function () {
			                var errors = this.validate();
			                if (errors.length > 0) return;
			                window.location.assign("login?login="+this.record.login+"&mdp="+this.record.mdp);
			            }
					}
			    });
			});
			</script>
		  </body>
		</html>	';	
	}