<?php
	$GLOBALS['toolbars'] = array(
		array(
			'Source'=>array(
				_CKE_SIZE=>'66',
				_CKE_DEFAULT=>0,
				_CKE_COMPAT=>0,
				_CKE_ICON=>0,
				_CKE_PLUGIN=>'sourcearea'
			),
		),
		array(
			'SpipSave'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>0,
				_CKE_COMPAT=>1,
				_CKE_ICON=>2
			),
			'NewPage'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>0,
				_CKE_COMPAT=>1,
				_CKE_ICON=>3,
				_CKE_PLUGIN=>'newpage'
			),
			'ZpipPreview'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>0,
				_CKE_COMPAT=>1,
				_CKE_ICON=>4
			),
		),
		array(
			'Templates'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>0,
				_CKE_COMPAT=>1,
				_CKE_ICON=>5,
				_CKE_PLUGIN=>'templates'
			),
		),
		array(
			'Cut'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>6,
				_CKE_PLUGIN=>'clipboard'
			),
			'Copy'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>7,
				_CKE_PLUGIN=>'clipboard'
			),
			'Paste'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>8,
				_CKE_PLUGIN=>'clipboard'
			),
			'PasteText'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>9,
				_CKE_PLUGIN=>'pastetext'
			),
			'PasteFromWord'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>0,
				_CKE_COMPAT=>0,
				_CKE_ICON=>10,
				_CKE_PLUGIN=>'pastefromword'
			),
		),
		array(
			'Print'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>0,
				_CKE_COMPAT=>1,
				_CKE_ICON=>11,
				_CKE_PLUGIN=>'print'
			),
			'SpellChecker'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>12,
				_CKE_PLUGIN=>'wsc'
			),
			'Scayt'=>array(
				_CKE_SIZE=>'32',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>12,
				_CKE_PLUGIN=>'scayt'
			),
		),
		array(
			'Undo'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>13,
				_CKE_PLUGIN=>'undo'
			),
			'Redo'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>14,
				_CKE_PLUGIN=>'undo'
			),
		),
		array(
			'Find'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>15,
				_CKE_PLUGIN=>'find'
			),
			'Replace'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>16,
				_CKE_PLUGIN=>'find'
			),
		),
		array(
			'SelectAll'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>17,
				_CKE_PLUGIN=>'selection'
			),
			'RemoveFormat'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>18,
				_CKE_PLUGIN=>'removeformat'
			),
		),
		array(
			'Form'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>0,
				_CKE_COMPAT=>0,
				_CKE_ICON=>47,
				_CKE_PLUGIN=>'forms'
			),
			'Checkbox'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>0,
				_CKE_COMPAT=>0,
				_CKE_ICON=>48,
				_CKE_PLUGIN=>'forms'
			),
			'Radio'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>0,
				_CKE_COMPAT=>0,
				_CKE_ICON=>49,
				_CKE_PLUGIN=>'forms'
			),
			'TextField'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>0,
				_CKE_COMPAT=>0,
				_CKE_ICON=>50,
				_CKE_PLUGIN=>'forms'
			),
			'Textarea'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>0,
				_CKE_COMPAT=>0,
				_CKE_ICON=>51,
				_CKE_PLUGIN=>'forms'
			),
			'Select'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>0,
				_CKE_COMPAT=>0,
				_CKE_ICON=>52,
				_CKE_PLUGIN=>'forms'
			),
			'Button'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>0,
				_CKE_COMPAT=>0,
				_CKE_ICON=>53,
				_CKE_PLUGIN=>'forms'
			),
			'ImageButton'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>0,
				_CKE_COMPAT=>0,
				_CKE_ICON=>54,
				_CKE_PLUGIN=>'forms'
			),
			'HiddenField'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>0,
				_CKE_COMPAT=>0,
				_CKE_ICON=>55,
				_CKE_PLUGIN=>'forms'
			),
		),
		array(
			'Bold'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>19,
				_CKE_PLUGIN=>'basicstyles'
			),
			'Italic'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>20,
				_CKE_PLUGIN=>'basicstyles'
			),
			'Underline'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>21,
				_CKE_PLUGIN=>'basicstyles'
			),
			'Strike'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>0,
				_CKE_ICON=>22,
				_CKE_PLUGIN=>'basicstyles'
			),
		),
		array(
			'Subscript'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>23,
				_CKE_PLUGIN=>'basicstyles'
			),
			'Superscript'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>24,
				_CKE_PLUGIN=>'basicstyles'
			),
		),
		array(
			'NumberedList'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>25,
				_CKE_PLUGIN=>'list'
			),
			'BulletedList'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>26,
				_CKE_PLUGIN=>'list'
			),
			'Outdent'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>27,
				_CKE_PLUGIN=>'indent'
			),
			'Indent'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>28,
				_CKE_PLUGIN=>'indent'
			),
			'Blockquote'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>0,
				_CKE_COMPAT=>0,
				_CKE_ICON=>72,
				_CKE_PLUGIN=>'blockquote'
			),
		),
		array(
			'JustifyLeft'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>29,
				_CKE_PLUGIN=>'justify'
			),
			'JustifyCenter'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>30,
				_CKE_PLUGIN=>'justify'
			),
			'JustifyRight'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>31,
				_CKE_PLUGIN=>'justify'
			),
			'JustifyBlock'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>32,
				_CKE_PLUGIN=>'justify'
			),
		),
		array(
			'Spip'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>81
			),
			'Link'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>33,
				_CKE_PLUGIN=>'link'
			),
			'Unlink'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>34,
				_CKE_PLUGIN=>'link'
			),
			'Anchor'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>35,
				_CKE_PLUGIN=>'link'
			),
			'Iframe'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>0,
				_CKE_COMPAT=>0,
				_CKE_ICON=>80,
				_CKE_PLUGIN=>'iframe'
			),
		),
		array(
			'SpipModeles'=>array(
				_CKE_SIZE=>'88',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1
			),
		),
		array(
			'SpipDoc'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>82
			),
			'Image'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>0,
				_CKE_COMPAT=>0,
				_CKE_ICON=>36,
				_CKE_PLUGIN=>'image'
			),
			'Flash'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>0,
				_CKE_COMPAT=>1,
				_CKE_ICON=>37,
				_CKE_PLUGIN=>'flash'
			),
			'Table'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>38,
				_CKE_PLUGIN=>'table'
			),
			'HorizontalRule'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>39,
				_CKE_PLUGIN=>'horizontalrule'
			),
			'Smiley'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>40,
				_CKE_PLUGIN=>'smiley'
			),
			'SpecialChar'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>41,
				_CKE_PLUGIN=>'specialchar'
			),
			'PageBreak'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>0,
				_CKE_COMPAT=>0,
				_CKE_ICON=>42,
				_CKE_PLUGIN=>'pagebreak'
			),
		),
		array(
			'Styles'=>array(
				_CKE_SIZE=>'91',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>0,
				_CKE_PLUGIN=>'stylescombo'
			),
			'Format'=>array(
				_CKE_SIZE=>'91',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_PLUGIN=>'format'
			),
			'Font'=>array(
				_CKE_SIZE=>'91',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>0,
				_CKE_PLUGIN=>'font'
			),
			'FontSize'=>array(
				_CKE_SIZE=>'56',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>0,
				_CKE_PLUGIN=>'font'
			),
		),
		array(
			'TextColor'=>array(
				_CKE_SIZE=>'32',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>0,
				_CKE_ICON=>44,
				_CKE_PLUGIN=>'colorbutton',
			),
			'BGColor'=>array(
				_CKE_SIZE=>'32',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>0,
				_CKE_ICON=>45,
				_CKE_PLUGIN=>'colorbutton',
			),
		),
		array(
			'Maximize'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>55,
				_CKE_PLUGIN=>'maximize'
			),
			'ShowBlocks'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>0,
				_CKE_COMPAT=>1,
				_CKE_ICON=>71,
				_CKE_PLUGIN=>'showblocks'
			),
			'About'=>array(
				_CKE_SIZE=>'24',
				_CKE_DEFAULT=>1,
				_CKE_COMPAT=>1,
				_CKE_ICON=>46,
				_CKE_PLUGIN=>'about'
			),
		),
	) ;
?>
