<?php 
if($this->ajax)$urlP = "../"; else $urlP = "../"  ;
if($this->inc)$urlP = "";
if(!$this->ajax){
	echo '
<!DOCTYPE HTML>
<html lang="fr">
<head>
	<meta charset="utf-8">
	<title>ISTE - importation des fichiers de vente</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="'.$urlP.'css/gestedit.css" />
		<link rel="stylesheet" href="'.$urlP.'css/w2ui.css" />	
		<link rel="stylesheet" type="text/css" href="../fonts/font-awesome/font-awesome.css" />
		<script type="text/javascript">
			var uti = '.$this->uti.';
			var fctInit;			
		</script>		
		<script type="text/javascript" src="'.$urlP.'js/jquery.min.js"></script>
		<script type="text/javascript" src="'.$urlP.'js/w2ui.js"></script>
		<script type="text/javascript" src="'.$urlP.'js/global.js"></script>
		<script type="text/javascript" src="'.$urlP.'js/data.js"></script>
		<script type="text/javascript" src="'.$urlP.'js/log.js"></script>		
		<script type="text/javascript">
			function init() {
				initFileUpload();
				fctInit = initImportVente;			
				initAll(); 
	  			if(uti.id_uti!=0)
					utiIsConnect();
	  			else
		    	  		diagLogin.showModal();				
			}
		</script>
	</head>
	<body onload="init()" >
		<p id="promptCompat">Votre navigateur ne pend pas en charge les balises <code><dialog></code></p> 
		<div id="utiConnect" style="visibility:hidden;"></div>
		<dialog id="diagLogin" close> 
			<label for="iptLogin">Login : </label>
	        <input type="text" name="iptLogin" id="iptLogin" required="required">
	        <label for="iptlogin">Mot de passe : </label>
	        <input type="password" name="iptMdp" id="iptMdp" required="required">
		    <div class="boutons">
				<button onclick="diagLogin.close()">Fermer</button> 
				<button onclick="connecte()">Connexion</button> 
			</div> 
		</dialog> ';
}
?>
	<!-- Generic page styles -->
	<link rel="stylesheet" href="<?php echo $urlP;?>css/jqfu.css">
	<!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->
	<link rel="stylesheet" href="<?php echo $urlP;?>css/bootstrap.min.css">
	<link rel="stylesheet" href="<?php echo $urlP;?>css/blueimp-gallery.min.css">
	<link rel="stylesheet" href="<?php echo $urlP;?>css/jquery.fileupload.css">
	<link rel="stylesheet" href="<?php echo $urlP;?>css/jquery.fileupload-ui.css">


	<script type="text/javascript">
<?php 
if($this->ajax)
	echo 'var urlP = "../";';
else
	echo 'var urlP = "../";';	
if($this->inc)
	echo 'urlP = "";';
?>
	</script>	

<div class="container" id="mainDivImport" >
	<div id="layoutImportFicVente" style="width: 1000px; height: 200px;"></div>    
    <!-- The file upload form used as target for the file upload widget -->
    <form id="fileupload" action="//jquery-file-upload.appspot.com/" method="POST" enctype="multipart/form-data">
        <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
        <div class="row fileupload-buttonbar">
            <div class="col-xs-2 fileupload-progress">
                <!-- The fileinput-button span is used to style the file input field as button -->
                <span class="btn btn-xs btn-success fileinput-button">
                    <i class="glyphicon glyphicon-plus"></i>
                    <span>Add files...</span>
                    <input type="file" name="files[]" multiple>
                </span>
            </div>
			<!-- The global progress state -->
            <div class="col-xs-10 fileupload-progress fade">
				<!-- The global file processing state -->
            		<span class="fileupload-process"></span>
            		<!-- The global progress bar -->
                <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                    <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                </div>
                <!-- The extended global progress state -->
                <div class="progress-extended">&nbsp;</div>
            </div>
        </div>
        <!-- The table listing the files available for upload/download -->
        <div style="height: 300px;overflow: auto;">
           <table role="presentation" class="table table-striped">
				<thead>
				    <tr>
				        <th style="width: 30%;">Fichier</th>
				        <th style="width: 20%;">Tailles</th>
				        <th style="width: 50%;">Actions</th>
				    </tr>
			    </thead>
				<tbody class="files"></tbody>
			</table>
		</div>
    </form>
    <br/><br/><br/>
</div>
<!-- The blueimp Gallery widget -->
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter=":even">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>
<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td style="width: 40%;">
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
			<input type="hidden" name="obj[]" value="<?php echo $this->obj; ?>"  />
			<input type="hidden" name="idObj[]" value="<?php echo $this->idObj; ?>"  />
			<div class="w2ui-field w2ui-span4 w2ui-required" style="">
         		<label style="width:200px;">Année fin (YYYY) : </label>
         		<div style="white-space: nowrap;">
					<input name="date_fin[]" type="number" >
	      		</div>
      		</div>
			<!--
			<div class="w2ui-field w2ui-span6 w2ui-required" style="">
         		<label>Type de fichier : </label>
				<div style="white-space: nowrap;">
					<select name="type[]" >
          				<option value="Elsevier">Elsevier</option>
          				<option value="NBN">NBN</option>
          				<option value="Wiley">Wiley</option>
					</select>
				</div>
      		</div>
			-->
        </td>
        <td style="width: 30%;">
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td style="width: 40%;">
            {% if (!i && !o.options.autoUpload) { %}
                <button class="btn btn-primary start" disabled>
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start</span>
                </button>
            {% } %}
            {% if (!i) { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td style="width: 30%;">
            <p class="name">
                {% if (file.url) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                {% } else { %}
                    <span>{%=file.name%}</span>
                {% } %}
            </p>
			<p class="type"><strong>{%=file.type||''%} {%=file.dateFin||''%}</strong></p>
            {% if (file.error) { %}
                <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td style="width: 20%;">
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
			<br/>
            <span class="size">{%=file.nbLigne%} ligne(s)</span>
			<br/>
            <span class="size">{%=file.nbVente%} vente(s)</span>
        </td>
        <td style="width: 50%;">
            {% if (file.deleteUrl) { %}
                <button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                    <i class="glyphicon glyphicon-trash"></i>
                    <span>Delete</span>
                </button>
            {% } else { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}

            {% if (file.nbLigne=="0" || file.nbLigne=="") { %}
                <button class="btn btn-warning" id="btnImp{%=file.id%}" onclick="importerData({%=file.id%},'in','global')" >
                    <i class="glyphicon glyphicon-download-alt" ></i>
                    <span>Importer</span>
                </button>
                <button class="btn btn-info hidden" id="btnVoir{%=file.id%}" onclick="voirData({%=file.id%})" >
                    <i class="glyphicon glyphicons-list-alt"></i>
                    <span>Voir</span>
                </button>
                <button class="btn btn-warning hidden" id="btnCalculer{%=file.id%}" onclick="calculerData({%=file.id%},'global')" >
                    <i class="glyphicon glyphicon-calendar"></i>
                    <span>Calculer</span>
                </button>
            {% } else { %}
                <button class="btn btn-info" id="btnVoir{%=file.id%}" onclick="voirData({%=file.id%})" >
                    <i class="glyphicon glyphicons-list-alt"></i>
                    <span>Voir</span>
                </button>
	            {% if (file.nbVente=="0" || file.nbVente=="") { %}
				<button class="btn btn-warning" id="btnCalculer{%=file.id%}" onclick="calculerData({%=file.id%},'global')" >
        		    		<i class="glyphicon glyphicon-calendar"></i>
        	    	    		<span>Calculer</span>
				</button>
	            {% } %}
            {% } %}
        </td>
    </tr>
{% } %}
</script>
<!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
<script src="<?php echo $urlP;?>js/jquery.ui.widget.js"></script>
<!-- The Templates plugin is included to render the upload/download listings -->
<script src="<?php echo $urlP;?>js/tmpl.min.js"></script>
<!-- The Load Image plugin is included for the preview images and image resizing functionality -->
<script src="<?php echo $urlP;?>js/load-image.all.min.js"></script>
<!-- The Canvas to Blob plugin is included for image resizing functionality -->
<script src="<?php echo $urlP;?>js/canvas-to-blob.min.js"></script>
<!-- Bootstrap JS is not required, but included for the responsive demo navigation -->
<script src="<?php echo $urlP;?>js/bootstrap.min.js"></script>
<!-- blueimp Gallery script -->
<script src="<?php echo $urlP;?>js/jquery.blueimp-gallery.min.js"></script>
<!-- The basic File Upload plugin -->
<script src="<?php echo $urlP;?>js/jqfu/jquery.fileupload.js"></script>
<!-- The File Upload processing plugin -->
<script src="<?php echo $urlP;?>js/jqfu/jquery.fileupload-process.js"></script>
<!-- The File Upload image preview & resize plugin -->
<script src="<?php echo $urlP;?>js/jqfu/jquery.fileupload-image.js"></script>
<!-- The File Upload audio preview plugin -->
<script src="<?php echo $urlP;?>js/jqfu/jquery.fileupload-audio.js"></script>
<!-- The File Upload video preview plugin -->
<script src="<?php echo $urlP;?>js/jqfu/jquery.fileupload-video.js"></script>
<!-- The File Upload validation plugin -->
<script src="<?php echo $urlP;?>js/jqfu/jquery.fileupload-validate.js"></script>
<!-- The File Upload user interface plugin -->
<script src="<?php echo $urlP;?>js/jqfu/jquery.fileupload-ui.js"></script>
<!-- The main application script -->
<script src="<?php echo $urlP;?>js/jqfu/main.js"></script>
<script type="text/javascript">
var pstyle = 'border: 1px solid #dfdfdf; padding: 5px;';
var idFicImport;
fuVerif = true;
function initImportVente() {
	
	config = {
		    layoutImportVente: {
		        name: 'layout_ImportVente',
		        padding: 4,
		        panels: [
					{ type: 'main', size: "1000px", resizable: true, style: pstyle},
		        ],
		    },
		    gridImportVenteData: { 
		        name: 'grid_ImportVenteData', 
				header: 'Données importées',		
		        show: { 
					header			: true,		
		            toolbar			: true,
					toolbarReload   : false,
					toolbarColumns  : true,
		            	toolbarSearch   : true,
		            	toolbarAdd      : false,
		            	toolbarDelete   : false,
		            	toolbarSave		: false,
		            	footer: true,
		        },
		        toolbar: {
		            items: [
		                { id: 'export', type: 'button', caption: 'Exporter', icon: 'fa-file' }
		            ],
		            onClick: function (event) {
		                if (event.target == 'export') {
		                		open(urlP+'export/datavente?idFic='+idFicImport,"_blank")
		                }
		            }
		        },
		        onClick: function (event) {
		            itemSelect = this.get(event.recid);
		            var g;           		           
		        }	    
		    },	    		    
		};
	
    // initialisation
    $('#layoutImportFicVente').w2layout(config.layoutImportVente);
}
    
function importerData(id, dt, tp){
	console.log("importerData : "+id);
	var e = window.event;
	var div = document.getElementById('mainDivImport');
	w2utils.lock(div, { spinner: true, opacity : 1 });
	$.get(urlP+'import/setdataficvente',
			{idFic:id, dateFin:dt, type:tp},
        		function(html){
				w2utils.unlock(div);
				w2alert(html);
				//affiche les boutons voir et calculer
				document.getElementById('btnVoir'+id).className = 'btn btn-info';				
				document.getElementById('btnCalculer'+id).className = 'btn btn-warning';								
				//cache le bouton importer
				document.getElementById('btnImp'+id).className += ' hidden';				
       		});		
	//empèche la propagation de l'événement
	e.preventDefault();
		
}
function voirData(id){
	console.log("voirData : "+id);
	var e = window.event;
	idFicImport = id;
	$.get(urlP+'import/getdataficvente',
			{idFic:id},
        		function(js){
				config.gridImportVenteData.columns=js.col;
			    config.gridImportVenteData.records=js.rs;
			    if(w2ui.grid_ImportVenteData)
			    		w2ui.grid_ImportVenteData.destroy();        
			    w2ui.layout_ImportVente.content('main', $().w2grid(config.gridImportVenteData));
       		},'json');		

	//empèche la propagation de l'événement
	e.preventDefault();
}
function calculerData(id, tp){
	console.log("voirData : "+id);
	var e = window.event;
	idFicImport = id;
	var div = document.getElementById('mainDivImport');
	w2utils.lock(div, { spinner: true, opacity : 1 });
    w2popup.lock("traitement en cours", true);
	
	$.get(urlP+'import/calculervente',
			{idFic:id, type:tp},
        		function(html){
				w2utils.unlock(div);
				w2alert(html);
				//cache le bouton calculer
				document.getElementById('btnCalculer'+id).className += ' hidden';				
       		});		

	//empèche la propagation de l'événement
	e.preventDefault();
}
</script>
<?php 
if(!$this->ajax){
	echo '</body>
</html>';
}else{
	echo '<script type="text/javascript">
			$(function () {
				initFileUpload();
				initImportVente(); 
			});                       		
		</script>		
		';	
}
