<?php 
$toolbar="false";
$idGrid = "gInst_".$this->typeObj."_".$this->idObj;

if(!$this->ajax){
	echo '<!DOCTYPE html>
<html>
	<head>
		<title>ISTE - Institutions</title>
		<link rel="stylesheet" type="text/css" href="css/w2ui.css" />
		<link rel="stylesheet" type="text/css" href="font/font-awesome/font-awesome.css" />
		<script type="text/javascript" src="js/jquery.min.js"></script>
		<script type="text/javascript" src="js/w2ui.js"></script>
		<script type="text/javascript" src="js/global.js"></script>
	</head>
<body>';
	$toolbar="true";	
}
?>
<div id="<?php echo $idGrid;?>" style="width: 100%; height: 200px;"></div>
<script type="text/javascript">
var config = {grid:
	    { 
        name: '<?php echo $idGrid;?>',
		header: 'Institution',		
        show: { 
			header			: true,		
            toolbar: true,
			toolbarReload   : <?php echo $toolbar;?>,
			toolbarColumns  : <?php echo $toolbar;?>,
            	toolbarSearch   : true,
            	toolbarAdd      : true,
            	toolbarDelete   : true,
            	toolbarSave		: true,
        },
        columns: [                
            { field: 'recid', caption: 'ID', size: '50px', sortable: true, resizable: true },
            { field: 'nom', caption: 'Nom', size: '120px', sortable: true, resizable: true, 
                editable: { type: 'text' }
            },
            { field: 'adresse', caption: 'Adresse', size: '180px', sortable: true, resizable: true,
                editable: { type: 'text' }
            },            
            { field: 'code_postal', caption: 'Code Postal', size: '80px', sortable: true, resizable: true, 
                editable: { type: 'text' }
            },
            { field: 'ville', caption: 'Ville', size: '80px', sortable: true, resizable: true, 
                editable: { type: 'text' } 
            },
            { field: 'pays', caption: 'Pays', size: '80px', sortable: true, resizable: true, 
                editable: { type: 'text' } 
            },
            { field: 'telephone', caption: 'Téléphone', size: '80px', sortable: true, resizable: true, 
                editable: { type: 'text' } 
            },
            { field: 'mail', caption: 'E-mail', size: '80px', sortable: true, resizable: true, 
                editable: { type: 'text' } 
            },
            { field: 'url', caption: 'URL', size: '80px', sortable: true, resizable: true, 
                editable: { type: 'text' } 
            }
        ],
        records: [
            { recid: 1, nom:"Paris 8", adresse:"24 rue de la liberté"
                , code_postal: '12346', ville: 'Saint Denis', pays:'France'
                , telephone:"0778987867", mail:"samszo@free.fr", url:"hhtp://jkhqkjhu" }
        ],
        onSave: function(event) {
            console.log(event);
        },
        onDelete: function(event) {
            console.log(event);
        },
        onAdd: function(event) {
            w2ui.<?php echo $idGrid;?>.add({ recid: w2ui.<?php echo $idGrid;?>.records.length + 1 });
        }
    }
}
$(function () {
    $("#<?php echo $idGrid;?>").w2grid(config.grid);    
});

</script>
<?php 
if(!$this->ajax){
	echo '</body>
</html>';
}
?>